- src/abstractdataframe/io.jl
- test/dataframe.jl
Now support append
Also created a check_column_names in order to check the consistency of the column names with the target file.
> Support to Append

- src/RDA.jl
- test/RDA.jl
Another round of RDA performance polishing:
1. Make long R vectors support optional. Disable by default on 32-bit systems (it's unlikely many people work with big dataframes on 32-bit systems, and in all other cases iterating over Int64 variable just slows everything down), R does the same.
2. Get >20% improvement in time and memory by improving type inference of IO variable. Before:
```bash
[~]$ julia -e "using DataFrames; @time read_rda(\"test.RData\")"
elapsed time: 15.414509979 seconds (2433718088 bytes allocated, 5.44% gc time)
```
after
```bash
[~]$ julia -e "using DataFrames; @time read_rda(\"test.RData\")"
elapsed time: 12.278712969 seconds (1834821860 bytes allocated, 3.38% gc time)
```
> Optimize RDAIO

- src/abstractdataframe/io.jl
- test/io.jl
Empty files are now treated the same as non-existent files in append mode.
> Fix writetable test for Windows, writetable bug

- src/abstractdataframe/reshape.jl
- test/show.jl
* Update RepeatedVector with both inner and outer arguments.
* Delete EachRepeatedVector (superseded by the new RepeatedVector).
* Add docstrings to reshape.jl.
For the docstrings, they are plain strings without the `@doc...`. These should work with Docile/Lexicon, but I don't think the feature has been put in 0.4, yet. In any case, they don't do anything now. If/when we decide on a docstring format, these can be updated. (Or, I can rip them out if you want.)
> Updates to reshape

- src/RDA.jl
RDatasets starting giving errors on julia 0.4, which are fixed by this PR.
```
julia> dataset("datasets", "iris")
ERROR: MethodError: `read_rda` has no method matching read_rda(::UTF8String)
in dataset at /Users/dcjones/.julia/v0.4/RDatasets/src/dataset.jl:6
```
> Allow non-ASCII filenames in read_rda.

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
#782, with an additional syntax deprecation fix.
Fixes #781, closes #782.
> Accept AbstractVector in describe()

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
Fixes the following:
```jl
_
_       _ _(_)_     |  A fresh approach to technical computing
(_)     | (_) (_)    |  Documentation: http://docs.julialang.org
_ _   _| |_  __ _   |  Type "help()" for help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 0.3.8 (2015-04-30 23:40 UTC)
_/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin13.4.0
julia> vcat([])
0-element Array{None,1}
julia> vcat([])
ERROR: BoundsError()
in _colinfo at /Users/rene/.julia/v0.3/DataFrames/src/abstractdataframe/abstractdataframe.jl:686
in vcat at /Users/rene/.julia/v0.3/DataFrames/src/abstractdataframe/abstractdataframe.jl:660
```
> fix vcat for empty arrays

- src/dataframe/io.jl
I triggered a BoundsError here, when loading a severely corrupted file.
> Prevent a BoundsError

- src/abstractdataframe/abstractdataframe.jl
Here's a silly example to reproduce MethodError:
```
DataFrames.by(DataFrame(a=[1,2], b=[3,4]), :a) do r
DataFrames.by(r, :b) do p
join(r,p, kind=:left, on=:a)
end
end
```
> Implement length(::Cols) for abstract dataframes.

- src/statsmodels/formula.jl
julia 0.3.8 does not support Uint8(x::Int64), causing an error in the dropUnusedLevels! function. Switched from type constructor to convert invocation to fix.
> fixed type error when converting Int64 to Uint8

- src/abstractdataframe/show.jl
Hi,
in Julia 0.4 `Version 0.4.0-dev+5511 (2015-06-22 05:05 UTC)`  **Commit 1e081b7***,
DataFrames does not load (neither does Gadfly) because of **local declaration in global scope** error:
```
ERROR: LoadError: LoadError: syntax: local declaration in global scope
in include at ./boot.jl:254
in include_from_node1 at ./loading.jl:133
in anonymous at no file:110
in include at ./boot.jl:254
in include_from_node1 at ./loading.jl:133
in reload_path at ./loading.jl:157
in _require at ./loading.jl:69
in require at ./loading.jl:52
while loading /home/alain/.julia/v0.4/DataFrames/src/abstractdataframe/show.jl, in expression starting on line 49
while loading /home/alain/.julia/v0.4/DataFrames/src/DataFrames.jl, in expression starting on line 79
```
With proposed patch, it …
> Corrects "local declaration in global scope" (0.4  Commit 1e081b7*)

- src/abstractdataframe/abstractdataframe.jl
This gets tests passing for me on 0.3.9 and 0.4-dev
fixes #830
> fixed "describe" override for 0.4

- src/abstractdataframe/join.jl
For joining, the unique combinations of values in the joined columns are indexed in the pooled data array. In the current code the size of the resulting pool is the dramatic overestimation of the actual number of unique combinations (and of the number of rows altogether). Because this pool has to be allocated, it can easily bring the system to the knees even if the joined data frame would only have 1000 rows.
The PR fixes the issue by reindexing the value combinations and allocating the optimal pool.
> Fix the multicolumn join memory disaster

- src/abstractdataframe/join.jl
- test/join.jl
Bug: the result contains as many left frame row copies as they have matches in the right frame
Expected: each left frame row appears once in the result, if there is a match
> Fix semi-join

- src/statsmodels/statsmodel.jl
- test/statsmodel.jl
`predict(mm::DataFrameRegressionModel, df::AbstractDataFrame)` currently returns a vector of length lower than `size(df, 1)` when there are missing regressors in the dataframe `df`,
I think it should always return a vector of length equal to `size(df, 1)` (potentially with missing values), so that it remains aligned with the initial dataframe, and so that one can  do
```
df[:yp] = predict(mm, df)
```
I know missing values are currently being redone so this pull request won't impact anything - but this is a general discussion and rewriting the current predict function makes my point clearer.
> predict on dataframes with missing rows

- doc/source/joins_and_indexing.rst
This appears to be a common point of confusion for new users.  Also clarify that there is no way to join on keys which have different names in the two data frames.
> Give an example of the syntax for joining on multiple keys

- src/abstractdataframe/io.jl
The number of rows written in `writemime` is now `min(n,tty_rows)` but the condition for writing the trailing &vellip; characters was `n > 20`.
> Suppress &vellip; characters when 20 < n < tty_rows

- src/abstractdataframe/abstractdataframe.jl
Fix #852 by using the new v0.4 syntax for documenting multiple things at once.
The downside is that method definitions must precede the documentation block.
CC @simonbyrne
> Use "multidoc" syntax

- doc/source/introduction.rst
Removed extra "with" and reworded/simplified a sentence to improve readability.
> Minor typos in the `DataFrames` documentation page

- src/abstractdataframe/reshape.jl
- test/dataframe.jl
This fixes column names in unstack when called without a key column.
Also added a test for this method.
> Correct a bug in a different unstack method

- src/statsmodels/formula.jl
This fixes the concat deprecation warning in DataFrames.allvars(ex:Expr):
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
> fixes concat deprec warning in allvars(ex::Expr)

- src/abstractdataframe/reshape.jl
Two functions share the signature:
```function unstack(df::AbstractDataFrame, colkey::Int, value::Int)```
Both functions were added in d0d7ff7f99d9713fad97dac2e1b637c4571f4684
> removed hidden unstack function that was never called

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
vcat should not try to copy data from a DataArray that only contains missing values.
> vcat: NA should be promoted to any type

- README.md
This was spurred on by the discussion on julia-dev about package maintenance:
https://groups.google.com/forum/#!topic/julia-dev/vLalAXOhogg
I've updated the README to attempt to clarify package maintenance. Some issues:
* I don't think the collaborators group I linked to is public. It would be nice if contributors could see who can merge PR's. 
* DataFrames has generally had a de facto lead maintainer. I started to write something that included some history there, but I didn't come up with anything that was concise and useful. 
Suggestions on the README are welcome as are suggestions on maintenance approaches for DataFrames.
> [RFC] Clarify package maintenance

- src/dataframe/io.jl
- test/io.jl
Silently altering the column names of a file is not always desired. This PR adds an option to turn it off in when calling readtable.
> make name normalization optional

- REQUIRE
- src/abstractdataframe/show.jl
Fixes #907.
This can either be merged as-is, or wait for a new version of Compat with support for `displaysize` to be tagged (cf. https://github.com/JuliaLang/Compat.jl/pull/172).
> Fix tty_cols()/tty_rows() deprecation

- doc/source/io.rst
The description of the falsestrings::Vector{ASCIIString} option in the documentation has been changed to indicate that the strings in the vector represent a Boolean false instead of a Boolean true.
> Fix falsestrings doc description for readtable

- src/abstractdataframe/io.jl
- test/io.jl
Previously, single and double quotes were escaped regardless of the quotemark.
Added two related unit tests to avoid future regression
> Changed printtable to escape only the quotemark character.

- .travis.yml
- REQUIRE
- docs/io.md
- src/DataFrames.jl
- src/dataframe/io.jl
- test/io.jl
I find it handy to have a macro to wrap `readtable` to make it easy to include small-to-medium amounts of data directly alongside code as a nonstandard string literal.  E.g., instead of writing
```julia
data = DataFrame(
name=["Alice","Bob","Carol","Eve"],
age=[36,24,58,49],
numPetSquid=[3,0,2,7])
```
one can instead write
```julia
data = df"""
name,  age, numPetSquid
Alice,  36,           3
Bob,    24,           0
Carol,  58,           2
Eve,    49,           7"""
```
This seems like a common enough need/convenience that I thought it was worth suggesting as an addition to the package. I'm pretty inexperienced at contributing patches, so please let me know if it seems like a worthwhile idea but needs improvement for inclusion.
> Adding macro df_str

- .travis.yml
- REQUIRE
- src/statsmodels/statsmodel.jl
These were just added to StatsBase (https://github.com/JuliaStats/StatsBase.jl/pull/146).
Tests won't pass until we tag a new StatsBase release. This PR is required to actually implement these functions in GLM.jl (https://github.com/JuliaStats/GLM.jl/pull/115), since tests there need methods working on `DataFrameRegressionModel`.
> Delegate new functions for statistical models

- REQUIRE
This works, but may as well be consistent
> Remove nonstandard v from version number in REQUIRE

- src/dataframerow/dataframerow.jl
In Julia 0.4.3 indexing into DataFrameRows with some child of AbstractArray produced a deprecation warning. This should now be fixed.
> Fix DataFrameRow's getindex deprecation warning.

- src/RDA.jl
- src/abstractdataframe/io.jl
- src/abstractdataframe/show.jl
- src/dataframe/dataframe.jl
- src/other/utils.jl
- test/io.jl
Accidentally, I also changed `AbstractString` in https://github.com/JuliaStats/DataFrames.jl/pull/957 and it caused https://github.com/JuliaStats/DataFrames.jl/issues/963. This PR should fix this.
> Undo restriction of AbstractString to String

- src/groupeddataframe/grouping.jl
- test/grouping.jl
Using the storage size of the first PDA does not make sense, since it can have
very few levels, and yet its combination with other columns may produce a lot
of them. UInt32 will be enough for any reasonable number of levels.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/960.
> Fix InexactError in groupby() due to too many levels

- src/dataframe/io.jl
- src/statsmodels/formula.jl
- test/dataframe.jl
- test/io.jl
- test/statsmodel.jl
This really needs to remain UTF8String on Julia 0.4.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/969.
> Fix passing UTF8String to readtable's eltypes argument

- src/dataframe/io.jl
nastrings is often specified separately from truestrings and falsestrings,
yet ParseOptions required the vector types to be the same. Also clean
a few details related to the port.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/978.
Cc: @andreasnoack
> More fixes to String porting

- REQUIRE
- src/abstractdataframe/join.jl
- src/abstractdataframe/reshape.jl
- src/groupeddataframe/grouping.jl
- src/subdataframe/subdataframe.jl
- test/grouping.jl
This function lives in DataArrays and is mostly redundant with
Base.repeat(). Use the latter where possible, or custom code
when not, so that we can deprecate rep().
Cf. https://github.com/JuliaStats/DataArrays.jl/pull/186.
> Stop using rep()

- src/abstractdataframe/abstractdataframe.jl
- src/other/index.jl
- src/other/utils.jl
- test/index.jl
- test/utils.jl
This fixes #972 by adding `strict` argument to `make_unique`, `Index` and `names!`.
If this fix PR is accepted `strict` can be added to `DataFrame` constructors to handle duplicate column names in similar way.
> Add strict checking of duplicates in names!

- src/abstractdataframe/join.jl
- test/join.jl
PooledDataVecs() uses the smallest possible integer size, but
the DataFrames code stores higher references than that in the vector.
Always use UInt32, which will be enough for any reasonable number of
levels.
Maybe PooledDataVecs() should not compact its result by default
(which makes it type-unstable), but this should be considered as part
of a larger rework.
Fixes the second issue at https://github.com/JuliaStats/DataFrames.jl/issues/960.
> Fix InexactError in join() due to too many levels

- README.md
- src/other/utils.jl
It only existed for a short period in the 0.4 development cycle. This
made the test fail on 0.5.
> Remove "stagedfunction" from reserved words

- REQUIRE
A bug with repeat() on Julia 0.4 makes tests fail with previous versions.
> Bump dependency on DataArrays to v0.3.4

- REQUIRE
- src/statsmodels/statsmodel.jl
`R2` et al. from StatsBase have been deprecated in favor of lowercase names.
> Update deprecated functions in StatsBase

- src/DataFrames.jl
- src/RDA.jl
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/io.jl
- src/abstractdataframe/join.jl
- src/groupeddataframe/grouping.jl
- src/other/index.jl
- src/statsmodels/formula.jl
- test/dataframe.jl
Import some operators instead of using `Base.(operator)` referencing for compatibility between 0.4 and 0.5
Make some array comprehensions Any such that they can be used in the `DataFrame` constructor
Adapt to shape preserving comprehensions
Some String stuff
cc: @ararslan
> Updates for Julia 0.5.

- test/io.jl
Fixes tests on 0.5 master on Windows by normalizing line endings in both input files.  In 0.4 the two
files read in with `\n` and `\r\n`, whereas they both are read in normalized
to `\n` on 0.5.
> Handle normalization of EOL in 0.5

- test/statsmodel.jl
Cleans up tests of `show` by always passing to an `IOBuffer`.
> use iobuffer for quiet show in statsmodel test

- src/statsmodels/formula.jl
- test/formula.jl
This fixes and tests an issue that showed up in MixedModels, wherein `coefnames` was attempting to index into an empty array because it was iterating over the full model frame terms, not the terms after dropping the response and random effects.
> In coefnames, iterate over the terms after dropping, not the full set

- src/abstractdataframe/io.jl
Replacing call to tty_size with displaysize(io) to address deprecation warning for Julia 0.5.  This call is triggered when displaying a DataFrame in a Jupyter notebook via IJulia.
> Address tty_size deprecation warning

- src/groupeddataframe/grouping.jl
- src/groupeddataframe/show.jl
- test/grouping.jl
grouping on an empty data frame should not crash. `combine` can't create additional columns but returning an empty data frame is better than crashing.
Similarly, showing an GroupedDataFrame in the REPL should not assume that it's non-empty.
> don't assume groups are non-empty

- src/statsmodels/formula.jl
- test/formula.jl
As discussed in #614 - coming back to this now that #870 and #1017 have been merged.
> RFC: Sparse ModelMatrix support

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
collect doesn't recognize the common type if the arguments are of mixed types
> vcat collect type

- src/DataFrames.jl
- src/abstractdataframe/io.jl
- src/abstractdataframe/show.jl
> Allow arguments to displaysize on 0.4

- test/deprecated.jl
- test/runtests.jl
Fixes #1064
CI should be green once this is tagged, and PkgEval should be as well if we tag afterward.
> Remove deprecation test

- src/statsmodels/formula.jl
Some downstream packages (like FixedEffectModels) call the direct `ModelFrame` constructor rather than use the outer constructor functions. This PR provides compatibility with the pre-#870 signature for that constructor method.
> Add compatibility with pre-contrasts ModelFrame constructor

- src/statsmodels/formula.jl
Addresses slow row-wise `SparseMatrixCSC` indexing when building sparse model matrix columns by transposing the contrast matrix before reindexing column-wise, then transposing the result (rather than just reindexing row-wise).
> Faster sparse model matrix construction

- src/dataframe/dataframe.jl
- test/index.jl
Closes #1053 (replacing it). Fixes #1051. Closes (maybe?) #1054, pending possible further discussion.
This implements @nalimilan and @andreasnoack's idea of filling arrays with scalars instead of creating new ones.
> Fill existing arrays with scalars

- src/dataframe/sort.jl
- test/sort.jl
```
> df = DataFrame(a=[2,1]);
> df[:b] = df[:a];
> sort!(df, cols=:a)
2×2 DataFrames.DataFrame
│ Row │ a │ b │
├─────┼───┼───┤
│ 1   │ 2 │ 2 │
│ 2   │ 1 │ 1 │
```
The column `:a` is not sorted here. This happens because `:b` and `:a` refer to the same array which gets permuted twice. By skipping duplicated columns in the permutation we get the correct result.
```
2×2 DataFrames.DataFrame
│ Row │ a │ b │
├─────┼───┼───┤
│ 1   │ 1 │ 1 │
│ 2   │ 2 │ 2 │
```
> Only sort duplicated columns once

- src/groupeddataframe/grouping.jl
- test/data.jl
Resolves `WARNING: [a] concatenation is deprecated; use collect(a) instead`
> collecting with brackets is deprecated

- src/groupeddataframe/grouping.jl
- test/data.jl
Use vcat() instead of collect() in colwise(), and identity() instead of abs(),
since the latter do not work with Nullable.
--------------
I introduced test failures when merging https://github.com/JuliaStats/DataFrames.jl/pull/939, as the fact that test passed when the PR was opened does not indicate that it still works today (even if there are no merge conflicts). We should probably close and reopen all PRs filed before the port before merging them.
> Fix test failures on master

- docs/src/man/getting_started.md
@nalimilan suggested in #1008 that we add links to packages that provide query functionality to the documentation. This adds a section to the documentation that links to DataFramesMeta and Query.
@tshort Are you ok with this?
@davidagold Should I add a link to StructuredQueries as well, or do you want to add that later?
> Add querying section with links to other packages to documentation

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/reshape.jl
- src/groupeddataframe/grouping.jl
- test/cat.jl
- test/grouping.jl
- test/join.jl
Several changes that looked too small and innocent for a separate PR:
* more tests for corner-case joins/groupings/assignments
* implement `AbstractVector` interface for `Cols` (mostly required to allow `map!(..., columns(df))` for `SubDataFrame`)
* some optimizations for `GroupedDataFrame` (avoiding array reallocation, improving type inference)
> Misc minor enhancements

- src/abstractdataframe/io.jl
- test/REQUIRE
- test/io.jl
At the moment DataFrames look great in IJulia (thanks to #433) until they are exported to PDF. This commit adds an additional `writemime` method for the `text/latex` mimetype.
> Output to LaTeX added (useful for IJulia notebook export to PDF)

- src/statsmodels/formula.jl
- test/formula.jl
> handle `A ~ B - 1` and add tests

- src/abstractdataframe/join.jl
- test/join.jl
Also return a NullableCategoricalArray from sharepools() since
the code currently doesn't check that no null values are present.
anyway this function is internal and the change imposes no overhead.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/1088.
> Fix join when mixing NullableArray and Array{Nullable}

- REQUIRE
- src/statsmodels/statsmodel.jl
> Update StatsBase.df to dof

- src/abstractdataframe/io.jl
- test/io.jl
> limit attribute of IOContext is used for html generation

- src/dataframe/dataframe.jl
- test/dataframe.jl
It seems to be a little more difficult than it should be to pass a container of columns to the `DataFrame`'s constructor. This change lets you, e.g.
```julia
DataFrame([[1,2,3]], [:a])
```
Before this would complain because `[[1,2,3]]` is of type `Vector{Vector{Int}}` which is not a subtype of (concrete) type `Vector{Any}` (type parameters aren't convariant). This will automatically loosen the type parameter for the column container, if necessary.
> Loosen constructor for a DataFrame

- REQUIRE
- src/abstractdataframe/show.jl
- test/REQUIRE
- test/show.jl
This patch adds an extremely lightweight dependency on Juno.jl, and implements rich display inside of Juno, like so:
In future I'd like to improve on this by having access to the entire dataframe rather than truncating it, but this is something for now.
> Juno Display

- docs/src/man/joins.md
The instruction to rename columns if they don't match was part of the docs previously (http://dataframesjl.readthedocs.io/en/latest/joins_and_indexing.html). I adapted the syntax to avoid using {}.
> Update joins doc to include rename!

- src/abstractdataframe/show.jl
- test/show.jl
These are rare enough to be untested, and Strings have a fast path which
is different from Nullable{String}. The +2 must be a remnant from a time when
we printed the quotes.
By the way, fix indentation and a deprecation in the previous example, which
is similar.
(Errors on nightlies are unrelated.)
> Fix computation of column width for Array{String} columns

- .gitignore
- src/abstractdataframe/reshape.jl
- test/data.jl
In R's `reshape2::melt`  it is possible to use a custom name for the newly created stacked columns. This adds two optional keyword arguments that allow this behaviour (demonstrated below).
I have added tests, but I would like to see if I can simplify the diff. I'd like to avoid having to define these kwargs for all the various `stack` and `melt` invocations (suggestions welcome).
```julia
julia> d = DataFrame(red=rand(2), blue=rand(2), green=rand(2), sample=["A", "B"])
2×4 DataFrames.DataFrame
│ Row │ red      │ blue     │ green    │ sample │
├─────┼──────────┼──────────┼──────────┼────────┤
│ 1   │ 0.134251 │ 0.668584 │ 0.463817 │ A      │
│ 2   │ 0.784527 │ 0.46851  │ 0.634924 │ B      │
julia> ds = stack(d, [:red, :blue, :green])
6×3 DataFrames.DataFrame
│ Row │ variable │ value    │ …
```
> ENH: stack: allow naming of measure/value column names

- docs/src/man/reshaping_and_pivoting.md
This example has not been updated after [1:4] stopped returning a Vector{Int}
in Julia 0.5.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/1162.
> Fix stack() example in manual

- docs/src/man/split_apply_combine.md
While in aggregate function it is explicitly stated column (or columns) that was not the  case with the description of the `by` function.
> Precised that by can use multiple columns to split

- docs/src/man/formulas.md
- src/DataFrames.jl
- src/statsmodels/formula.jl
- test/formula.jl
- test/statsmodel.jl
This copies over the definition of `@formula` from StatsModels and deprecates `@~` for Julia versions where `~` parses as an infix macro rather than a regular call.
> Replace bare tilde with formula macro

- README.md
Builds have stalled for several weeks on the current account on which
current maintainers have no control.
Backport of https://github.com/JuliaStats/DataFrames.jl/pull/1153/, which was only applied on master (now DataTables).
> Move AppVeyor to another account

- src/statsmodels/formula.jl
julia v0.6 deprecates `!retrms` in favor of `.!retrms` but that syntax is not available in v0.5 or through the `Compat` package
> Suppress deprecation warning in v0.6

- docs/src/man/joins.md
ID in example output was duplicated. Make ID distinct from row number, to avoid confusion. Align examples.
> Fix typo in example

- src/subdataframe/subdataframe.jl
- test/data.jl
Non-`Int64` row-indices were not being correctly converted to `Int64`.
- explicit conversion to `Vector{Int64}`
- test-cases added
Interestingly, this came up only when DataFrames was precompiled into a userimg (see JuliaLang/julia#21164) and only after the rename of `sub()` to `view()`
> Fix handling of non-Int row indices

- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
- test/data.jl
- test/dataframe.jl
- test/join.jl
Also fix some uses of all(isna(x)) and any(isna(x)), and avoid computing
the number of missing values twice in describe().
@ararslan I'm not sure whether I should bump the dependency on DataArrays. AFAICT this form worked before the deprecation was added, since it's possible since Julia 0.5, right?
> Fix isna, allna and anyna deprecations

- src/dataframe/io.jl
- src/statsmodels/formula.jl
- test/dataframe.jl
- test/formula.jl
- test/io.jl
- test/statsmodel.jl
Closes #1202.
Replaced all instances of Compat.UTF8String with String.
NOTE: Compat deprecated UTF8String when it dropped julia-0.4 support.
> Fixed Compat UTF8String deprecation warnings.

- docs/src/man/getting_started.md
- src/dataframe/dataframe.jl
- test/constructors.jl
Created a `DataFrame` constructor that uses pairs. Works similarly to the keyword argument constructor but allows you to use column names that are Julia keywords:
```julia
julia> DataFrame(type=[])
ERROR: syntax: unexpected "="
julia> DataFrame(:type => [])
0×1 DataFrames.DataFrame
```
> Pair Constructor

- docs/make.jl
Whenever tests failed on nightlies, the manual was not deployed.
> Deploy Documenter manual from Julia 0.6 rather than from nightlies

- README.md
DataFrames no longer uses DataArrays, and we don't want to recommend
using DataTables now.
> Remove mention of DataTables and DataArrays in README

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
> `isempty(df)` should return true if either dimension == 0.

- src/abstractdataframe/io.jl
- test/io.jl
Otherwise `allocate(::Type{T}, rows, ref) where {T <: Union{WeakRefString, Null}}` method gets called resulting in an error.
> Add allocate(::Type{Null})

- REQUIRE
- src/abstractdataframe/show.jl
- test/io.jl
- test/show.jl
Incrementally improving `show` for `DataFrames`.
In this PR I propose to indicate `null` with a star. This way one can distinguish `null` from `"null"` and `:null` as can be seen in test cases.
Additionally as `*` is put in an unused visual column it helps to spot null values in a data frame.
> Improve show in corner cases

- test/cat.jl
- test/conversions.jl
- test/data.jl
With Nulls 0.0.7, `1 == null` and `null == null` return `null`. Prepare
tests to this new behavior.
> Adapt to new == behavior with nulls

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
- test/constructors.jl
- test/data.jl
- test/dataframe.jl
- test/duplicates.jl
- test/join.jl
This is consistent with `null == null` returning `null` in the next Nulls release (https://github.com/JuliaData/Nulls.jl/pull/33), but does not depend on it. This was actually the old behavior when using DataArrays.
Note that with Nulls.jl master, things like `[1, null] == [1, null]` throw because `if null` is an error. We could probably fix that by providing a special method for `==(::AbstractArray{:>Null}, ::AbstractArray)`, but that would cover  `==(::Array{Any}, ::Array{Any})`... We should discuss that in Nulls.jl. Tests do not appear to cover this, so we should add a few when it works.
> Restore old == using three-valued logic, separate from isequal()

- src/deprecated.jl
This will ease the transition to CSV, without introducing a dependency on it
and without breakage due to behavior changes.
I tested this locally, but it's not covered by the test suite.
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1240.
> Reintroduce readtable(), writetable() and string-literal macros, keeping them deprecated

- src/abstractdataframe/abstractdataframe.jl
This is a fix to a rather critical stack overflow error that can occur when aggregating even modestly sized data sets.  See discussion [here](https://discourse.julialang.org/t/stack-overflow-in-dataframes-group-by/6357).
Fixes #1247.
> Fix StackOverflow in promote_col_type() when grouping with large number of groups

- src/dataframe/dataframe.jl
I think this was to get rid of a warning/error when a dependency of `DataTables` also imported `DataFrames` and the names conflicted? Either way, we don't need it anymore
> Remove disambiguation prefix

- .travis.yml
- README.md
- appveyor.yml
Allow failures on nightly for now until a release candidate for 0.7
is ready. Remove Julia package evaluator badge for 0.7 to be added back
later
> Update CI test badges

- REQUIRE
- src/deprecated.jl
Without it, the functions failed when working with compressed .csv.gz files.
Missed by https://github.com/JuliaData/DataFrames.jl/pull/1243.
> Reintroduce temporarily GZip dependency for deprecated CSV functions

- src/abstractdataframe/abstractdataframe.jl
- src/groupeddataframe/grouping.jl
- test/grouping.jl
This avoids compiling specialized methods for each number of arguments,
which can be very large when using `groupby()`. The code does not take
advantage at all of that information anyway. The code prior to
refactoring used to do that, by exporting
`vcat(::Vector{AbstractDataFrame})`. Use an internal method instead since
this is non-standard.
Incidentally, this fixes a small bug introduced in the refactoring: when
working with an empty data frame, `vcat()` was called, and it returns
`Any[0]`, which surprisingly implied the addition of a bogus `x1` column to
the result. The test was actually correct before refactoring.
Refactoring was done at https://github.com/JuliaData/DataTables.jl/pull/45. See also report at https://discourse.julialang.org/t/stack-overflow-in-dataframes-group-by/6357. …
> Avoid calling vcat(dfs...) in combine()

- src/dataframerow/utils.jl
- src/groupeddataframe/grouping.jl
- test/dataframerow.jl
- test/grouping.jl
The new argument allows skipping values with at least one null in one
of the grouping columns. Doing this in `groupby()` is more efficient
and more convenient than dropping them before calling `groupby()`.
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1249.
> Add skipnull argument to groupby()

- src/subdataframe/subdataframe.jl
This causes endless pain and headache because of https://github.com/JuliaLang/julia/issues/24447
> Remove include_string call

- src/abstractdataframe/join.jl
- test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1257
cc @alyst
> Ensure levels are maintained when joining df's with Categorical cols

- REQUIRE
- docs/src/man/getting_started.md
- src/abstractdataframe/abstractdataframe.jl
- src/groupeddataframe/grouping.jl
- src/other/index.jl
> Use skipmissing() instead of Missings.skip()

- docs/make.jl
Temporary until Query has been ported to DataFrames 0.11.0, so that
the updated manual is deployed.
> Disable doctests

- REQUIRE
- src/deprecated.jl
I'm not sure whether `writetable()` is already at its end-of-life stage, but if it stays for a while, it might be better to switch to `CodecZlib.jl` from `GZip.jl` as the latter is deprecated and not actively maintained.
> Switch to CodecZlib from GZip

- src/dataframe/dataframe.jl
- test/dataframe.jl
Convenient, and consistent with `categorical!`.
> Add one-argument version of allowmissing!()

- src/DataFrames.jl
This is not used so I think we can safely remove it.
> do not import :(==)

- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/cat.jl
Following the discussion in #1301:
* `hcat` now accepts `AbstarctVector` as first argument if the second argument is `DataFrame` and produces a `DataFrame` in result;
* `hcat` with `DataFrame` throws an error if something else than `DataFrame` or `AbstractVector` is passed as a second argument.
> Improve hcat for DataFrames

- src/abstractdataframe/reshape.jl
- test/data.jl
- test/dataframe.jl
Now `unstack` throw StackOverflow if it is passed vector of symbols or numbers. This PR restricts the types of passed arguments only to `Symbol` and `<:Real`.
> Restrict arguments of unstack to avoid StackOverflow

- src/deprecated.jl
It failed because of a name conflict introduced when porting from Null to Missing.
See https://discourse.julialang.org/t/how-to-read-a-table-with-missing-values-using-csv/7556/4.
> Fix readtable() in the presence of missing values

- REQUIRE
- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/dataframe.jl
- change behavior of `similar` on DataFrames to not auto-enable missing
value support and instead use same column eltypes as parent df
- add docstrings for `similar` and `allowmissing!`
- change behavior of `allowmissing!` on CategoricalArrays to preserve
correct Array type (which is a CategoricalArray)
- add `similar` to docs
Should fix https://github.com/JuliaData/DataFrames.jl/issues/1294 and https://github.com/JuliaData/DataFrames.jl/issues/1291, although it does not address the `append!` ideas presented in https://github.com/JuliaData/DataFrames.jl/issues/1291.
> Small improvements to missing value support

- src/abstractdataframe/join.jl
- test/join.jl
Banishes https://github.com/JuliaData/DataFrames.jl/issues/1297 to [**Closed**](https://github.com/JuliaData/DataFrames.jl/issues?q=is%3Aissue+is%3Aclosed)
> Support joining dataframes on columns with different left/right names

- src/DataFrames.jl
The current code calls `include()` in a loop. It confuses `Revise`, so it cannot handle `DataFrames` package in v0.6.
v0.7 should solve such problems, but since the loop doesn't really simplify or reduce the code, let's just remove it.
> Simplify source files inclusion

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Types should always implement the two-argument version, which is the most general method.
Follow the same approach as the AbstractArray implementation in Base.
See https://discourse.julialang.org/t/a-question-on-hashes/7742.
> Fix hash()

- REQUIRE
- src/abstractdataframe/reshape.jl
- test/dataframe.jl
Changes:
1) allow multiple columns in rowkeys
2) remove incorrect and slower implementation for single column in rowkey
> Refactor unstack

- src/abstractdataframe/join.jl
- test/join.jl
Currently, if you do a few joins, most of the columns in your data frame become "missable" (`>: Missing`).
That's because so far `join` preserves non-missingness only for inner joins:
* inner join doesn't introduce new missing values => non-missingness of columns from both left and right frames should be preserved.
This PR adds the other logical rules:
* left join doesn't introduce new missing values in the left columns => non-missingness of the left frame should be preserved
* right join doesn't introduce new missing values in the right columns => non-missingness of the right frame should be preserved
* joins do not introduce missing values to the on-columns => non-missingness of the on columns should be preserved if both left-on and right-on columns are non-missing
The rules above are …
> Preserve non-missingness during non-inner joins

- src/DataFrames.jl
- src/abstractdataframe/sort.jl
- src/dataframe/dataframe.jl
Introduced by https://github.com/JuliaData/DataFrames.jl/pull/1320.
> Fix failure due to calling pairs() on keyword arguments on Julia 0.6

- src/other/index.jl
- test/index.jl
Fixes #1321.
Additionally corrects signatures of `getindex`.
> make boolean indexing of Index strict

- docs/src/lib/functions.md
- docs/src/man/subsets.md
- src/abstractdataframe/abstractdataframe.jl
- test/data.jl
Currently these cannot be made efficient as the column types are not encoded in `DataFrameRow`, but this can be improved in the future with `NamedTuples`.
Closes https://github.com/JuliaData/DataFrames.jl/issues/43. See also https://github.com/JuliaData/DataFrames.jl/issues/323 and a previous `filter` function (with a different interface) which was removed in https://github.com/JuliaData/DataFrames.jl/commit/e47accbac6e9a92ca5f8b4776c337216deb3e7a2.
> Add filter() and filter!() methods

- src/abstractdataframe/reshape.jl
one method of `stack` called `stackdf` internally instead of `stack` (I guess it was a typo - not an intentional design decision).
> stack called stackdf and should call stack

- src/abstractdataframe/reshape.jl
- src/dataframe/dataframe.jl
- src/deprecated.jl
- src/other/index.jl
- test/data.jl
- test/index.jl
Currently `stack(df, :a, [])` produces StackOverflow.
With this PR we check that length of `measure_vars` and `id_vars` is at least 1.
> Redesign getindex and fix stack/melt StackOverflow error

- src/dataframe/dataframe.jl
- src/deprecated.jl
- test/constructors.jl
Following discussion in https://discourse.julialang.org/t/how-do-dataframes-jl-compare-to-rs-and-interoperability-between-r-and-julia/7387/14 I propose to:
1. Add a constructor of `DataFrame` from a `Matrix` that can take column names argument;
2. Add a method to `convert` allowing conversion from `Vector` to `DataFrame` (so that both the constructor and conversion work and work the same way);
> improve DataFrame constructors and conversions for Vector and Matrix

- src/deprecated.jl
Together with #1341 this should fix the tests of `RDatasets` on `DataFrames` master (although there are still lots of deprecation warnings which will be fixed by https://github.com/johnmyleswhite/RDatasets.jl/pull/48)
> Add deprecation for vcat(Vector{<:AbstractDataFrame})

- src/deprecated.jl
I.e. use the `CodecZLib` API since we don't load `GZip` anymore. This broke the `RDatasets` tests.
> Unbreak deprecated readtable(GZip)

- REQUIRE
- test/join.jl
These tests should fail until JuliaData/CategoricalArrays.jl#111 and #1316 are merged.
> Test non-matching joins

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
Fix for issue #1280 
I came across the same issue when using `vcat` to combine two DataFrames with a column of exclusively Missings so I figured I would just submit the fix.
> Fix combining DataFrames with a column of Missings

- src/dataframerow/utils.jl
Eachindex no longer accepts inputs of different length, so the `groupby` logic was incorrect in v0.7. This corrects the problem. Fixes the only (current) DataFrames.jl specific issue in #1349
> Behavior of eachindex has changed

- src/deprecated.jl
- src/other/index.jl
- test/cat.jl
- test/data.jl
- test/dataframe.jl
- test/index.jl
- test/join.jl
- test/utils.jl
This is a maintenance PR of test files adding:
* `makeunique` keyword where needed (except for one place with `getindex` taking the same column twice - this test case should be changed to throw an error after deprecation);
* cases of indexing into `Index` tests that are deprecated are removed and a list of cases to test for error after deprecation period is introduced; added tests for indices being `Integer` other than `Int`;
* in *join.jl* two parts of code are wrapped in `@testset` as they defined the same function twice.
> Fix tests for makeunique keyword and deprecated column indexing

- src/subdataframe/subdataframe.jl
- test/subdataframe.jl
PR filling missing functionality indicated in #1359.
> allow colon for rows and columns in DataFrame view

- test/show.jl
Constructing `DataFrame` with vector of values other than vectors is deprecated so in the test I change it to transpose of such a vector and we allow constructing from `AbstractMatrix`.
> change tests not to use deprecated DataFrame constructor

- src/abstractdataframe/sort.jl
- src/dataframe/sort.jl
- src/groupeddataframe/grouping.jl
- test/sort.jl
Shorter, as clear as the old form, and consistent with the array method
taking a region along which to sort and with JuliaDB. Also apply this change
to sort! and issorted.
> Deprecate sort(df, cols=c) in favor of sort(df, c) and add docstrings

- src/abstractdataframe/abstractdataframe.jl
Fixes #1358 until JuliaLang/julia#21256 is fixed.
The issue with `enumerate` somehow allocating during the loop seems fixed on Julia master (0.7/1.0).
Since this is a performance change, I don't quite know if and how to add a test. Suggestions?
> only test missing values if type has Missing

- src/dataframe/dataframe.jl
- test/dataframe.jl
`setindex!` had to be fixed as it created duplicate column names in corner cases:
```
julia>         df = DataFrame(rand(3,2), [:x3, :x3_1])
3×2 DataFrames.DataFrame
│ Row │ x3       │ x3_1     │
├─────┼──────────┼──────────┤
│ 1   │ 0.186789 │ 0.891261 │
│ 2   │ 0.675452 │ 0.587771 │
│ 3   │ 0.510852 │ 0.107851 │
julia>         df[3] = [1,2,3]
3-element Array{Int64,1}:
1
2
3
julia> df
3×3 DataFrames.DataFrame
│ Row │ x3       │ x3_1     │ x3 │
├─────┼──────────┼──────────┼────┤
│ 1   │ 0.186789 │ 0.891261 │ 1  │
│ 2   │ 0.675452 │ 0.587771 │ 2  │
│ 3   │ 0.510852 │ 0.107851 │ 3  │
```
> make setindex! not create duplicate column names

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
Implementation following discussion in #1347.
> vcat allowing column reordering

- src/dataframe/dataframe.jl
- test/dataframe.jl
Part three of implementation of #1372.
Changes:
* full coverage of `push!`
* full coverage of `categorical!`
* removed `push!` method that was not needed (duplicate in special case with no extra functionality and the same performance)
* cleaned up deprecated `Associative` references
* corrected documentation of `DataFrame(ds::AbstractDict)` constructor (it does not accept a vector but a dictionary)
> improve push! and categorical! test coverage

- REQUIRE
- src/dataframe/dataframe.jl
Probably introduced by the latest Missings.jl release, but that code needed to be updated for recent CategoricalArrays versions anyway.
> Fix CategoricalArray-related test failure

- src/abstractdataframe/sort.jl
- test/sort.jl
Resolves both problems from #1327.
In general `lt` function was broken when subsetting of `DataFrame` for `issorted` was performed.
@nalimilan CI will fail because of `CategoricalArray` bug. Need to rebase this PR after that one is merged, but currently it should be good for a review.
> fix issorted bug

- src/dataframe/dataframe.jl
- test/dataframe.jl
Following #1388 this PR always collects `AbstractRange` before assignment to a `DataFrame`. In this way we have consistency between constructor and `setindex!`.
> Always collect AbstractRange

- src/abstractdataframe/io.jl
- src/abstractdataframe/show.jl
- test/io.jl
Also change try... catch blocks to isassigned calls in show.jl, which is more correct and can avoid hiding bugs.
Fixes #1397.
> Fix error with undefined values in HTML printing

- src/abstractdataframe/show.jl
- src/abstractdataframe/sort.jl
- src/dataframe/sort.jl
- src/dataframerow/show.jl
A minor PR cleaning up remaining references to `Void` type in *DataFrames.jl* (only in documentation and comments).
> Rename Void to Nothing

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/reshape.jl
- src/other/utils.jl
- test/data.jl
- test/dataframe.jl
- test/show.jl
The remaining failure is fixed with DataStreams master.
> Fix tests on Julia 0.7

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/io.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/dataframerow/show.jl
- src/dataframerow/utils.jl
- src/subdataframe/subdataframe.jl
- test/cat.jl
- test/constructors.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/join.jl
- test/subdataframe.jl
Provides a nice shorthand syntax for simple getindex and setindex! uses, with autocompletion,
and makes `DataFrameRow` more like `NamedTuple`.
This requires replacing all direct field accesses with calls to accessor functions.
Do not mention this feature in the manual yet since it is not available on a released Julia
version. Most uses of `df[:col]` will better be changed to `df.col` when Julia 0.7 is released.
(CI failure on 0.7 is fixed with DataStreams master.)
Fixes #1336.
> Override getproperty, setproperty! and propertynames for AbstractDataFrame and DataFrameRow

- src/groupeddataframe/grouping.jl
- test/data.jl
Implementation of `aggregate` had a bug that threw error when one used column number for indexing as later the implementation assumes that column name as a `Symbol` is passed.
Example problem that is fixed:
```
julia> x = DataFrame(rand(3,4))
3×4 DataFrames.DataFrame
│ Row │ x1       │ x2        │ x3        │ x4       │
├─────┼──────────┼───────────┼───────────┼──────────┤
│ 1   │ 0.748279 │ 0.0678513 │ 0.260604  │ 0.390001 │
│ 2   │ 0.446409 │ 0.401046  │ 0.0651925 │ 0.649831 │
│ 3   │ 0.40989  │ 0.0341148 │ 0.197234  │ 0.184495 │
julia> aggregate(x, 1, sum)
ERROR: MethodError: no method matching _makeheaders(::Array{Base.#sum,1}, ::Array{Any,1})
Closest candidates are:
_makeheaders(::Array{T<:Function,1}, ::Array{Symbol,1}) where T<:Function at …
```
> Allow aggregate to use column number for aggregation

- src/dataframe/dataframe.jl
- test/dataframe.jl
Strictly checking column types was particularly problematic now that we support columns with both `Union{T,Missing}` and `T` element types.
See https://github.com/JuliaData/DataFrames.jl/issues/1291#issuecomment-397868499.
> Relax column type requirements in append! and improve behavior on error

- src/groupeddataframe/grouping.jl
- test/grouping.jl
This resolves #1431.
@nalimilan I was not sure which version of Julia should be a cutoff (or is there some other canonical way of supporting old and new iteration protocol).
> improve iteration protocol and fix assignment in combine

- docs/make.jl
- docs/src/man/getting_started.md
- docs/src/man/missing.md
It really does not belong right at the top of getting started.
It doesn't belong on that page at all -- everything else is concerned with creating dataframes,
or basic manipulation of them.
The missing section doesn't even mention them.
It is not the *first* thing someone getting started wants to see.
> Move Missing to it's own page in the Docs

- docs/src/man/getting_started.md
I think it is easier to navigate with section headings.
And the row-by-row construction is something I always forget how to do.
(and I think more useful than column by column)
> Add section headings and row-by-row construction example

- docs/src/man/getting_started.md
- src/abstractdataframe/show.jl
- test/show.jl
I think i figured out my git issues. Hopefully. 
This commit fixes the printing of `nothing`  by changing the function `ourshowcompact`.
> Fix printing of nothings

- src/deprecated.jl
With that I don't get any deprecation warnings anymore when loading the package on 0.7. Could we merge this and then tag a release? That would make life easier for downstream packages that are updating things to 0.7.
> Fix a deprecation warning

- src/abstractdataframe/iteration.jl
Updates iterator protocol to Julia 0.7.
I do not change protocol for `DataFrameRow` as it is changed in #1449 which is not merged yet.
> Update iteration protocol for row and column iterators to Julia 0.7

- src/abstractdataframe/abstractdataframe.jl
Fixes issue #1467 
The issue was that we didn't wrap `first(col)` and `last(col)` in `try.. catch` blocks. 
I saw two ways to fix the issue: 
1) Be lazy and wrap `first` and `last` in `try... catch` blocks, and changing the `stats` keyword agument so that we only return whether a column contains missing and the `eltype`
2) Be more robust and change the `stats` vector at the top *and* only calculate the statistics we need to calculate, resulting in this beautiful piece of code:
```
function get_stats(col::AbstractArray{>:Missing}) # there is another one for the non-missing case
nomissing = collect(skipmissing(col))
data_dict = Dict{Sumbol, Any}()
if :q25 in stats | :median in stats | :q75 in stats 
q = try quantile(nomissing, [.25, .5, .75]) catch [nothing, nothing, nothing] end …
```
> Make describe work for a zero-row DataFrame

- docs/src/man/querying_frameworks.md
The `Query.jl` links were out of date, so this change makes the documentation / integration that much smoother!
> Update Query.jl documentation links

- src/dataframe/dataframe.jl
- test/dataframe.jl
`permutecols!` exposes internal `DataFrame` structure in its return value. This PR makes it return the modified `DataFrame`.
> make permutecols! return modified DataFrame

- src/dataframerow/show.jl
- test/dataframerow.jl
Fix implementation of `show` for `DataFrameRow` which threw an error when `nothing` was passed. Now nothing (empty string) is printed - the same as when displaying `DataFrame`.
> fix show for DataFrameRow

- src/dataframe/dataframe.jl
... that was causing failures on 32-bit machines.  See discussion and appveyor link [here](https://github.com/JuliaLang/METADATA.jl/pull/17015).
This problem seems a little silly at first glance, so I fear I may be missing some part of what's going on here.
If this is indeed a proper fix, ideally it should be applied all the way back to 0.11, though to be honest I'm not sure what the easiest way of doing that would be (we could tag off new branches, but that seems somehow excessive).
> fixed overzealous type assertion

- src/dataframe/dataframe.jl
- test/constructors.jl
Now when constructors do not fall back to conversion we need to define `DataFrame(df::DataFrame)` constructor.
In general it should return a copy of a `DataFrame` but it is a breaking change, so I guess we should first keep the old behavior and return the same object and throw a deprecation - right?
> add DataFrame constructor accepting a DataFrame

- docs/make.jl
The documentation hasn't actually deployed to gh-pages since 0.6 was dropped on Travis.
> Bump julia version in docs/make.jl

- src/dataframerow/dataframerow.jl
- src/dataframerow/show.jl
- src/deprecated.jl
- test/dataframerow.jl
- test/deprecated.jl
- test/iteration.jl
This will allow changing iteration to return values instead of pairs, which is consistent with `NamedTuple` and `Vector`.
First step to fix https://github.com/JuliaData/DataFrames.jl/issues/1400. See also https://github.com/JuliaData/DataFrames.jl/pull/1439.
> Deprecate iterating over DataFrameRow in favor of pairs()

- src/abstractdataframe/iteration.jl
- test/iteration.jl
It might help inference in some cases. For `eltype` of `eachcol` I left the second element of the tuple to be `Any` as this is what we have in `DataFrame` implementation, but maybe `AbstractVector` would be better (the performance should be the same though I think).
> Add eltype to eachrow and eachcol

- src/dataframe/dataframe.jl
- test/constructors.jl
To complement #1495 I propose to finish deprecation error of vector of vectors constructor.
Now what Tables.jl integration proposed works like this:
```
julia> DataFrame([(a=1,b=2), (a=3, b=4)])
┌ Warning: passing columns argument with non-AbstractVector entries is deprecated
│   caller = top-level scope at none:0
└ @ Core none:0
1×2 DataFrame
│ Row │ x1             │ x2             │
├─────┼────────────────┼────────────────┤
│ 1   │ (a = 1, b = 2) │ (a = 3, b = 4) │
```
so the change in #1495 is breaking (although probably no one would do this 😄).
After this the above will be disallowed and Tables.jl will fill this gap.
> only allow vector of vectors in DataFrame constructor

- src/abstractdataframe/show.jl
- test/show.jl
This PR follows #1496 and adds showing of column types for `DataFrame` and avoids printing element types along their values.
The rules for abbreviating type names are the following:
1. print at least 8 characters unless type name is shorter;
2. if abbreviating print `…` at the end; when abbreviating terminate at first non-word (not `[a-zA-z_]`) character (and leave at least one character - this is a corner case if someone uses Greek etc.)
3. if type allows missing but is not `Any` print `⍰` and avoid printing `Missing` and also `Union` (if possible)
4. If column contents is wider than 8 characters and type name is wider then print as much characters as possible without widening of the column
This PR now will fail, because I have not updated tests as this is a bit cumbersome. I will …
> Add showing element types for DataFrames

- src/abstractdataframe/show.jl
- test/show.jl
Following https://github.com/JuliaData/DataFrames.jl/pull/1499#issuecomment-421594253.
Now it should be good. Actually I have corrected it in that old PR, but in the original code there was a problem with odd number of lines in the terminal. After that old PR there was a problem with even number of lines in the terminal (which was more visible as most terminals have 40 lines by default). Substracting `7` should fit on screen for even and odd number of lines in the terminal.
> Make sure show of DataFrame fits the screen right

- src/abstractdataframe/iteration.jl
- src/abstractdataframe/reshape.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/deprecated.jl
- src/other/index.jl
- src/subdataframe/subdataframe.jl
- test/data.jl
- test/dataframerow.jl
- test/deprecated.jl
- test/index.jl
This is a first (simpler) part to make #1380 clean after Julia 1.0. It concentrates on `getindex`.
What was deprecated is now an error.
Additionally I have reviewed whole DataFrames.jl to fix all `getindex` occurrences. There are some new deprecation warnings.
> Clean up getindex

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/io.jl
- src/abstractdataframe/join.jl
- src/abstractdataframe/reshape.jl
- src/dataframe/dataframe.jl
- src/groupeddataframe/grouping.jl
- test/cat.jl
- test/constructors.jl
- test/data.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/grouping.jl
- test/join.jl
- test/show.jl
This is needed to allow Tables integration to work with `AbstractVector` of `NamedTuples`. For example with this PR:
```julia
julia> DataFrame([(a=1, b=2)])
1×2 DataFrame
│ Row │ a     │ b     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 2     │
julia> using StructArrays
julia> DataFrame(StructArray([1+3im]))
1×2 DataFrame
│ Row │ re    │ im    │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 3     │
```
> tighten DataFrame of vector signature

- src/abstractdataframe/reshape.jl
in the future `df[:,c]` will create a copy so I change it to `df[c]`.
> make stackdf avoid copying a vector

- src/dataframe/dataframe.jl
- test/data.jl
- test/dataframe.jl
There was a one corner case that needed fixing that came out when analyzing `SubDataFrames` code 😄.
The problem is only with single-row `DataFrame` and `Bool` index.
> fix getindex for Bool argument

- src/dataframe/dataframe.jl
- test/dataframe.jl
- test/index.jl
But avoid making a redundant copy for the first column.
Also move related test out of test/index.jl, which is about testing the Index type
rather than indexing.
Replaces https://github.com/JuliaData/DataFrames.jl/pull/1052, continuing https://github.com/JuliaData/DataFrames.jl/pull/1057.
It's a bit weird that only the first column would actually be `===` to the passed vector. Would it be better to make copies for all columns?
> Avoid aliasing columns when assigning vector

- src/dataframe/dataframe.jl
- src/other/tables.jl
- test/cat.jl
- test/constructors.jl
- test/data.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/grouping.jl
- test/join.jl
- test/show.jl
This follows #1527. What I do:
1. make the that change as non-breaking as possible
2. change other constructors to follow the expected behavior
3. update tests (so that we have coverage of all cases) and clean-up tests where `AbstractVector` qualification is not needed
4. Make `DataFrame` internally use `Vector{AbstractVector}`.
5. Fix some indentation issues introduced (not sure if I spotted 100% cases)
The thing I was unsure of was what type `columns` should be. I decided for `Vector{AbstractVector}` not `Vector{<:AbstractVector}` as the latter could e.g. allow `Vector{Vector}` to sneak in, and then we would not be able to add other `AbstractVectors` to such a `DataFrame` (CC @nalimilan - any comment on this as you have also written `Vector{<:AbstractVector}` earlier).
> Make AbstractVector change in constructor clean and non deprecating

- REQUIRE
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/cat.jl
- test/dataframe.jl
This new interface allows removing special cases for `CategoricalArray` and making the code more general. It also makes it easier to stop calling `promote_col_type(data...)` which triggers a stack overflow when the number of input arguments is high.
This relies on promotion rules which have been fixed in CategoricalArrays 0.3.14 (https://github.com/JuliaData/CategoricalArrays.jl/pull/159), and which give a slightly different behavior: now combining a `CategoricalArray` with an `Array` gives an `Array`, since the number of unique levels could be very high.
Fixes https://github.com/JuliaData/DataFrames.jl/pull/1472, https://github.com/JuliaData/DataFrames.jl/issues/1532, and replaces https://github.com/JuliaData/DataFrames.jl/pull/1473.
> Use Tables.allocatecolumn to simplify and improve code

- src/abstractdataframe/io.jl
- test/io.jl
I think in most cases `show` for HTML will be used in IJulia, where it is useful to have `eltype` printed as in terminal (I can image using this output to produce a report, where `eltype` type is uninteresting, but I would assume this is a relatively rare case; maybe we should add a kwarg that would handle this case?). This PR adds this functionality.
I left out LaTeX output without `eltype` as I guess in most cases when people use `show` to LaTeX they would want a table for publication so `eltype` is not needed.
> add column type in HTML show

- src/groupeddataframe/show.jl
- test/show.jl
Actually print grouping columns instead of always `:A, :B`. Also use singular or plural depending on number of groups.
Fixes #1538.
> Fix GroupedDataFrame printing

- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/subdataframe/subdataframe.jl
- test/cat.jl
- test/subdataframe.jl
A small PR that prepares for `df[:, cols]` to make a copy of columns. It should introduce no functional changes as of now.
> Make setindex! and hcat use column alias where possible

- src/dataframe/dataframe.jl
- test/dataframe.jl
Changed the dispatch of base.push! from Base.push!(df::DataFrame, dict::AbstractDict) to Base.push!(df::DataFrame, col::Union{AbstractDict, NamedTuple}). This seems to be enough to fix the issue.
This is my first PR EVER, I'm sorry I made any mistakes and will appreciate any guidance or correction
Fixes #1385.
> Fix push! for NamedTuple

- src/groupeddataframe/grouping.jl
- test/grouping.jl
@nalimilan That is how later we have to fix things 😄.
A small fix to `==` because when `cols` are different we know that `GroupedDataFrame`s do not match even if their parents have `missing`s.
> fix == for GroupedDataFrame

- src/abstractdataframe/reshape.jl
- src/abstractdataframe/sort.jl
- src/dataframe/dataframe.jl
- src/other/index.jl
- src/other/utils.jl
This PR removes `mutable` from struct definitions where possible.
Exceptions are: `GroupedDataFrame` (this is handled in #1558) and `Index` (which is mutated internally with `names!` - but maybe we can decide to reimplement `names!` and avoid `mutable` there also).
> Remove mutable structs

- src/groupeddataframe/grouping.jl
- test/data.jl
October is about to end, so I proposed to solve #1276.
I use standard `DataFrame` constructor machinery to generate names. The default suffix for lambda function is `λ`.
Also added `makeunique` keyword argument as it was missing (as here I guess we should set it to `true` it by default).
I do not know a better approach to test if a function is anonymous than by checking if first character of its name is `#` (maybe there is a cleaner solution to this?).
> improve naming of anonymous functions in aggregate

- src/dataframerow/dataframerow.jl
- test/dataframerow.jl
PR following discussion in #1564.
> convert for DataFrameRow

- src/dataframerow/utils.jl
Since `hash` takes as an argument the hash for the previous keys, we cannot in general reuse precomputed hashes. However, this is possible for the first grouping key since the previous hash is always zero in that case. Since the number of keys is generally small, it makes a large difference to improve performance for this case.
This makes `groupby` twice faster on a simple benchmark with `CategoricalString`. Of course the difference is much smaller with `CategoricalValue{Int}`.
```julia
using DataFrames, BenchmarkTools
v = categorical(["AZERT", "AERDD", "DGGI", "RRFKLK", "4FGFD"][rand(1:5, 10_000)])
df = DataFrame(rand(10_000, 10))
df.key = v
julia> @btime groupby(df, :key);
316.541 μs (49 allocations: 365.33 KiB)
julia> @btime groupby(df, :key);
153.849 μs (51 allocations: 365.47 KiB) …
```
> Use faster hashing approach for first CategoricalVector grouping key

- .travis.yml
- docs/Project.toml
- docs/make.jl
This will ensure doctests do not regress (once they pass and we enable them).
See https://discourse.julialang.org/t/psa-use-a-project-for-building-your-docs/14974.
> Use project to build Documenter docs

- docs/make.jl
- docs/src/lib/functions.md
- docs/src/lib/types.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/groupeddataframe/grouping.jl
- src/subdataframe/subdataframe.jl
Fixes:
* generation of doc page of indexing that was missing;
* hopefully makes http://juliadata.github.io/DataFrames.jl/latest/lib/types.html#Types-1 correctly contain documentation of types (not only their names)
> Cleanup of documentation code

- docs/src/lib/functions.md
- docs/src/lib/types.md
- src/abstractdataframe/iteration.jl
- test/iteration.jl
Improves documentation of `eachrow` and `eachcol`.
Additionally specifies `eltype` of `DFColumnIterator` to be `Tuple{Symbol, AbstractVector}`.
> document eachrow and eachcol

- src/deprecated.jl
This breaks DataFramesMeta piping framework. The one-flavored versions could be migrated to DataFramesMeta.
Fixes https://github.com/JuliaData/DataFramesMeta.jl/issues/116
> Respecting |>

- REQUIRE
- src/other/tables.jl
- test/runtests.jl
- test/tabletraits.jl
I've had something like this lingering around in branches for a very long time, but now finally finished it upstream.
With this PR, the current performance overhead that [CSVFiles.j](https://github.com/queryverse/CSVFiles.jl) has over a raw [TextParse.jl](https://github.com/JuliaComputing/TextParse.jl) disappears entirely. So in the benchmarks shown [here](https://discourse.julialang.org/t/textparse-jl-is-fast-again/16664/10), [CSVFiles.j](https://github.com/queryverse/CSVFiles.jl) gets the same (excellent) performance that one can see in raw [TextParse.jl](https://github.com/JuliaComputing/TextParse.jl) if used with ``DataFrame``.
We have a whole bunch of other plans for the [Queryverse.jl](https://github.com/queryverse/Queryverse.jl) that will lead to more and more sources that will …
> Add support for another TableTraits.jl interface

- src/abstractdataframe/abstractdataframe.jl
- src/deprecated.jl
- test/dataframe.jl
This definition goes against the view of data frames as collections of rows.
Fixes #1200. Part of https://github.com/JuliaData/DataFrames.jl/issues/1514.
(Coverage drop seems to be spurious, since the `axes` method is called by the one above, which is covered.)
> Deprecate length(df::AbstractDataFrame) in favor of size(df, 2)

- src/abstractdataframe/abstractdataframe.jl
- src/dataframerow/utils.jl
- src/groupeddataframe/grouping.jl
- src/groupeddataframe/show.jl
- test/dataframerow.jl
- test/grouping.jl
When grouping on a single `CategoricalArray` column, we don't need a `Dict` to get group codes.
This approach cannot be used when joining, as the `Dict` is needed.
`group_rows` now handles the sorting, which allows skipping this step if the grouping is guaranteed to be sorted (as is the case for `CategoricalArray`).
This mechanism can be extended in the future to handle multiple `CategoricalArray` keys, or integer keys (using radix sort).
This makes grouping about 4 times faster on simple benchmarks, even with the optimized code from https://github.com/JuliaData/DataFrames.jl/pull/1565 (which BTW is still used when grouping on several `CategoricalArray` keys). Of course grouping only represents a small part of the time taken by a split-apply-combine operation, so typically the win isn't …
> Add fast grouping method for CategoricalArray keys

- docs/src/man/getting_started.md
Also add a few missing backticks.
Fixes #1605.
> Fix CSV.write example

- docs/src/man/split_apply_combine.md
- src/deprecated.jl
- src/groupeddataframe/grouping.jl
- test/grouping.jl
This is inspired by the [JuliaDB API](http://juliadb.org/latest/api/aggregation.html#IndexedTables.groupby). When columns are specified via `select`, the user-provided function is passed column vectors (as `SubArray`s) rather than a `SubDataFrame`. This gives fully type-stable code and dramatically improves performance.
This relatively limited change allows taking full advantage of the recent refactoring (https://github.com/JuliaData/DataFrames.jl/pull/1520). The performance gain is really incredible: about 200× for a simple sum after compilation.
```julia
using DataFrames, BenchmarkTools
df = DataFrame(a = repeat(1:40000, outer=[20]),
b = randn(800000))
gd = groupby(df, :a)
julia> @time combine(d -> sum(d.b), gd);
4.657727 seconds (7.39 M allocations: 640.692 MiB, 2.92% gc time)
julia> …
```
> Support type-stable map and combine on GroupedDataFrame

- src/DataFrames.jl
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/show.jl
@nalimilan This is a pretty urgent PR to merge and tag a minor release. It avoids pringing deprecation warning on eachcol when using `dump` or showing a data frame (which calls `getmaxwidths`).
> avoid depwarn in eachcol

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/iteration.jl
- src/deprecated.jl
Avoid depwarn messages when using `SubDataFrame`
> add proper fallbacks for dump, getmaxwidths and mapcols to avoid depwarns

- src/abstractdataframe/abstractdataframe.jl
Currently `describe` calculates the standard deviation of all columns, even if you don't ask it to. 
This PR adds `if` statements around all the function calls so that it only calculates the values it needs to for reporting the descriptive statistics the user asks for. 
However the PR in its current form adds a lot of if statements, which may end up being costly. I doubt it, but will benchmark tomorrow.
> Add `if`s everywhere in describe

- REQUIRE
- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/subdataframe/subdataframe.jl
- test/data.jl
- test/dataframe.jl
- test/subdataframe.jl
I opened a new PR instead of #1618 as there were too many changes and this way is cleaner.
What it changes:
* add `disallowmissing` kwarg for `dropmissing` and `dropmissing!`
* add documentation for `deletecols!` and `deleterows!`
* `deleterows!` manipulates columns "in-place" (I did not do not in-place modification as it can be achieved by `getindex` so it would duplicate)
* `deleterows!` for `SubDataFrame` has a nicer error as it could be accidentally called
> improve dropmissing and deleterows!

- src/abstractdataframe/reshape.jl
- test/data.jl
This deprecation was here for some time already and it changes the behavior (i.e. it is not e.g. a removal of function but change how the function works so I think it is better to clean it up).
> finish deprecation of unstack

- src/dataframe/dataframe.jl
- src/other/index.jl
- test/dataframe.jl
A small PR that is a pre `setindex!` review clean up. It makes sure that we do not allow `Bool` for column indexing and cleans up method signatures (the signature changes are not breaking).
Disallowing `Bool` is a bit breaking, but I would merge it without deprecation as this is what we have warned against in `getindex` and it is disallowed in Base.
> Sanitize haskey and column inserting against Bool column index

- src/abstractdataframe/io.jl
- test/io.jl
This PR adds the option to not print the number of rows and columns in HTML and LaTeX output. This is useful in custom DataFrame types that have their own headers.
> Add summary option to HTML and LaTeX show methods

- src/abstractdataframe/abstractdataframe.jl
- src/dataframerow/dataframerow.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/subdataframe.jl
In this PR:
* add `parent` to `AbstractDataFrame` as identity (similarly to `parent` for arrays that are not views)
* add `parentindices` to `AbstractDataFrame`, `SubDataFrame` and `DataFrameRow` - this is a standard function and we can avoid users calling `DataFrames.row` or `DataFrames.rows`; see e.g. https://discourse.julialang.org/t/dataframerow-row-number/18692
* remove docstrings for `parent` as I think they are not needed (it is clear that `SubDataFrame` and `DataFrameRow` are views)
> Add parentindices and parent

- src/dataframerow/dataframerow.jl
- src/deprecated.jl
- test/dataframerow.jl
I propose to deprecate `convert(Array, ::DataFrameRow)` as it is easy enough to get this functionality with other means and it is not consistent with anything I am aware of since we treat `DataFrameRow` as 1-dimensional object.
> deprecate convert(Array, ::DataFrameRow)

- src/abstractdataframe/abstractdataframe.jl
- src/deprecated.jl
- test/conversions.jl
1. Make conversion to Matrix use `typejoin` not `propote_type`
2. Remove internal function `promote_col_type` that is not used anywhere (@nalimilan - do you know its use?)
3. Deprecate `convert(Arraty, ::AbstractDataFrame)` as I do not understand its value.
> better AbstractDataFrame conversion

- src/dataframerow/dataframerow.jl
- src/deprecated.jl
- test/dataframerow.jl
Clean-up of `DataFrameRow` API.
Notice that `collect(dfr)` will have `eltype` set to `Any` (this is the standard mechanics), while `Vector(dfr)` does `promote_type` (and possibly makes a conversion - this is a behavior inherited from eralier implementation of `convert` to `Array` for `DataFrame`).
> DataFrameRow: fix iterate, ndims, iterate

- src/dataframe/dataframe.jl
- test/dataframe.jl
Fixes a bug when indexing `deletecols!` with a range caused StackOverflow.
> correctly handle ranges in deletecols!

- docs/src/man/joins.md
This avoids a conflict with the function with the same name.
Fixes #1654.
> Avoid calling objet 'names'

- src/subdataframe/subdataframe.jl
- test/subdataframe.jl
Replaces the need for #840.
I did not implement `promote_rule` as I do not see why `Base.promote_rule(::Type{DataFrame}, ::Type{SubDataFrame}) = AbstractDataFrame` is needed. Can someone please explain?
Promotion refers to converting values of mixed types to a single common type. and `SubDataFrame` is already `AbstractDataFrame` which is an abstract type anyway.
> Conversion of SubDataFrame to a DataFrame

- docs/src/man/missing.md
Add description of dropmissing in missing.md docs. The function is already described in the API but it seems useful to mention it in the missing handling part as it should most of the time be more useful that skipmissing to keep alignment between column vectors.
> Add dropmissing mention in missing.md docs

- src/dataframerow/utils.jl
- src/groupeddataframe/grouping.jl
- test/grouping.jl
```julia
df = DataFrame(a = repeat(1:40000, outer=[20]),
b = repeat(20000:-1:1, outer=[40]),
c = randn(800000))
gd = groupby(df, :a)
using BenchmarkTools, Statistics
julia> @btime combine(gd, :c => sum);
10.473 ms (439181 allocations: 17.39 MiB)
julia> @btime combine(gd, :c => sum, :b => mean);
19.515 ms (719227 allocations: 26.24 MiB)
julia> @btime combine(gd, :c => sum);
1.578 ms (154 allocations: 946.95 KiB)
julia> @btime combine(gd, :c => sum, :b => mean);
3.046 ms (186 allocations: 1.54 MiB)
```
> Add optimized methods to compute grouped reductions

- src/dataframerow/utils.jl
- test/grouping.jl
The compiler is still able to generate efficient code specialized on the number of keys. Also require `groups !== nothing` for this method since we never call it without groups and it cannot compute the actual number of nonempty groups without doing all the work anyway.
```julia
using DataFrames, BenchmarkTools
df1 = DataFrame(key1=categorical(string.(rand(1:10, 500_000))),
key2=categorical(string.(rand(1:10, 500_000))));
df2 = DataFrame(key1=categorical(string.(rand(1:1000, 500_000))),
key2=categorical(string.(rand(1:1000, 500_000))));
julia> @btime groupby(df1, :key1);
2.807 ms (66 allocations: 7.63 MiB)
julia> @btime groupby(df2, :key1);
4.727 ms (68 allocations: 7.66 MiB)
julia> @btime groupby(df1, [:key1, :key2]);
21.069 ms (499949 allocations: 23.08 MiB)
julia> @btime groupby(df2, …
```
> Generalize optimized categorical grouping method to multiple keys

- docs/src/man/missing.md
The URL to the stable version of Julia manual website, https://docs.julialang.org/en/stable/manual/, is not generated any more. Instead, use the new URL, https://docs.julialang.org/en/v1/manual/.
Discussed at JuliaLang/julia#30524
> Update URL to the stable version of Julia manual

- src/groupeddataframe/grouping.jl
- test/grouping.jl
Column indices referred to the original data frame but did not necessarily point to the right column in the new parent. Add tests to cover this situation and more.
(Hide whitespace changes to review.)
> Fix grouping column after map on GroupedDataFrame

- src/abstractdataframe/io.jl
- src/groupeddataframe/show.jl
- test/grouping.jl
Use `repr` to show grouping column values and improve escaping in HTML and LaTeX output.
> improve show of GroupedDataFrame

- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- test/dataframe.jl
- test/dataframerow.jl
Changes in this PR:
* add `push!` for `DataFrameRow`
* add `DataFrame` constructor for `DataFrameRow` (it is inconsistent with `NamedTuple`, but we cannot guarantee consistency here anyway so it does not hurt to allow it)
* finish deprecation period for `push!` with string keys; now we do not allow it
* small performance improvements in column lookup
This replaces https://github.com/JuliaData/DataFrames.jl/pull/1439 and fixes https://github.com/JuliaData/DataFrames.jl/issues/1675.
> Improve push! and DataFrame for DataFrameRow

- docs/src/lib/functions.md
- src/dataframe/dataframe.jl
Users coming from other languages (notably Stata) often find `append!` before `vcat`, yet it is rarely what they need. Also add docstrings for vcat and hcat to the manual.
> Add docstring for append!

- src/other/tables.jl
The `DataFrame` constructor needs to convert the array to `Vector{AbstractVector}`.
> Avoid a copy in fromcolumns()

- src/groupeddataframe/grouping.jl
- test/grouping.jl
A small fix as now `groupby` fails when you pass range as columns specification (e.g. `groupby(df, 1:2)` throws an error).
> Improve groupby

- src/dataframerow/dataframerow.jl
- src/deprecated.jl
- test/dataframerow.jl
This fixes https://github.com/JuliaData/DataFrames.jl/issues/1696.
Additionally I have cleaned up some related line length issues in the code
and reorganized test code, because it was hard to reason about.
> Undeprecate DataFrameRow constructor, fix line length, reorganize tests

- REQUIRE
- src/DataFrames.jl
- src/dataframerow/utils.jl
- test/grouping.jl
The PR currently adds a dependency on PooledArrays. I'm not sure what's the best approach. We could define a custom method behind `@require PooledArrays` to avoid the dependency (calling a separate function to avoid duplicating the code). But I figured we may want to add a `pool!` function to parallel `categorical!`, in which case we would have to take the dependency anyway. Though we can defer this issue for later, and use `@require` until then.
Most of the work was to adapt tests to make them more generic. I've added a helper for that. Note that it is better to ignore whitespace to see what actually changed.
Obligatory benchmark:
```julia
using DataFrames, BenchmarkTools, PooledArrays
df1 = DataFrame(key1=categorical(string.(rand(1:10, 500_000))),
key2=categorical(string.(rand(1:10, …
```
> Use optimized grouping method for PooledArrays

- src/dataframerow/show.jl
- test/dataframerow.jl
- test/show.jl
Spotted at https://discourse.julialang.org/t/how-to-show-all-columns-with-dataframerow/20883.
> Fix two-argument show for DataFrameRow

- src/dataframe/dataframe.jl
- src/other/tables.jl
- test/constructors.jl
- test/tables.jl
- test/tabletraits.jl
Following https://github.com/JuliaData/DataFrames.jl/issues/1599 I have added 3 new constructors (allowing a Tuple for columns and for names - for completeness).
> Add DataFrame constructors allowing NTuple and collection of Pair-s

- src/abstractdataframe/show.jl
`Base.nonmissingtype` has bugs in some corner cases. `Missings.T` uses `typesubtract` instead. See also https://github.com/JuliaLang/julia/pull/31016.
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1728. I don't think it's worth adding a test as `Missings.T` is covered elsewhere, and there's no end in testing printing on corner cases like this.
> Use Missings.T instead of Base.nonmissingtype

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
https://github.com/JuliaLang/julia/issues/21672
makes this the preferred phrasing for `vcat`ing collections of matrixes.
it is nice for it to be the same for dataframes.
this very thinly wraps the existing `_vcat`, see the timing.
```
julia> using BenchmarkTools
julia> dataframes = [DataFrame(;A=1:100, B=rand(100), C=fill(i,100)) for i in 1:50];
julia> @btime vcat($(dataframes)...);
37.223 μs (422 allocations: 138.52 KiB)
julia> @btime reduce(vcat, $(dataframes));
595.878 μs (4904 allocations: 3.21 MiB)
julia> @btime DataFrames._vcat($(dataframes));
36.184 μs (420 allocations: 137.59 KiB)
julia> dataframes = [DataFrame(;A=1:100, B=rand(100), C=fill(i,100)) for i in 1:500];
julia> @btime vcat($(dataframes)...);
306.130 μs (3572 allocations: 1.31 MiB)
julia> @btime …
```
> Add optimized reduce(vcat, dataframes)

- docs/src/man/categorical.md
- src/dataframe/dataframe.jl
- test/dataframe.jl
I have made `categorical!` add compression by default. Under the hood `categorical!` calls `CategoricalArrays.categorical`, which selects the smallest `Unsigned` type to represent the pool of categorical elements.
```julia
julia> df = DataFrame(a = 1:typemax(UInt8));
julia> categorical!(df, :a);
julia> eltypes(df)
1-element Array{DataType,1}:
CategoricalValue{Int64,UInt8}
julia> df = DataFrame(a = 1:typemax(UInt8)+1);
julia> categorical!(df, :a);
julia> eltypes(df)
1-element Array{DataType,1}:
CategoricalValue{Int64,UInt16}
julia> df = DataFrame(a = 1:typemax(UInt16)+1);
julia> categorical!(df, :a);
julia> eltypes(df)
1-element Array{DataType,1}:
CategoricalValue{Int64,UInt32}
```
I also updated the categorical docs and tests.
Closes #1733
> Add compress argument to categorical!()

- src/dataframe/dataframe.jl
- src/other/index.jl
It does not appear to be needed and other packages generally don't define it.
> Remove deepcopy

- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- src/subdataframe/subdataframe.jl
Clean up and enable `nrow` and `ncol` documentation.
My current understanding is that in the end we tend to want to keep them in 1.0.
> document nrow and ncol

- src/groupeddataframe/grouping.jl
We don't actually need to call these functions since we always have access to the original name of reductions.
This is a more radical fix for #1747.
> Remove unnecessary funname methods

- src/groupeddataframe/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1747 (we should use `nameof` instead of `Symbol` to get **name of** function 😄).
I have also updated docstrings where they were missing outputs.
After this PR is OK and gets merged the next step is to enable checking docstrings by Documenter (a separate PR).
> fix names of functions from Statistics in by and upgrade documentation

- src/dataframe/dataframe.jl
- test/dataframe.jl
This follows the comment from @nalimilan here https://discourse.julialang.org/t/best-way-to-iteratively-add-to-a-dataframe/21084/8.
Changes:
* allow to `append!` a data frame with 0 columns to an existing data frame (and this is a no-op)
* allow to `append!` to a `DataFrame` with 0 columns; in this case new columns are added (this is an exception) with freshly allocated column data; in this case it is problematic what should be the exact type of `AbstractVector` to create (this is why this change is slightly problematic); I have decided to recommend creating a `Vector` in this case
> Improve append!

- REQUIRE
- src/deprecated.jl
This avoids requiring admin privileges on Windows. Without these, `readtable` no longer supports .csv.gz files, but it's deprecated.
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1754.
> Remove dependency on CodecZlib and TranscodingStreams

- .travis.yml
This is the recommended code. See https://github.com/JuliaStats/StatsBase.jl/pull/480#discussion_r270540283.
> Call Pkg.develop before Pkg.instantiate when building docs

- docs/src/lib/types.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/iteration.jl
- src/abstractdataframe/join.jl
- src/deprecated.jl
- src/groupeddataframe/grouping.jl
- test/cat.jl
- test/constructors.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/indexing.jl
- test/iteration.jl
- test/join.jl
- test/subdataframe.jl
I had to open a new PR for this (the old one was https://github.com/JuliaData/DataFrames.jl/pull/1613).
It is now rebased to the current master.
> End deprecation period of eachcol

- src/deprecated.jl
Moving towards cleaning up src/deprecated.jl I propose to remove deprecations for methods that have been deprecated for a long time already. With others we probably can wait as they have been changed more recently (and a major thing related to file reading/writing is waiting for CSV.jl rewrite that is going on currently).
> Remove some old deprecated methods

- Project.toml
- src/dataframe/dataframe.jl
- src/groupeddataframe/grouping.jl
- src/other/tables.jl
- test/grouping.jl
- test/tables.jl
This PR fixes the following problem:
```
julia> gd = groupby(DataFrame(rand(3,4)), :x1)
GroupedDataFrame with 3 groups based on key: x1
First Group (1 row): x1 = 0.6359046443565228
│ Row │ x1       │ x2       │ x3       │ x4       │
│     │ Float64  │ Float64  │ Float64  │ Float64  │
├─────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ 0.635905 │ 0.310854 │ 0.695098 │ 0.579583 │
⋮
Last Group (1 row): x1 = 0.0519420235728989
│ Row │ x1       │ x2       │ x3       │ x4       │
│     │ Float64  │ Float64  │ Float64  │ Float64  │
├─────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ 0.051942 │ 0.666328 │ 0.896186 │ 0.775949 │
julia> DataFrame!(gd)
3×4 DataFrame
│ Row │ x1         │ x2         │ x3          │ x4          │
│     │ SubArray…  │ SubArray…  │ SubArray…   │ SubArray… …
```
> Additional fixes of DataFrame constructors

- src/abstractdataframe/abstractdataframe.jl
- test/cat.jl
Changes in this PR:
* make `reduce(vcat, dfs; cols)` behave in the same way as `vcat(dfs...; cols)` (this means: disregard data frames with 0 columns and acccept `cols` keyword argument)
* make `reduce(vcat, dfs; cols)` also accept a tuple of `AbstractDataFrame`s and not only an `AbstractVector` of them
> minor change in vcat implementation

- docs/src/man/getting_started.md
The way to change the way data frames are displayed in Jupyter Notebook is non-obvious so I propose to add the instructions to the manual.
> add instructions for setting up Jupyter Notebook with DataFrames.jl

- src/dataframe/dataframe.jl
- test/dataframe.jl
Fixes #1800.
Additionally fixes a bug under which `0`-length ranges were not converted to a vector. This should be merged before 0.18.2 release.
> fix constructor with zero rows

- src/other/tables.jl
- test/tables.jl
Because we're now calling `if x isa AbstractVector || x isa Tuple`, we don't need the initial `istable` check, so we can simplify things a little here.
> Simplify fallback

- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
- test/subdataframe.jl
This is an abuse of `dump`, which is supposed to always print the internals.
`summary(df)` can be used instead.
> Remove dump method

- src/groupeddataframe/grouping.jl
- src/groupeddataframe/show.jl
- test/grouping.jl
Also fix a bug when the user-provided function returns an empty `DataFrame` with no columns.
> Fix map(f, ::GroupedDataFrame) when there are no groups

- src/other/tables.jl
- test/tables.jl
Fixes #1820.
Any chance that a bug fix release could be tagged soon? The problem that is fixed with this PR and https://github.com/JuliaData/DataFrames.jl/issues/1809 are causing a lot of trouble for our work right now, and it would be good to get a new release out that fixes those two regressions.
> Fix the constructor to no longer mask error messages

- src/dataframerow/dataframerow.jl
- test/dataframerow.jl
This PR implements methods that make `DataFrameRow` behave like `NamedTuple` in standard operations.
This is breaking for:
* `keys` (as we return now a `Tuple` not a `Vector`),
* `pairs` as we return `Pairs` not a `Generator`
* `map` where we return a `NamedTuple` not a `Vector`
* `broadcastable` where we disallow `DataFrameRow` on RHS (in preparation for a future functionality to match `NamedTuple`)
I will write the tests after we decide:
* if we want it (or part of it)
* in case we want it do we go through a deprecation period or simply change it (these are small changes, the only code that would be broken is code that expects a vector and consequently mutates it, and now it will get a `Tuple` or `NamedTuple`)
> Make DataFrameRow behave more like NamedTuple

- src/abstractdataframe/io.jl
- src/abstractdataframe/show.jl
- test/io.jl
- test/show.jl
Currently trying to display `DataFrameRow` with zero columns throws an error.
This PR fixes this and adds some extra tests for zero columns data frames.
> Fix display of DataFrameRow with zero columns

- src/dataframe/dataframe.jl
This fixes a problem with printing `push!` error message when `t` is `nothing`.
> fix push! error message

- src/dataframe/dataframe.jl
- test/dataframe.jl
A small change how `categorical!` without specified columns works. I recommend to allow automatic conversion of columns with eltype `Union{AbstractString,Missing}` (and not only `AbstractString` as currently).
> make categorical! accept missing values when converting

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/join.jl
- src/dataframe/dataframe.jl
- src/deprecated.jl
- test/dataframe.jl
I propose to deprecate `get` method for `AbstractDataFrame`. I think it is not used and in general it is confusing to have it since we moved from `AbstractDict` interpretation.
> Deprecate get for AbstractDataFrame

- src/dataframe/dataframe.jl
Computing the integer indices before indexing into the vectors is faster: since the array indexing code does that anyway, doing it manually avoids repeating the operation for each column.
```julia
using DataFrames, BenchmarkTools
df = DataFrame(rand(10_000, 100));
inds = rand(Bool, nrow(df));
@btime df[inds, :];
@btime df[inds, 1:10];
@btime df[inds, 1:2];
@btime df[inds, [1]];
julia> @btime df[inds, :];
4.039 ms (517 allocations: 3.85 MiB)
julia> @btime df[inds, 1:10];
397.159 μs (76 allocations: 395.48 KiB)
julia> @btime df[inds, 1:2];
79.435 μs (36 allocations: 80.55 KiB)
julia> @btime df[inds, [1]];
40.242 μs (34 allocations: 41.34 KiB)
julia> @btime df[inds, :];
1.372 ms (419 allocations: 3.87 MiB)
julia> @btime df[inds, 1:10];
135.309 μs (68 allocations: 433.06 KiB)
julia> @btime …
```
> Speed up getindex with AbstractVector{Bool} row selection

- src/dataframe/dataframe.jl
- src/deprecated.jl
- test/dataframe.jl
- test/deprecated.jl
So that we can change it to be equivalent to `empty!.(eachcol(df))`.
Fix #1841.
> Deprecate empty!

- test/conversions.jl
Loading `InteractiveUtils` is not needed and it causes tests to fail on nightly
> remove InteractiveUtils load

- src/deprecated.jl
A small fix needed due to problem described in https://discourse.julialang.org/t/subsetting-uninitialized-arrays/25449.
> fix deprecation warning for DataFrame constructor

- src/DataFrames.jl
- src/abstractdataframe/join.jl
- src/deprecated.jl
I have forgotten to clean-up some code after `deletecols!` removal.
I also propose to remove old `insert!`, `delete!` and `merge!` deprecations.
> clean up after deletecols! removal

- src/groupeddataframe/grouping.jl
- test/grouping.jl
`gix == 0` for missing values when skipmissing=true, but the code was not designed to handle this. Due to `@inbounds`, it is likely to go unnoticed.
I've checked using benchmark at https://github.com/JuliaData/DataFrames.jl/pull/1651 that this doesn't affect performance (since unfortunately SIMD isn't enabled anyway in this loop).
> Fix combine with aggregation when skipmissing=true

- src/other/broadcasting.jl
I have replaced two obvious cases where it is better to throw DimensionMismatch error rather than a more general ArgumentError. Not sure how to test this feature. Appreciate if I can have any help for unit test.
> Throw a more specific exception when dimensions are mismatched

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/io.jl
- src/abstractdataframe/show.jl
- src/abstractdataframe/sort.jl
- src/dataframerow/dataframerow.jl
- src/deprecated.jl
- test/conversions.jl
Make sure to limit error-throwing code lines within the width of 95 characters.
> Reformat long error-throwing code lines

- docs/Project.toml
- docs/make.jl
- docs/src/index.md
- docs/src/lib/functions.md
Fixes #1891
The original reason for this PR is #1891. The problem I have is that locally the documentation of the functions mentioned there is generated correctly, but it is broken on GitHub for some strange reason.
So I have started to look at documentation generation mechanics and fixed some deprecations. Currently when I build documentation locally I get the following output (sorry that it is long, but maybe something important is lurking there). I will ask the questions I have below the output.
```
julia> include("make.jl")
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: skipped.
[ Info: ExpandTemplates: expanding markdown templates.
┌ Warning: duplicate docs found for 'DataFrame' in `@docs` block in src\lib\types.md:112-122
│ ```@docs
│ AbstractDataFrame
│ …
> Improve documentation generation

- src/abstractdataframe/io.jl
- src/abstractdataframe/join.jl
- src/abstractdataframe/show.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/groupeddataframe/grouping.jl
- test/dataframe.jl
- test/grouping.jl
- test/io.jl
- test/join.jl
- test/show.jl
This fixes https://github.com/JuliaData/DataFrames.jl/issues/1885 and https://github.com/JuliaData/DataFrames.jl/issues/1845.
What it does:
* sanitizes `push!` and `append!`, as I concluded that it is best to do more strict checks there (as we do dynamic dispatch there anyway)
* adds consistency checks to `join`, `groupby` and `_show`
(this also lead to a bit different approach to error throwing)
Consistency check for 10000 column costs ~200 microseconds so I think it is acceptable. But please comment on this.
Also please comment where else you think it is worth to add consistency checks.
> First proposal of consistency checks

- Project.toml
- docs/src/lib/indexing.md
- src/other/broadcasting.jl
- test/broadcasting.jl
Fix #1889
@grahamgill - in tests you can see what will be allowed and what will be still disallowed.
> allow scalar broadcasting into an empty data frame

- src/dataframe/dataframe.jl
Fixes a problem with error message generation:
Current:
```
julia> df = DataFrame()
0×0 DataFrame
julia> df.a = df.b = [1]
1-element Array{Int64,1}:
1
julia> append!(df, df)
┌ Error: Exception while generating log record in module DataFrames at C:\Users\bogum\.julia\dev\DataFrames\src\dataframe\dataframe.jl:1138
│   exception =
│    UndefVarError: df not defined
│    Stacktrace:
│     [1] macro expansion at .\logging.jl:319 [inlined]
│     [2] append!(::DataFrame, ::DataFrame)
│     [3] top-level scope at none:0
│     [4] eval(::Module, ::Any) at .\boot.jl:328
│     [5] eval_user_input(::Any, ::REPL.REPLBackend) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\REPL\src\REPL.jl:85
│     [6] macro expansion at …
```
> fix a typo in append!

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Fixes #1765.
Actually I think that it is better to print true `eltype` not a stripped one. It is a bit more verbose, but is explicit and in this case it is not a problem (someone wants `eltype` in `describe` so one gets it verbatim).
> Change eltype to true eltype in describe

- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/dataframe.jl
Fixes #1720
To make things consistent I add `disallowmissing`, `allowmissing` and `categorical` support.
I also fix a bug in `categorical!` which incorrectly handled `:` passed as column selector.
> add disallowmissing, allowmissing and categorical; fix a bug in categorical!

- src/groupeddataframe/grouping.jl
- test/grouping.jl
I do not do deprecation period, as the old behavior was unintended.
> disallow GroupedDataFrame broadcasting

- Project.toml
- docs/src/lib/indexing.md
- src/DataFrames.jl
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/other/index.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
- test/index.jl
Adds `Between` and `All` column indexing
> Add Between and All

- .travis.yml
The old path-getting syntax is currently deprecated
> Update deprecated Travis build commands

- Project.toml
- src/deprecated.jl
- test/deprecated.jl
This fixes https://discourse.julialang.org/t/overwrite-partial-dataframe-row-with-new-array/27953.
@nalimilan After this is merged we should tag a release. Ideally I would also merge https://github.com/JuliaData/DataFrames.jl/pull/1925 and https://github.com/JuliaData/DataFrames.jl/pull/1899 if they could be ready relatively soon (I have time to work on it) and then tag 0.20.0 release (this is my preferred option if you have time to have a look, especially at #1899 which is large). Otherwise we should just pick this PR over 0.19.3 and tag 0.19.4 with only this fix.
> fix deprecation for setindex! using 1-row DataFrame

- test/broadcasting.jl
- test/cat.jl
- test/constructors.jl
- test/index.jl
- test/tables.jl
What I have changed:
* added tests for `DataFrame` constructors from `eachrow` and `eachcol` as they were missing
* removed `"error"` word from testset names, so that they do not produce false positives when parsing log files.
> Cleanup tests

- src/groupeddataframe/grouping.jl
- test/grouping.jl
Instead, check whether columns with the same names as grouping keys have been returned, and throw an error if they are not equal.
This is breaking since columns named key_1, etc. won't be created, but in practice it should not be frequently used. Introducing a deprecation would be more annoying than helpful since it would require adding a keyword argument to disable adding grouping keys and force users to set it to silence
the warning, which happens in most common cases.
Fixes #1460.
> Stop using makeunique=true for grouping keys in combine

- docs/src/man/reshaping_and_pivoting.md
This occurrence had been missed in a previous fix apparently.
> Fix path to iris.csv

- src/groupeddataframe/grouping.jl
- test/grouping.jl
This change makes `by` and `groupby` consistent.
It is marginally breaking as someone in `by` could have wanted to create column named `skipmissing` (a similar problem we now have with `sort`), but I think it is OK to go with it without deprecation period.
> add skipmissing to by

- src/dataframe/dataframe.jl
- test/dataframe.jl
Also changed the unit test to check ArgumentError, not ErrorException.
#1867
> Throw more specific error, ArgumentError, rather than a general Error()

- src/dataframe/dataframe.jl
- test/dataframe.jl
This is a deprecation PR for now.
Note that we still allow `AbstractArray`s (not only `AbstractVector`s) as this is what base allows:
```
julia> x = ones(2,2)
2×2 Array{Float64,2}:
1.0  1.0
1.0  1.0
julia> x[:, 1] = zeros(1,1,1,2)
1×1×1×2 Array{Float64,4}:
[:, :, 1, 1] =
0.0
[:, :, 1, 2] =
0.0
julia> x
2×2 Array{Float64,2}:
0.0  1.0
0.0  1.0
```
> Make push! more strict

- docs/src/man/getting_started.md
- docs/src/man/reshaping_and_pivoting.md
- docs/src/man/sorting.md
- docs/src/man/split_apply_combine.md
> fix documentation examples

- docs/src/lib/indexing.md
- src/dataframe/dataframe.jl
- test/indexing.jl
To make it consistent with `push!`
> disallow Base.Generator in setindex! to DataFrameRow

- test/data.jl
this is a minor PR cleaning up outstanding tests in test/data.jl that were not wrapped in `@testset`.
> wrap outstanding tests in data.jl in testset

- src/dataframerow/utils.jl
- test/grouping.jl
Original code was correct but JuliaData/DataTables.jl#79 incorrectly moved `break` outside of the `if`.
Fixes #1978.
> Fix handling of hash collisions in row_group_slots

- src/abstractdataframe/join.jl
- test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1962
> allow joins for more than two data frames

- src/DataFrames.jl
- src/dataframe/dataframe.jl
- src/other/index.jl
As discussed in Issue #1861 . This will significantly improve performance for the `select!` function(over 1000x for 100,000 columns).
Passes the tests locally and I couldn't find any bugs upon testing.
> Rewrite `select!` to improve performance

- src/groupeddataframe/grouping.jl
- test/data.jl
- test/grouping.jl
Allow more flexible `cols` in `groupby` and `by` (e.g. `Regex`, `Not`, `All`).
In particular also correctly handle the case when cols produces an empty selection of columns. In this case we create a single group having all columns.
> allow more flexible cols in groupby and in particular handle empty cols

- src/dataframe/dataframe.jl
- test/dataframe.jl
`lookup` of `Index` was not cleaned by `select!` before reassignment. This PR fixes this.
> fix a bug in select!

- docs/src/index.md
I think that the website [https://github.com/bkamins/Julia-DataFrames-Tutorial/](https://github.com/bkamins/Julia-DataFrames-Tutorial/) is a very useful resource, and it could be good to mention it in the documentation.
> Add reference to DataFrames Tutorial in index.md

- docs/src/man/getting_started.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1999
> Documenting the difference betwen df[!, :col] and df[:, :col]

- src/dataframe/dataframe.jl
- src/other/tables.jl
- test/tables.jl
Additionally I have cleaned a minor bug in the documentation of `DataFrame` constructor.
See https://github.com/JuliaData/DataFrames.jl/pull/2003#issuecomment-550217542 for a rationale of this change.
> change how copycols in Vector{<:NamedTuple} constructor

- src/abstractdataframe/reshape.jl
```julia
using DataFrames
a = DataFrame( i=["a","a","b","b"], j=["a1","a1","b1","b1"],
var1=[1,2,3,3], val=[11,22,33,44])
unstack(a,:i,:var1,:val)
#┌ Warning: Duplicate entries in unstack at row 4 for key b and variable 3.
unstack(a,[:i,:j],:var1,:val)
#┌ Warning: Duplicate entries in unstack at row 4 for key ("a", "a1") and variable 3.
unstack(a,[:i,:j],:var1,:val)
#┌ Warning: Duplicate entries in unstack at row 4 for key ("b", "b1") and variable 3.
```
> Key in warning doesn't reflect the the right entry

- src/other/index.jl
- test/cat.jl
- test/dataframerow.jl
- test/index.jl
- test/indexing.jl
- test/subdataframe.jl
see the discussion in https://github.com/JuliaData/DataFrames.jl/pull/1958.
Rationale for this change:
* the case when the cost of creation of `DataFrameRow` or `SubDataFrame` will be affected is only when indexing by `AbstractVector{Int}` is performed (abut not ranges - as they will be fast) - so I guess the case when it is needed is pretty rare
* if someone really wants to avoid checking for duplicates it is possible to call `SubIndex` default constructor with appropriate values
* the additional benefit is that functions that previously called `lazyremap!` have a bit less work to do later
> make SubIndex strict about duplicates

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Fixes #2014
I have also tried to improve docs a bit.
> add cols to describe

- src/dataframe/dataframe.jl
> remove unnecessary line in DataFrame constructor

- docs/src/lib/indexing.md
- src/dataframe/dataframe.jl
- src/other/broadcasting.jl
- test/broadcasting.jl
- test/indexing.jl
Allow `df[:, col] = vector` and `df[:, col] .= v` to create a column if `col` is not present in `df`. A fresh vector is always allocated.
Given the comments on Slack I am convinced we can add this without harm, but there is no rush (though personally I would prefer to settle this PR before 1.0, as I would prefer not to mess with `getindex`/`setindex!`/broadcasting assignment after 1.0 if possible).
CC @oxinabox @nalimilan @pdeffebach
> allow to create columns using : as row selector

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
allow integer as `from` value in `rename` and `rename!`. Also clean up the docstrings.
> allow integer as from value in rename

- Project.toml
- docs/src/lib/functions.md
PRs required to be merged before 0.20 release:
PRs that I would like merge before 0.20 release (but they are pending consensus or final changes, hopefully this can be resolved soon - if there are problems with them they will not get included):
Nice to have PRs (should be easy so possibly they can be included in the release, but they are non blocking):
- ~https://github.com/JuliaData/DataFrames.jl/pull/1864~ (excluded from the release)
> Release 0.20.0

- src/other/tables.jl
- test/tables.jl
This PR adds Tables.jl interface for `DataFrameRows` and `DataFrameColumns`.  It is useful for defining data manipulation functions expecting iterators.  Example:
```julia
julia> tablemap(f, xs) = Tables.materializer(xs)(map(f, xs))
tablemap (generic function with 1 method)
julia> tablemap(x -> (A=x.a, B=x.b), eachrow(DataFrame(a=[3], b=[4])))
1×2 DataFrame
│ Row │ A     │ B     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 3     │ 4     │
```
> Add Tables.jl interface for DataFrame(Rows|Columns)

- src/other/tables.jl
- test/tables.jl
This PR reverts last two commits in #2055 so that
```julia
materializer(::Union{DataFrameRows,DataFrameColumns}) = DataFrame
```
Ref: https://github.com/JuliaData/DataFrames.jl/pull/2055#issuecomment-566421559
> Materialize DataFrame(Rows|Columns) as DataFrame

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/iteration.jl
- src/dataframerow/dataframerow.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/iteration.jl
- test/subdataframe.jl
Following https://github.com/JuliaData/DataFrames.jl/pull/2055#issuecomment-566225609. Actually it seems that only `names` was missing for `eachcol` and `eachrow` return values.
> Add names to data frame iterators

- src/abstractdataframe/reshape.jl
- test/reshape.jl
Fixes #1947
I have left an option for the column to contain `Symbol`s (via a keyword argument), as it simplified the deprecation period and maybe some old code uses this.
After the deprecation the only thing to change is the default value of the kwarg (if we decide to use the design I have proposed).
> Allow stack to make column variable contain a categorical vector of strings

- src/other/tables.jl
- test/tables.jl
Instead of converting to a NamedTuple of Vectors (via `columntable`). The conversion to
NamedTuple is problematic in the case of extremely wide DataFrames, and
as such is the root cause of
https://github.com/JuliaData/CSV.jl/issues/538.
The reason NamedTuple was used in the first place, however, was due to a
desire in certain querying contexts to be able to get a type-stable
row-iterator (cc: @davidanthoff ).
While this change generally follows the DataFrames.jl approach to
avoiding extreme compiler pressure, it does incur just over 2x
performance penalty on a simple manipulation like:
```julia
df |> @map({x=_.id + 1, y=_.salary * 2.0}) |> DataFrame
```
Perhaps it's easy enough for users who need that extra speed to just do
`columntable(df)` first before manipulating and when they know …
> Change Tables.rows implementation to use eachrow

- src/abstractdataframe/reshape.jl
- src/dataframerow/utils.jl
- src/groupeddataframe/grouping.jl
- test/grouping.jl
This can make simple aggregation functions more than twice faster.
Some benchmarking shows no regression from current state even when a custom function (which doesn't benefit from optimization) is used:
```julia
using DataFrames, PooledArrays, BenchmarkTools
n = 100_000;
for k in (10, 10_000)
global df = DataFrame(x=PooledArray(rand(1:k, n)), y=rand(n));
println("groupby with $k groups")
@btime groupby(df, :x);
global gd = groupby(df, :x);
println("sum with $k groups")
@btime by(df, :x, :y => sum);
@btime combine(gd2, :y => sum) setup=(gd2=deepcopy(gd));
println("sum+length with $k groups")
@btime by(df, :x, :y => sum, :y => length);
@btime combine(gd2, :y => sum, :y => length) setup=(gd2=deepcopy(gd));
println("x -> x[1] with $k groups")
@btime by(df, :x, :y => (x -> x[1]));
@btime …
```
> Avoid computing group indices when possible

- src/dataframerow/dataframerow.jl
- test/dataframerow.jl
Fixes #2059.
Notes:
1) I did not add docstrings for these functionalities following the logic that we treat `DataFrameRow` as if it is a `NamedTuple`
2) I skipped defining `merge` for more than 2 passed arguments as this is not supported in 1.0 (it is new in 1.1) and additionally it is problematic (there is no clean way to define `merge` with `Union` approach as it overwrites the original `merge(a::NamedTuple, b::NamedTuple, cs::NamedTuple...)` definition which I think we should avoid); I think thought that in practice this is not needed
3) in tests I check to make sure splatting as kwargs works as expected for `DataFrameRow`
> add conversions and merge for DataFrameRow

- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
When a group only contains missing values, grouped `maximum` and `minimum` have to throw an error like the corresponding functions. Otherwise they incorrectly return `typemin`/`typemax`. Also fix `var` and `std` to return `NaN` in that case instead of `-0.0`.
This problem cannot happen without `skipmissing`, as empty groups are not allowed.
Fixes #2061.
> Fix grouped maximum, minimum, var and std with only missing values

- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes the following problem:
```
julia> df = DataFrame(a=1)
1×1 DataFrame
│ Row │ a     │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │
julia> dfr = DataFrame(x=1, y="1")[1, 2:2]
DataFrameRow
│ Row │ y      │
│     │ String │
├─────┼────────┤
│ 1   │ 1      │
julia> by(sdf -> dfr, df, :a)
ERROR: AssertionError: j === nothing
```
> fix combine with DataFrameRow

- src/abstractdataframe/iteration.jl
- src/abstractdataframe/show.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/other/index.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
- test/io.jl
We were using wrong syntax for `BoundsError` in the whole package (it does not allow a custom message). This PR fixes this.
> Fix BoundsError messages

- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1981
Allow `NamedTuple()`, `DataFrame` and zero columns matrix as return value in `combine` and `map`. They are ignored and drop columns.
Additionally fixes some small issues in tests.
@nalimilan - one potential performance consideration is that now I use `colnames` as `Vector{Symbol}` - do you think it will be problematic?
Also I had to separate `_combine_with_first_row!` and `_combine_with_first!` as separate functions as for some strange reason alternatively in some cases Julia had problems with type inference.
Importantly  - we allow these 0-column containers only for vector-oriented containers. They are disallowed in scalar-oriented containers.
Finally - this PR touches parts of code that I do not know very well, so feel free to …
> Allow containers with no columns in combine

- src/abstractdataframe/abstractdataframe.jl
- src/deprecated.jl
The removed method should not be used. It was needed when we supported single-index indexing.
> remove lastindex without a dimension

- src/abstractdataframe/io.jl
Without this bugfix IOContext specifications (e.g. to which precision to print Float64) will be ignored.
> bugfix: io context no longer ignored

- docs/src/lib/indexing.md
- docs/src/lib/types.md
- src/groupeddataframe/groupeddataframe.jl
- test/grouping.jl
Use array of keys (`GroupKey`/`Tuple`/`NamedTuple`) in `getindex(::GroupedDataFrame, ...)`.
I also fixed a couple of issues remaining in my last PR: a test for `IndexStyle(::GroupKeys)` and added some missing bindings to the documentation.
> Index GroupedDataFrame with array of keys

- src/DataFrames.jl
- test/tables.jl
Fixes #2114.
Given @nalimilan comment I just export Tables.jl.
Also internally I switched to import Tables.jl and DataAPI.jl (not using).
I think it is cleaner if all functionality from these packages is explicitly qualified by package name when used (except we decide to export some names explicitly, as we currently do for: `columnindex`, `All`, `Between` and `describe`)
> export Tables and imoprt DataAPI and Tables internally

- src/abstractdataframe/show.jl
- test/runtests.jl
- test/show.jl
Keeps printing behaviour the same on Julia 1.5-DEV as it currently exists. The change https://github.com/JuliaLang/julia/pull/34387 changes the 2-arg show to display the parser-friendly version.
> Consistent period printing on Julia 1.5-DEV

- docs/src/lib/types.md
- docs/src/man/getting_started.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/io.jl
- src/abstractdataframe/iteration.jl
- src/abstractdataframe/show.jl
- src/deprecated.jl
- test/dataframerow.jl
- test/deprecated.jl
- test/indexing.jl
- test/io.jl
- test/iteration.jl
- test/show.jl
- test/subdataframe.jl
- test/tables.jl
Fixes #2090.
In the next move we will drop V parameter of `DataFrameColumns`.
Making this PR revealed that `names=true` is in practice almost never used (at least internally), so this change - while big - should not be that problematic.
> [BREAKING] deprecate names=true in eachcol

- src/abstractdataframe/abstractdataframe.jl
- test/reshape.jl
This is a feature I wanted for `flatten`, to be able to use it on multiple vector-valued columns at a time. I couldn't quite figure out how to word the error message for when the lengths don't match up between the columns (see the `df3` example I've added to the docstring). I definitely welcome your suggestions on that and anything else!
> Flatten multiple columns at once

- src/groupeddataframe/groupeddataframe.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2095.
I used `Dict{Any, Int}` interface which is fast enough I think. In the future this can be improved as @nalimilan noted, but already we have huge performance gains here and the end-result makes `GroupedDataFrame` practically usable as an indexed `DataFrame`.
> use Dict{Any,Int} to speed up GroupDataFrame lookup

- docs/src/man/getting_started.md
Actually you can change `ENV` entries interactively and they take effect immediately (there is no need to set them before the notebook is started)
> Make the Jupyter Notebook documentation more precise

- src/groupeddataframe/groupeddataframe.jl
- test/grouping.jl
When we defined `keys` for `GroupedDataFrame` and `GroupKey` we have not defined `haskey` for them. I think it is natural to define both.
When we have it defined then actually `GroupedDataFrame` can be used as a dictionary.
A design decision is if we want to define all the methods I proposed, but I think it should be OK.
> add haskey to GroupedDataFrame and GroupKey

- src/abstractdataframe/reshape.jl
- test/reshape.jl
Fixes a wrong definition of `eltype` when `stack` with `view=true` is used. We switch from dynamic to static calculation of eltype (which is needed as Base uses static eltype information for vectors to manipulate them).
Do not merge before #2140 is merged as docs (the manual) need to be updated here which is not done yet.
> [BREAKING] fix eltype in stack with view=true

- src/abstractdataframe/iteration.jl
- test/iteration.jl
Apologies if this has already been proposed before and rejected. I couldn't find it with cursory searching. I semi-frequently see people confused by the `MethodError` stacktrace thrown when trying to iterate over a DataFrame (e.g. https://discourse.julialang.org/t/i-do-not-understand-this-error-methoderror-no-method-matching-iterate-dataframe/34530 although that person has more confusion than just the exception). This PR adds a method for `iterate(::AbstractDataFrame)` which simply throws an error with more explanation of what went wrong.
> Show friendly error when trying to iterate DataFrames

- docs/src/man/categorical.md
- docs/src/man/getting_started.md
- docs/src/man/joins.md
- docs/src/man/missing.md
- docs/src/man/reshaping_and_pivoting.md
- docs/src/man/sorting.md
- docs/src/man/split_apply_combine.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/join.jl
- src/abstractdataframe/show.jl
- src/dataframe/dataframe.jl
- test/io.jl
- test/show.jl
> change ⍰ to ? when showing a DataFrame with missing eltype

- src/abstractdataframe/selection.jl
- test/select.jl
Allow an easy way to get a number of rows in `select`. It was such a clean idea that I could not resist it (but maybe other people will think otherwise).
I think having this as a special case is justified.
When this is merged the full benefit will be in https://github.com/JuliaData/DataFrames.jl/pull/2158, as `nrow` is routinely required in split-apply-combine operations and now we did not have a clean and quick way to do it.
> add nrow to select

- docs/src/lib/functions.md
- docs/src/man/getting_started.md
- src/DataFrames.jl
- src/abstractdataframe/selection.jl
- src/other/index.jl
- test/index.jl
- test/indexing.jl
- test/select.jl
Adds transform and transform! functions.
Additionally small bug fixes in `select` (`Any()` corner case when `copycols=false`) and in making a view of a `SubDataFrame` and some small rearrangements of documentation.
> add transform and transform! and select cleanup

- docs/src/lib/functions.md
- src/DataFrames.jl
- src/deprecated.jl
- src/groupeddataframe/groupeddataframe.jl
- src/groupeddataframe/show.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
`valuevars` function will be a useful complement to `groupvars` function.
If we have it we can actually deprecate `aggregate` already now, as then:
```
aggregate(df, :a, sum)
```
becomes
```
combine(gdf, valuevars(gdf) .=> sum)
```
@nalimilan In particular that adding broadcasting of `All` will not allow to deprecate `aggregate` as `All()` would include grouping columns which are skipped by `aggregate`.
If you think that some other name would be better please comment.
> [BREAKING] add groupcols and valuecols functions

- src/abstractdataframe/selection.jl
- src/dataframe/dataframe.jl
- test/constructors.jl
- test/select.jl
Resolves the `select` part of https://github.com/JuliaData/DataFrames.jl/issues/2162.
I have disallowed "squashing" scalars to 0-rows if vectors have 0-rows. So this is a decision to make what we should do (I disallowed it as later allowing it would be non-breaking).
BTW `DataFrame` and `insertcols!` are currently inconsistent here (`DataFrame` does not allow squashing and `insertcols!` allows it). We should decide what should be the target functionality and make it consistent across these three use cases (and `combine` in the future)
> [BREAKING] allow pseudo-broadcasting in select

- docs/src/man/split_apply_combine.md
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2166
I still need to update the documentation and tests, but all from #2166 is implemented here.
One comment is that we treat `NamedTuple` as-is (i.e. we do not unpack `NamedTuples` when pseudo-broadcasting)
> [BREAKING] add to combine and by: column selection, pseudo broadcasting, fix bug with unequal column lengths

- src/abstractdataframe/abstractdataframe.jl
- src/dataframerow/dataframerow.jl
- src/groupeddataframe/groupeddataframe.jl
- test/data.jl
allow `cols` argument to `names` so that it is easy to use any valid selector in `select` and `combine` when broadcasting.
> add cols to names

- Project.toml
- docs/src/man/categorical.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/reshape.jl
- src/abstractdataframe/show.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/dataframerow/utils.jl
- src/deprecated.jl
- test/broadcasting.jl
- test/dataframe.jl
- test/grouping.jl
- test/reshape.jl
- test/tables.jl
Replace `CategoricalString` with `CategoricalValue{String}` and stop using `CategoricalArrays.index`. This simplifies the code a bit. Also drop some specializations which are equivalent to optimized methods defined in CategoricalArrays.
> Port to CategoricalArrays 0.8

- .travis.yml
Having both `matrix` and `jobs` disables the latter.
> Fix building documentation on Travis

- docs/src/man/categorical.md
Documenter doesn't seem to support this.
> Fix exponent in docs

- docs/src/man/getting_started.md
- src/abstractdataframe/abstractdataframe.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
This is a PR implementing the suggestions of @oxinabox to #2199.
@nalimilan - the major comment was if we want to allow `AbstractVector{<:SymbolOrString}`
in place of `Union{AbstractVector{Symbol}, AbstractVector{<:AbstractString}}` (in technical terms, as in some places in the code this has a different manifestation, but essentially - I was defensive in #2199 and disallowed mixing `Symbol`s and strings, and @oxinabox suggests to allow this).
(as a note - my preference is to disallow mixing - as I do not see a use case where it is really useful)
@oxinabox - note that currently we also disallow mixing integers and `Symbol`s or strings (of course this is not the same, but ...).
> cleanup after string PR

- src/abstractdataframe/selection.jl
- src/groupeddataframe/splitapplycombine.jl
`ByRow` is a function wrapper.
Its callable, so it works like a function.
As such it is not unreasonable to for it to subtype `Function`
Which means it is also covered by `Base.Callable`.
Which means we can simplify some of the more complex type constraints.
(I noticed this because these get more complex in #2199 )
In general I think if something is callable and doesn't already have a supertype, it is a fairly good idea to make it subtype `Function`.
(i would be in general a fan of dropping the [constraints here entirely](https://white.ucc.asn.au/2020/04/19/Julia-Antipatterns.html#dispatching-on--function), but that would require closer looking at the code to see if it would cause any change in dispatch)
> Make ByRow subtype Function

- docs/src/man/getting_started.md
Fixes Getting Started docs -- currently look [like this](http://juliadata.github.io/DataFrames.jl/dev/man/getting_started/#write-DataFrame-out-to-CSV-file-1)
> errant space confused juliadoc builder

- src/abstractdataframe/iteration.jl
- src/dataframerow/dataframerow.jl
- test/dataframerow.jl
In reference to #2164 . Just some short text to make it a bit clearer (hopefully) how to work with `eachrow` a bit better. 
Long term solutions might include a `eachrow(df, namedtuples = true)`. But this seems unnecessary given `select` with `ByRow`.
> dataframerow related docstrings

- Project.toml
A final check before 0.21 release.
The plan is that ideally the next release is 1.0 and we do not include any breaking changes (the reality might turn out to be different).
What are key objectives to do after 0.21 release till 1.0 release:
1. documentation improvements
2. decouple DataFramesBase.jl to make the core much more lightweight
3. adding requested non-breaking functionality
4. find as many bugs as possible before 1.0 release
I would plan that we shall make 1.0 release in 3 to 6 months from now (depending how the things progress and the user feedback).
What I also will do after the release:
1. Write release notes on Discourse + Slack x-ref
2. Update DataFramesTutorial.jl
Thank you for working on the package!
> up version to 0.21.0

- src/groupeddataframe/splitapplycombine.jl
Fix `groupby` references in the documentation of several functions (`select`, `select!` and `transform`)
> Fix several references in documentation

- docs/make.jl
- docs/src/lib/functions.md
- docs/src/lib/internals.md
- docs/src/lib/types.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/join.jl
- src/abstractdataframe/selection.jl
- src/abstractdataframe/show.jl
- src/groupeddataframe/splitapplycombine.jl
> Fix docstring references in the manual

- src/deprecated.jl
- test/deprecated.jl
Now the deprecations are more correct (still we generate other column names in auto-generation of column names mode but I would ignore it). The cost is that they are messy.
> better deprecations of by and map

- Project.toml
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- test/dataframe.jl
1. `append!` incorrectly tried to access a non-existent column in source in some cases.
2. `push!` incorrectly did not clean up the data frame on error in some cases
PS. and this is a lesson for me not to do copy-paste :cry:.
After this is merged it should be backported to 0.21.2.
> fix bugs in append! and push! corner cases

- src/other/utils.jl
- test/grouping.jl
- test/select.jl
- test/utils.jl
Fixes change introduced by https://github.com/JuliaLang/julia/pull/35980.
I assume we prefer `function` rather than `ComposedFunction` to be used in auto-generated column names. Also this is non-breaking this way.
@nalimilan - I have checked and I think that https://github.com/JuliaLang/julia/pull/35980 does not break aggregation code for composed functions (we still should use a fast branch then), but maybe you will want to take a second look.
> [BREAKING] Keep naming ComposedFunction :function

- src/abstractdataframe/join.jl
- test/join.jl
> let indicator allow strings

- .editorconfig
- CONTRIBUTING.md
The `.editorconfig` is very close to the one I use personally. The lines about `end_of_line` and `charset` are best guesses. What do you think about it? If you want one but not the other, I'd be happy to split this PR.
> Add .editorconfig and comment on GitHub Actions

- src/abstractdataframe/selection.jl
- src/groupeddataframe/groupeddataframe.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
- test/select.jl
In this PR I fix some corner cases that were bugs in 0.21 release. It should be merged before https://github.com/JuliaData/DataFrames.jl/pull/2279 as it should be backported.
What it covers:
* documentation improvements of what happens (and should happen in corner cases, especially when something is "empty", where something is: `GroupedDataFrame`, `DataFrame`, list of transformations, or `groupcols`)
* fix a bug with `GroupDataFrame` indexing that caused StackOverflow
* fix a bug in creation of `GroupedDataFrame` with `ungroup=false` (wrong columns could be shown as grouping columns in the past)
* fix cases of "empty" stuff passed (listed above), especially when `keepkeys=false` or `ungroup=false` (there are several corner cases here); most likely in real usage scenarios these cases do …
> Fix various bugs in split/apply/combine in 0.21 release

- src/abstractdataframe/join.jl
- test/join.jl
This PR makes the code cleaner and makes the implementation follow the docstring.
@pdeffebach - this is the change I was talking about in the PR allowing strings as `indicator`.
> improve handling of indicator in joins

- Project.toml
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
This should not change any functionality, but just speed up common cases, as it seems that `all` tests are not optimized out by the compiler.
Also it is a workaround for https://github.com/JuliaData/DataFrames.jl/issues/2289, although probably the bug there is unrelated to DataFrames.jl
> add handling to cases when all is not optimized out

- src/dataframerow/dataframerow.jl
- test/dataframerow.jl
Fixes #2287.
I do not do deprecation as it is a corner case and could be considered a bug in the old implementation.
> [BREAKING] stricter isless for DataFrameRow

- src/abstractdataframe/abstractdataframe.jl
- src/groupeddataframe/groupeddataframe.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
@nalimilan - this is a follow up to your comment in #1732.
> add filter and filter! to GroupedDataFrame

- docs/src/lib/functions.md
- docs/src/lib/types.md
- src/abstractdataframe/iteration.jl
- src/dataframe/dataframe.jl
- src/deprecated.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
- test/indexing_begin_tests.jl
- test/iteration.jl
- test/reshape.jl
- test/select.jl
- test/tables.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2229
I have added functionalities for `DataFrameColumns` that I find useful, but please comment if you would like to see more.
> [BREAKING] Make DataFrameColumns stop being an AbstractVector

- Project.toml
- src/dataframe/dataframe.jl
- test/indexing.jl
Fix  #2332
Also it would be great to merge https://github.com/JuliaData/DataFrames.jl/pull/2331 today so that I can make a patch release before the workshop today (it is about indexing so it would be good to avoid having bugs in this area :)).
> fix DataFrameRow setindex!

- src/groupeddataframe/splitapplycombine.jl
Works around crash seen in #2326. The inferred return type of
`groupreduce_init` is `Union{Vector{Any}, SentinelVector{Float64}}` and
it seems the compiler then crashes when trying to correctly identify `U`
from that union of types. Part of my conclusion here is based on the
fact that if you remove all other argument type constraints and just
make `groupreduce!` return `res` directly, it still crashes; thus, by
deduction, the crash has something to do with the compiler having
trouble with the `::AbstractVector{U}` argument type
constraint/specialization.
The work-around is pretty uncontroversial; we were already calling
`eltype(res)` in several other places, and I've checked that it infers
the same. I didn't add a test since this seems like such an obscure
compiler bug that it doesn't …
> Don't specialize groupreduce! on result array element type

- src/other/tables.jl
- test/tables.jl
Fixes https://github.com/JuliaData/CSV.jl/issues/702. A DataFrame
constructor was removed from CSV.jl in its latest release (0.7.6) as
part of new deprecations for decoupling the two packages. What I forgot
was that we were relying on that constructor because of an ambiguity in
the generic DataFrame constructor fallback that mostly uses Tables.jl to
try and turn anything into a DataFrame. The problem is "mostly"; one of
the checks is if the input is an `AbstractVector` of `AbstractVectors`,
which it turns out `CSV.File` is! This is because it's considered an
`AbstractVector` of `Row`s, which themselves are `<: AbstractVector`. So
we were trying to basically take each row of a `CSV.File` and treat each
row as a column in that fallback constructor.
While it was proposed to put the DataFrame …
> Add check if input is a table before trying alternative constructors

- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2269
As decided there we just drop computing `:median` and `:nunique` by default.
This is simplest to change, and if someone wants them it is easy to opt-in.
Just to get a relative impact on performance of dropping this consider:
```
julia> x = rand(10^8);
julia> @time mean(x)
0.055976 seconds (1 allocation: 16 bytes)
0.5000065333980973
julia> @time median(x)
2.046998 seconds (3 allocations: 762.940 MiB, 8.01% gc time)
0.5000076592923275
julia> @time length(unique(x))
24.142629 seconds (112 allocations: 4.903 GiB, 0.49% gc time)
100000000
```
which when you have even several dozens of variables only starts to be prohibitive.
> remove median and nunique from describe by default

- src/groupeddataframe/groupeddataframe.jl
- test/grouping.jl
Add missing methods for `GroupKey` to make it consistent with `DataFrameRow` which is similar.
See https://github.com/JuliaData/DataFrames.jl/issues/2305 for discussion. CC @goretkin.
Also this should be made consistent with https://github.com/JuliaData/DataFrames.jl/pull/2281 whichever gets merged first. CC @pdeffebach 
After this PR and #2281 another one with `==`, `isequal`, `in` etc. definitions should be done.
I hope I have not missed any definitions - could you please check? Thank you!
> [BREAKING] make GroupKey API more consistent

- src/groupeddataframe/groupeddataframe.jl
- src/groupeddataframe/splitapplycombine.jl
This is a minor fix, but it uses a proper pattern (in some extremely rare corner cases the old code could stall because exception thrown could make the lock not getting released).
@quinnj or @nalimilan - if we could merge this quickly I would backport it to 0.21.6 release that I hope to make soon.
> fix locking of GroupedDataFrame

- .vscode/settings.json
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
This came up on Slack - as the `eltype` is printed in the returned table, there's little additional information in returning `nothing`, as the user can see from `eltype` whether the columns allows `missing` or not. Returning 0 here makes sorting the table on this column easier.
> [BREAKING] Return 0 missing count for columns of nonmissing type

- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2316
also is related to https://github.com/JuliaLang/Statistics.jl/issues/50 and https://github.com/JuliaLang/julia/issues/36978 but I work around it.
@pdeffebach - this PR uncovered many corner cases, a close look at what I propose to do would be welcome.
> [BREAKING] fix isagg to correctly use a fast path

- README.md
Add a reference to JuliaAcademy
> Update README.md with JuliaAcademy reference

- src/abstractdataframe/join.jl
I am slowly moving towards #2340. For now a small fix in the "core code", that shaves off some allocations because it makes it type stable and in consequence time. Nothing big, but not problematic to add either (and it should not degrade performance in any scenario).
Benchmarks:
Code setup:
```
using DataFrames
using Random
Random.seed!(1234);
df1 = DataFrame(id1 = rand(1:1000, 1000000), id2 = rand(1:1000, 1000000), x1=1:1000000);
df2 = DataFrame(id1 = rand(1:1000, 1000000), id2 = rand(1:1000, 1000000), x2=1:1000000);
```
Before PR:
```
julia> @benchmark innerjoin($df1, $df2, on=[:id1, :id2])
BenchmarkTools.Trial: 
memory estimate:  299.87 MiB
allocs estimate:  3999662
--------------
minimum time:     769.417 ms (2.13% GC)
median time:      815.853 ms (4.77% GC)
mean time:        830.811 …
```
> make update_row_maps! type stable

- src/abstractdataframe/abstractdataframe.jl
- src/other/index.jl
- test/dataframe.jl
Currently rename! on `SubDataFrame` either worked or failed with `MethodError` which was not very clear. This PR clarifies this.
I opt to allow `rename!` for `SubDataFrame` with `Index`, as this is consistent with what we discuss in https://github.com/JuliaData/DataFrames.jl/issues/2211 (i.e. to make `SubDataFrame` created with `:` special).
> better error for rename! and improved docstring

- NEWS.md
- src/other/index.jl
- src/other/tables.jl
- test/indexing.jl
- test/tables.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2379
> add columnindex for DataFrameRow, speed up columnindex, fix a bug in indexing

- Project.toml
- src/groupeddataframe/splitapplycombine.jl
Fixes #2382. Same issue and fix as
https://github.com/JuliaData/DataFrames.jl/issues/2326.
> Don't match on AbstractVector type parameter due to compiler crash

- NEWS.md
- src/abstractdataframe/join.jl
- test/join.jl
This will make the kwarg naming conventions more consistent in DataFrames.jl (with reshaping and transformations)
> change kwarg rename to renamecols in joins

- src/abstractdataframe/reshape.jl
The column holding the different :values was erroneously called
'variable_name' in the docstring.
> Fix typo in docstring of `stack`

- NEWS.md
- src/DataFrames.jl
- src/abstractdataframe/reshape.jl
- test/broadcasting.jl
- test/cat.jl
- test/constructors.jl
- test/data.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/deprecated.jl
- test/duplicates.jl
- test/grouping.jl
- test/join.jl
- test/reshape.jl
- test/select.jl
- test/sort.jl
- test/tables.jl
Continuation of #2391 and #2394.
> [BREAKING] Stop reexporting CategoricalArrays

- NEWS.md
- src/abstractdataframe/io.jl
- src/abstractdataframe/iteration.jl
- src/abstractdataframe/show.jl
- src/dataframerow/show.jl
- src/groupeddataframe/show.jl
- test/io.jl
- test/show.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2389
I made it a bit different than Markdown rendering, but I think we do not have to be super cautious here as this is just handling corner cases of display.
Also fixes the problem of overwide first column (not as nicely as PrettyTabes.jl but again - this is a rare corner case now as we are trimming at 32 screen width anyway)
CC @nalimilan @ronisbr
> allow to flexibly change the display width limit

- docs/make.jl
This prevents search engines from pointing to outdated releases. The same change should be applied to HTML files for older releases.
Currently Google seems to point to the latest release, but this is safer.
> Add canonical URL to manual

- docs/src/index.md
As there are long-standing issues that makes ParquetFiles unusable see https://github.com/queryverse/ParquetFiles.jl/pulls where ParquetFiles.jl has not updated to Parquet 0.6 and is still relying on Parquet 0.4.
Also, Parquet.jl can read and write Parquet files now and although it is not feature-complete it is a much better alternative to ParuqetFiles.jl now.
> Replaced ParquetFiles.jl with Parquet.jl

- docs/src/man/comparisons.md
PR #2378 got merged but I just realized the pandas comparison tables are all right-aligned. This PR just make them left-aligned.
> Left align pandas comparison tables

- src/other/tables.jl
```julia
julia> using DataFrames, Tables, BenchmarkTools
[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
julia> X = DataFrame(randn(1000, 10000));
julia> @btime Tables.schema($X); #master
10.189 ms (9505 allocations: 774.17 KiB)
julia> @btime Tables.schema($X); # this PR
1.336 ms (12 allocations: 469.45 KiB)
```
> make schema(df) faster by using less allocation

- docs/src/man/comparisons.md
The `rename` function in pandas creates a copy and so it would more appropriate to provide the equivalent DataFrames.jl example without any mutation as well. Previous discussions at https://github.com/JuliaData/DataFrames.jl/pull/2378#issuecomment-691733622
> Remove mutating examples for adding new columns

- Project.toml
- src/other/utils.jl
As of https://github.com/JuliaLang/julia/pull/37517, `ComposedFunction` becomes a public API and the fields are renamed to `.outer` and `.inner`. This PR uses Compat 3.17 https://github.com/JuliaLang/Compat.jl/pull/720 to make DataFrames work with the new API for all Julia 1.x.
> Use ComposedFunction public API

- src/dataframe/dataframe.jl
- src/subdataframe/subdataframe.jl
- test/indexing.jl
Without it if you pass incorrect types a default `setproperty!` method is invoked (user would have to try very hard to exploit this, but still I think it is better to throw an informative error in this case). The problem was hidden earlier by deprecations.
Before:
```
julia> df = DataFrame(a=1);
julia> dfv = @view df[:, :];
julia> @edit dfv.parent = DataFrame();
julia> df.a = 1
ERROR: type DataFrame has no field a
Stacktrace:
[1] setproperty!(::DataFrame, ::Symbol, ::Int64) at ./Base.jl:34
[2] top-level scope at REPL[12]:1
julia> dfv.parent = DataFrame();
ERROR: setfield! immutable struct of type SubDataFrame cannot be changed
Stacktrace:
[1] setproperty!(::SubDataFrame{DataFrame,DataFrames.Index,Base.OneTo{Int64}}, ::Symbol, ::DataFrame) at ./Base.jl:34
[2] top-level scope at REPL[5]:1 …
```
> fix setproperty! for data frame

- NEWS.md
- docs/src/lib/types.md
- docs/src/man/getting_started.md
- src/abstractdataframe/selection.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
- test/select.jl
This PR partially addresses https://github.com/JuliaData/DataFrames.jl/issues/2410 and https://github.com/JuliaData/DataFrames.jl/issues/2457.
It covers `select` etc. for `AbstractDataFrame`.
If we are OK with the functionality I will update the documentation.
TODO:
* do the same for `select` etc. for `GroupedDataFrame` (this will be a separate PR to keep PRs more atomic)
* add support for `ByRow` with no columns passed to `filter` (also a separate PR)
CC @nalimilan @pdeffebach @matthieugomez - this is a rather complex PR so independent testing (especially for corner cases) would be welcome (if you would have suggestions for types of tests to add please comment and I will add them).
> Allow multicolumn transformations for AbstractDataFrame

- Project.toml
- src/dataframerow/utils.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Generalize existing optimized `row_group_slots` method for `CategoricalArray` and `PooledArray` so that it can be used for other array types for which `DataAPI.refpool` returns an `AbstractVector`. This allows dropping the dependency on CategoricalArrays in this part of the code.
Also refactor the method to be faster when not sorting. In that case, we do not need to build a map between reference codes and groups (indexing into it is slow when the number of groups is very large). `CategoricalArray` is no longer special cased: when `sort=false`, levels are still sorted, but `missing` appears first.
Add more tests to cover weird combinations.
Some benchmarks:
```julia
df = DataFrame(x=PooledArray(rand(1:ngroups, N)), y=rand(N));
julia> @btime groupby(df, :x);
51.310 ms (35 allocations: 76.31 …
```
> [BREAKING] Use DataAPI.refpool for optimized grouping

- NEWS.md
- docs/src/lib/functions.md
- docs/src/man/reshaping_and_pivoting.md
- src/abstractdataframe/reshape.jl
- test/reshape.jl
Figured I'd get a jumpstart on Hacktoberfest, and this is something I've wanted in DataFrames for a longtime. This is an attempt to address #2420 
I implemented 3 versions of `transpose`:
- `transpose1` copies @tbeason 's stack/unstack method from the issue above
- `transpose2` creates a `Matrix` from everything _except_ the indexing column, and does `permutedims` on it
- `transpose3` builds column-by-column by iterating rows
```
julia> builddf(n) = DataFrame(a = [randstring(6) for _ in 1:n], b = rand(n), c = rand(Int, n), d = repeat(["x", "y"], inner=n÷2))
builddf (generic function with 1 method)
julia> df1 = builddf(10);
julia> df2 = builddf(100);
julia> df3 = builddf(1000);
julia> @btime DataFrames.transpose1($df1);
33.565 μs (398 allocations: 32.61 KiB)
julia> @btime …
```
> Implement permutedims

- src/abstractdataframe/join.jl
- src/dataframerow/utils.jl
- test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2502
The problem is that `SubDataFrame` is `UnionAll`. Now I propose to have a container of abstract types, but I think it is OK, as it will save some compilation time + data frame is type unstable anyway.
> Remove type parameters in DataFrameJoiner

- NEWS.md
- src/abstractdataframe/join.jl
I have found a dependency on CategoricalArrays in joins also.
> [BREAKING] remove CategoricalArrays dependency from joins

- NEWS.md
- src/abstractdataframe/join.jl
- test/data.jl
- test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2499.
This is the core implementation and update of docstrings.
I will add tests later, as it first requires https://github.com/JuliaData/DataFrames.jl/pull/2503 to be merged and rebased against.
> [BREAKING] add matchmissing kwarg to joins

- test/reshape.jl
The only changes in this PR is replacing deprecated by non-deprecated syntax in tests.
> fix deprecated tests in reshape

- src/dataframerow/utils.jl
- test/grouping.jl
@nalimilan - this follows your suggestion in https://github.com/JuliaData/DataFrames.jl/issues/2506#issuecomment-723066223.
It is not fully in line with DataAPI.jl API (but I propose - as already mentioned to make that API stricter and require `DataAPI.refpool` to be `AbstractVector`).
If we agree on the proposal I will add more tests.
> make hashrows_col! not depend on CategoricalArrays.jl

- test/cat.jl
- test/dataframerow.jl
- test/grouping.jl
@nalimilan - this behavior differs between CategoricalArrays.jl 0.8.3 and 0.9. I propose to test against 0.9 (also please confirm that this is expected but I guess it is)
> Update Categorical test

- NEWS.md
- Project.toml
- test/select.jl
- test/tables.jl
> Update tests to Tables.jl v1.2

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/iteration.jl
- src/abstractdataframe/join.jl
- src/abstractdataframe/reshape.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- src/groupeddataframe/splitapplycombine.jl
- src/other/index.jl
- src/subdataframe/subdataframe.jl
I wanted to fix this problems in error printing (missing space in both cases):
```
julia> df = DataFrame(a=1)
1×1 DataFrame
Row │ a     
│ Int64 
─────┼───────
1 │     1
julia> push!(df, (a=1, b=2))
ERROR: ArgumentError: `push!` with `cols` equal to `:setequal`requires `row` to have the same number of elements as the number of columns in `df`.
julia> dfv = @view df[:, :]
1×1 SubDataFrame
Row │ a     
│ Int64 
─────┼───────
1 │     1
julia> dfv.x = [1]
ERROR: ArgumentError: Replacing or adding of columns of a SubDataFrame is not allowed.Instead use `df[:, col_ind] = v` or `df[:, col_ind] .= v` to perform an in-place assignment.
```
So I also reviewed the whole source code to make sure that we always use a space at the end of the line when we break it.
+ I changed very long lines in …
> code layout improvements

- CONTRIBUTING.md
- docs/src/man/querying_frameworks.md
- test/reshape.jl
- test/show.jl
- test/tabletraits.jl
This is the third of 3 PRs replacing #2488 now that the big reorg has happened. These should not change or add any functionality, but are instead intended to unify some style conventions.
Here, I add zeros after decimals when floats are manually written. These were found by doing find/replace for `(\d)\.(\D)` => `$1.0$2`, though I had to manually go through and accept the replacements because there are a lot of things like `df1.col`.
In addition, this PR includes addition to `CONTRIBUTING.md` for #2547
> Zero after decimal

- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/reshape.jl
- src/abstractdataframe/show.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
This is the second of 3 PRs replacing #2488 now that the big reorg has happened. These should not change or add any functionality, but are instead intended to unify some style conventions.
Here, I deal with optional arguments in docstrings. There isn't a strong convention here - I looked through Base docstrings, and their style is inconsistent as well. One thing that does seem consistent is that multiple optional arguments have nested brackets, eg `[, opt1[, opt2] ]`. There aren't many examples in this package, but the principle I went with is that everything that is optional (including separators and spaces) should be inside brackets. So eg
```
foo(required[, opt])
bar([opt, ]required)
```
For multiple optional args, I did the same thing, with nested brackets. One thing that may or may …
> Optional args style

- README.md
Not sure whether that's the best link but I couldn't find one in the official documentation.
(I've canceled CI.)
> Add link to CI status badge

- src/abstractdataframe/abstractdataframe.jl
- src/groupeddataframe/splitapplycombine.jl
- src/other/index.jl
Master:
```julia
julia> @time include("cat.jl")
Test Summary: | Pass  Total
...
13.921540 seconds (30.55 M allocations: 1.835 GiB, 3.81% gc time, 97.72% compilation time)
```
This PR:
```julia
12.296551 seconds (28.88 M allocations: 1.728 GiB, 3.05% gc time, 97.42% compilation time)
```
This is of course from a fresh session in both cases, and all the gains are to inference time on first use.
The idea is that improvements in inference quality let your precompile statements do you more good because they reach deeper into the call stack. It may be helpful to outline some of the principles that guide these changes:
- the change to `reduce` tries to "standardize" the types that get passed to `_vcat`; any `DF` that is fully concrete can be specialized, otherwise we standardize on …
> Improve inference in `vcat`

- test/broadcasting.jl
- test/cat.jl
- test/constructors.jl
- test/data.jl
- test/dataframe.jl
- test/dataframerow.jl
- test/grouping.jl
- test/indexing.jl
- test/join.jl
- test/reshape.jl
- test/select.jl
- test/subdataframe.jl
No functionality is changed in this PR
> additional tests to improve coverage

- src/groupeddataframe/show.jl
- test/grouping.jl
`show` always says `GroupedDataFrame`, even when the type would be printed as `DataFrames.GroupedDataFrame`. We do the
same for `DataFrame`. So it makes no sense to use complex constructs such as `$(nameof(typeof(gd)))` nor `$GroupedDataFrame`. This fixes an error when calling `include("test/grouping.jl")` without `using DataFrames`.
> Make GroupedDataFrame show tests more robust to context

- src/abstractdataframe/show.jl
> fix display problem with Turing.jl

- test/grouping.jl
As @nalimilan spotted there is a risk that these cases were not covered comprehensively.
> Add tests for column selection and renaming for GroupedDataFrame

- src/dataframerow/utils.jl
Fixes #2591 
I ended up adding 5/4 (and not 9/8) multiplier based on the following benchmark. But the difference is not big, so we can also do 9/8.
5/4 timings
```
julia> df = DataFrame(value=[string(i) for i in 1:2^24+1]);
julia> @time groupby(df, :value);
1.740594 seconds (31 allocations: 512.002 MiB, 24.71% gc time)
julia> let sub_df = df[1:end-1, :]
@time groupby(sub_df, :value)
end;
1.266897 seconds (31 allocations: 512.002 MiB)
julia> for mul in 17/16:1/16:3/2
let sub_df = df[1:trunc(Int, nrow(df)/mul), :]
@info mul
@time groupby(sub_df, :value)
end;
end
[ Info: 1.0625
1.624300 seconds (31 allocations: 496.943 MiB, 28.38% gc time)
[ Info: 1.125
1.341545 seconds (31 allocations: 483.558 MiB, 19.32% gc time)
[ Info: 1.1875
1.008878 seconds (31 allocations: …
```
> Avoid performance bottleneck corner case in grouping

- NEWS.md
- docs/src/lib/functions.md
- docs/src/man/comparisons.md
- src/DataFrames.jl
- src/abstractdataframe/subset.jl
- test/grouping.jl
This follows https://github.com/JuliaData/DataFrames.jl/issues/2314 discussion.
CC @pdeffebach @matthieugomez
> Add subset

- Project.toml
- src/groupeddataframe/fastaggregates.jl
- test/grouping.jl
For `Number`s for which squaring changes the type, we need to use different types for the mean, the variance and the standard deviation.
Fixes #2600.
@bkamins Do you think we should add Unitful as a test dependency to test this? I wonder whether there are types in Base that would allow reproducing the problem. Otherwise we could create a custom type just for this.
> Fix groupreduce with var and std for Unitful types

- test/tables.jl
@quinnj - I guess it is intended in Tables.jl 1.3.1 change?
> Fix DataFrame(Any[]) test

- NEWS.md
- Project.toml
- docs/src/lib/types.md
- src/abstractdataframe/iteration.jl
- src/abstractdataframe/selection.jl
- src/dataframe/dataframe.jl
- src/dataframerow/dataframerow.jl
- test/indexing.jl
- test/indexing_offset.jl
- test/iteration.jl
- test/select.jl
We currently assume that vectors are 1-based in DataFrames.jl. This PR makes sure we check for that. Not checking this will lead to bugs. Also I found some small bug in `mapcols!` in the process related to `AbstractRange` handling.
I think we should decide on this before 1.0 release (it is better to be strict I think now; we can be more flexible later).
I will add tests, NEWS.md and update documentation with this PR after we agree that we want to add these changes.
> add firstindex check and fix a bug in mapcols!

- docs/src/man/getting_started.md
Also change heading to match the pattern used for other sections.
Spotted while looking at https://github.com/JuliaData/DataFrames.jl/pull/2598.
> Fix missing mention of transform in manual

- src/dataframerow/utils.jl
- test/data.jl
- test/grouping.jl
main:
```julia
julia> using DataFrames, BenchmarkTools
julia> df = DataFrame(x=rand(1:10, 100_000), y=rand(10:20, 100_000));
julia> @btime groupby(df, :x);
730.118 μs (31 allocations: 2.53 MiB)
julia> @btime groupby(df, [:x, :y]);
1.091 ms (38 allocations: 2.53 MiB)
julia> df = DataFrame(x=rand(1:1000, 100_000), y=rand(1000:2000, 100_000));
julia> @btime groupby(df, :x);
1.009 ms (31 allocations: 2.53 MiB)
julia> @btime groupby(df, [:x, :y]);
2.690 ms (38 allocations: 2.53 MiB)
```
PR (updated to latest commits):
```julia
jjulia> using DataFrames, BenchmarkTools
julia> df = DataFrame(x=rand(1:10, 100_000), y=rand(10:20, 100_000));
julia> @btime groupby(df, :x);
186.219 μs (58 allocations: 784.46 KiB)
julia> @btime groupby(df, [:x, :y]);
296.452 μs (85 allocations: 785.84 KiB)
julia> df = …
```
> Use refpool optimized method for integer grouping

- docs/src/man/split_apply_combine.md
- src/abstractdataframe/selection.jl
- src/groupeddataframe/complextransforms.jl
- src/other/utils.jl
- test/grouping.jl
- test/runtests.jl
This is a continuation of (though it's mostly orthogonal to) https://github.com/JuliaData/DataFrames.jl/pull/2574.
Spawn one task per thread in `_combine_rows_with_first!` so that custom grouped operations that return a single row are run in parallel. This is optimal if operations take about the same time for all groups. Spawning one task per group could be faster if these times vary a lot, but the overhead would be larger: we could add this as an option later.
The implementation is somewhat tricky as output columns need to be reallocated when a new return type is detected.
Benchmarks for a relatively fast operation such as (non-fast-path) `sum` (which should be the worst case for this reason) show nice speedups with multiple threads even for small number of rows, and a limited overhead …
> Multithreaded custom grouped operations with single-row result

- Project.toml
@KristofferC - I have a question regarding Project.toml.
If a package is in `[extras]` then is `[compat]` entry allowed for it?
In https://julialang.github.io/Pkg.jl/v1/toml-files/#The-[compat]-section it is stated that only `[deps]` entries are allowed in `[compat]`, but maybe also `[extras]` are allowed and the description given there should be fixed? Thank you!
> Fix CategoricalArrays.jl in Project.toml

- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/broadcasting.jl
- test/subdataframe.jl
- test/utils.jl
Some fixes after https://github.com/JuliaLang/julia/pull/31829.
Mainly restricting the signature of `repeat`.
Additionally one dangling `get` to `unwrap` for CategoricalArrays.jl compatibility I missed earlier.
@mbauman
The https://github.com/JuliaLang/julia/pull/31829 broke the following thing in Julia Base that was not covered by tests (fortunately we had appropriate tests in DataFrames.jl):
```
julia> x = [1,2,3]
3-element Vector{Int64}:
1
2
3
julia> repeat(x, inner=1,outer=1)
3-element Vector{Int64}:
1
2
3
julia> repeat(x, inner=1,outer=false) # it works but I think it should be an error
Int64[]
julia> repeat(x, inner=false,outer=1) # previously it worked
ERROR: ArgumentError: invalid index: false of type Bool
```
> fix repeat and some other minor issues

- src/other/tables.jl
- test/tables.jl
Fixes https://github.com/JuliaData/Arrow.jl/issues/146. The issue here
was we were just ignoring `copycols` entirely when building DataFrame
from `Tables.CopiedColumns`. Which is mostly fine because
`CopiedColumns` implies DataFrames can assume ownership of the columns.
The wrinkle comes in when you consider cases like `Arrow.Table`, which
wraps columns in `Tables.CopiedColumns`, not necessarily because copies
have been made, but because the data is immutable, so it should be safe
for other tables to assume ownership. The problem is when users want to
_mutate_ those columns, they need to make copies of them, so naturally
users try `DataFrame(::Arrow.Table; copycols=true)`, but then that
doesn't actually make copies.
The proposal here just intercepts the top-level …
> Respect copycols when building DataFrame from Tables.CopiedColumns

- docs/src/index.md
- docs/src/man/getting_started.md
Just a small tweak to ensure the documentation is consistent in the capitalization and target link of the references to LINQ. Besides the two ocurrences that this PR changes, there's an additional one in [`docs/src/man/querying_frameworks.md`](https://github.com/JuliaData/DataFrames.jl/blob/6d1347983b67e93d50df847d2d8546a4c9a8cfd4/docs/src/man/querying_frameworks.md).
> Normalize references to LINQ in docs

- src/abstractdataframe/abstractdataframe.jl
- test/data.jl
- test/dataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2651
> update describe, unique and nonunique docs

- benchmarks/grouping_performance.jl
- docs/src/lib/internals.md
- src/dataframerow/utils.jl
- src/other/utils.jl
- test/grouping.jl
- test/utils.jl
main:
```julia
julia> using Revise, DataFrames, PooledArrays, BenchmarkTools
julia> x = PooledArray(rand(1:10, 10_000_000));
julia> df = DataFrame(x=x);
julia> @btime groupby(df, :x);
40.742 ms (38 allocations: 76.30 MiB)
julia> df.x[df.x .== 5] .= 6; # Empty group
julia> @btime groupby(df, :x);
52.488 ms (39 allocations: 76.30 MiB)
julia> x = PooledArray(rand([missing; 1:10], 10_000_000));
julia> df = DataFrame(x=x);
julia> @btime groupby(df, :x);
42.955 ms (42 allocations: 76.30 MiB)
julia> @btime groupby(df, :x, skipmissing=true);
63.951 ms (42 allocations: 76.30 MiB)
```
PR with two threads:
```julia
julia> using Revise, DataFrames, PooledArrays, BenchmarkTools
julia> x = PooledArray(rand(1:10, 10_000_000));
julia> df = DataFrame(x=x);
julia> @btime groupby(df, :x);
25.053 ms (113 …
```
> Use multithreading in row_group_slots refarray method

- NEWS.md
- src/join/composer.jl
- test/join.jl
A minor PR to speed up column creation in joins using threading.
Its major benefit is for left, right and outerjoins having many extra columns (and producing over 1_000_000 rows)
> Support threading in joined column creation

- src/dataframe/dataframe.jl
Maybe I'm misunderstanding the manual here, but shouldn't the `row` be `df2` as in the other options for `cols`?
> Fix small typo in docs

- src/abstractdataframe/show.jl
- test/show.jl
If the user pass the option `show_row_numbers = false` to PrettyTables.jl, then we also need to omit the vertical line in the first column.
Closes #2673
> Omit vertical lines with show_row_numbers = false

- src/other/tables.jl
Fixes #2636 
In the end I decided only to change the return value of `Tables.columns` to `DataFrameColumns` to ensure iteration is supported for it.
I did not go for `DataFrameColumns <: Tables.AbstractColumns` as it did not seem necessary (it would only add `haskey` and `get` methods - we can always add this support later if needed).
> make Tables.columns(df) return eachcol(df)

- src/DataFrames.jl
- src/dataframerow/dataframerow.jl
- src/groupeddataframe/complextransforms.jl
- src/groupeddataframe/groupeddataframe.jl
- src/other/names.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2424
I still need to update tests and docs (which will also make sure we have no bug in my code :smile:). I will do it later this weekend.
The benchmarks are.
Setup:
```
julia> df = DataFrame(x = 1:10^6);
julia> gdf = groupby(df, :x);
julia> f(x) = return (a=x[1], b=x[1]+1)
f (generic function with 1 method)
```
this PR:
```
julia> @benchmark combine($gdf, :x => f => AsTable)
BenchmarkTools.Trial: 
memory estimate:  129.72 MiB
allocs estimate:  1000280
--------------
minimum time:     225.386 ms (1.09% GC)
median time:      242.938 ms (2.17% GC)
mean time:        252.185 ms (5.65% GC)
maximum time:     349.955 ms (27.36% GC)
--------------
samples:          20
evals/sample:     1
```
0.22.6 release:
```
julia> @benchmark …
```
> check if column order is correct in aggregations

- NEWS.md
- src/dataframe/dataframe.jl
- test/dataframe.jl
check for data frame corruption in delete!
> check for data frame corruption in delete!

- src/groupeddataframe/fastaggregates.jl
- test/grouping.jl
This is related to https://github.com/JuliaData/DataFrames.jl/issues/2564#issuecomment-809177160 problem. I propose to produce a `Vector` always when `add_sum` or `mul_prod` is used. The slowdown was due to the fact that output vector was `similar` to input vector, so if input were `PooledArray` a big slowdown was observed.
> Fix grouping aggregation slowdown

- src/abstractdataframe/abstractdataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2693
@pdeffebach - some tests (correctness and performance) would be welcome if you can spare some time.
In my opinion this change should be OK, as rather the called functions should add support for `skipmissing` value passed - and I would rather fix this limitation if possible.
> do not use collect in describe

- benchmarks/grouping_performance.jl
- docs/src/lib/internals.md
- src/groupeddataframe/utils.jl
- src/other/utils.jl
This is somewhat faster for large number of rows (by about 20% for 10M rows and 10 threads), but a bit slower when the number of rows is lower than the threshold (so that a single thread is used). Not sure whether something can be done about it, nor whether the improvement in some cases is worth the loss in others.
```julia
julia> using Revise, DataFrames, BenchmarkTools
julia> for n in (1000, 10_000_000)
df = DataFrame(x=rand(string.(1000000:1000010), n));
@btime groupby($df, :x);
h = similar(df.x, UInt);
n = similar(df.x, Bool);
@btime DataFrames.hashrows_col!($h, $n, $df.x, nothing, true);
end
21.105 μs (29 allocations: 34.05 KiB)
12.211 μs (0 allocations: 0 bytes)
335.166 ms (32 allocations: 280.59 MiB)
122.653 ms (0 allocations: 0 bytes)
26.041 μs (29 allocations: 34.05 KiB)
16.291 …
```
> Enable multithreading in hashrows_col!

- docs/src/lib/internals.md
- src/groupeddataframe/utils.jl
- src/other/utils.jl
It allows keeping the syntax even closer to a normal loop,
and it avoids duplicating functionality. Also simplify `@inbounds`
uses since it work when put in front of `@spawn_for_chunks`.
I've checked that performance is the same.
> Replace `tforeach` with `@spawn_for_chunks`

- Project.toml
- src/groupeddataframe/utils.jl
avoid using `allunique` for `PooledArray`.
> fix PooledArray performance bottleneck

- src/abstractdataframe/abstractdataframe.jl
- test/data.jl
Optimization to two `completecases` methods by only processing _missingable_ columns.
Discussed in #2724
> Optimize `completecases` to process only missingable columns

- NEWS.md
- Project.toml
- src/groupeddataframe/callprocessing.jl
- src/groupeddataframe/complextransforms.jl
- src/groupeddataframe/splitapplycombine.jl
Resolves https://discourse.julialang.org/t/allocations-and-slow-perf-for-transform-on-groupeddataframes/60594
> fix performance issue in multirow split-apply-combine

- docs/src/man/comparisons.md
Update to #2388, with comparison with data.table syntax. Focus on in place changes (!)
> Update comparisons with data.table info

- test/show.jl
@nalimilan - following your query in #2750 I have improved test coverage :smile:.
> Cover corner case of compactype (wide name and CategoricalValue)

- src/other/utils.jl
- test/utils.jl
While testing #2724 and looking at #2769 benchmarks I've seen that sometimes `_findall` allocates a lot and has some weird  overhead in memory. After digging in, changing
`I[i:i+64-1] .= i1:(i1+64-1)` 
into 
```
for j in 0:64-1
I[i + j] = i1 + j 
end
```
removed unnecessary allocations, and sped up execution a bit.
I'll post benchmarks tommorow.
> Explicit loop in `_findall` to avoid allocations

- NEWS.md
- src/abstractdataframe/io.jl
- test/dataframerow.jl
- test/grouping.jl
- test/io.jl
Adds a `title` argument to the types in the HTML output, so that we would get the full type (up to 256 characters) when hovering over the shortened type with a mouse:
> Put longer type into th title argument in HTML show

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/join/composer.jl
- src/other/index.jl
- src/other/utils.jl
- test/index.jl
- test/utils.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2765
> add _findall for AbstractVector{Bool} and use it in internal functions

- test/show.jl
`'$'` and `'\$'` are the same, but the latter confuses code parser in VS Code.
> remove escape in Char

- NEWS.md
- docs/src/man/split_apply_combine.md
- src/abstractdataframe/selection.jl
- test/select.jl
Fixes #2779
This is mildly breaking but I would classify the current behavior as a bug (oversight).
> allow :col => AsTable and :col => cols

- NEWS.md
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2781
> allow Matrices in transformations of GroupedDataFrame

- NEWS.md
- Project.toml
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/cat.jl
- test/deprecated.jl
Preparation for #2776
This is a draft. Finalizing is required, docs update, news update, test update
Things to discuss before I move forward:
1. do we want to add the same to `vcat` (like in `append!`)?
2. the tricky thing is that `hcat(df, table)` and `hcat(table, df)` always produces a `DataFrame`; this could lead to dispatch ambiguities in case if other `table` type also defined `hcat` (and allowed it with `DataFrame`) - what do you think we should do? Maybe only `hcat(df, table)` should be defined and we should use a rule that the first argument governs the dispatch and output type?
> Deprecate AbstractVector in hcat

- src/other/tables.jl
This is part of fixing errors like
https://github.com/JuliaData/CSV.jl/issues/635 in addition to the
changes to support really wide tables in
https://github.com/JuliaData/Tables.jl/pull/241. Luckily, there aren't
many cases I've found across Tables.jl implementations that make working
with really wide tables impossible, but this was a key place where for
really wide tables, we want the names/types to be stored as `Vector`s
instead of `Tuple`/`Tuple{}` in `Tables.Schema`. This shouldn't have any
noticeable change/affect for non-wide DataFrames and should be covered
by existing tests.
> Use standard Tables.Schema constructor instead of constructing directly

- NEWS.md
- src/abstractdataframe/io.jl
- test/dataframerow.jl
- test/grouping.jl
- test/io.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2800
> move summary outside of a <table> in text/html

- docs/src/lib/types.md
- src/dataframe/dataframe.jl
Should help address some confusion in #2799 around `copycols=nothing`
default for `DataFrame` constructor when Tables.jl input is provided.
> Add some clarifying comments on copycols for Tables.jl inputs

- NEWS.md
- Project.toml
- src/dataframe/dataframe.jl
- test/data.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2819.
I will make a release once this is merged.
Notice that currently this PR will fail on nightly, but soon it will pass thanks to https://github.com/JuliaLang/julia/pull/41646 (but I would not wait for Julia Base with merging this PR).
After this PR is merged I will make a patch release.
> fix delete! for versions of Julia 1.6.2 or earlier

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/groupeddataframe/groupeddataframe.jl
- src/groupeddataframe/utils.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2762.
If we accept it then:
* by default we use the fastest algorithm
* if user passes `sort=false` explicitly then groups are created in order of appearance
* if user passes `sort=true` then groups are sorted
If we agree to add this extension I will add tests and NEWS.md entry and finalize this PR.
> make sort kwarg in groupby more flexible

- NEWS.md
- Project.toml
- src/other/index.jl
- test/index.jl
`merge` implementation was super old and it turns out we even did not have proper tests of it. I have added them now. `merge` is used only in `crossjoin` now, and the problem appeared when one tries to do a `crossjoin` of two `SubDataFrame`s with `makeunique=true`. This is also added to the tests
> correct signature of merge for AbstractIndex

- NEWS.md
- src/abstractdataframe/reshape.jl
- test/reshape.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2841
> Fix empty unstack on empty data frame

- src/join/composer.jl
These were likely missed when renaming back DataTables.jl to DataFrames.jl.
> Fix three uses of "data table"

- src/abstractdataframe/abstractdataframe.jl
- test/conversions.jl
Before:
```
julia> Matrix(DataFrame())
ERROR: ArgumentError: reducing over an empty collection is not allowed
[ stacktrace omitted ]
```
After:
```
julia> Matrix(DataFrame())
0×0 Matrix{Union{}}
```
I chose an eltype of `Union{}` because the element type cannot be determined without any columns, and because it's the natural generalization of the type promotion between the columns.
> Allow constructing Matrix from empty dataframe

- NEWS.md
- Project.toml
- docs/src/lib/indexing.md
- docs/src/lib/internals.md
- docs/src/man/working_with_dataframes.md
- src/other/index.jl
- test/index.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2875
I was thinking that we might make it even more flexible and allow predicate to be mixed with other selectors in `Cols`, but for now I proposed a restrictive version. @nalimilan - do you think we should be more flexible?
> Allow predicate in Cols

- NEWS.md
- src/abstractdataframe/selection.jl
- src/groupeddataframe/splitapplycombine.jl
- test/select.jl
> avoid not specialized Pair issue

- NEWS.md
- docs/src/man/split_apply_combine.md
- src/abstractdataframe/selection.jl
- src/groupeddataframe/splitapplycombine.jl
- test/select.jl
@nalimilan + @pdeffebach: I am sharing the preview of the functionality making e.g. `Not(:x1) .=> sum` work in the minilanguage.
The core mechanism should be working for intended cases.
What is todo:
> Add broadcasting of selectors to the minilanguage

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Dispersion statistics are essential to assess the distribution of a variable.
This is inspired by the [skimr](https://github.com/ropensci/skimr) R package. Note that Stata's `summarize` includes the standard deviation too (but no quantiles, not even the median).
I've been willing to try this for some time. The drawback is that this results in a wider table (~120 characters). skimr only uses one of two decimals and it does'nt print column types, which gives a significantly narrower result (note that the example printed in the doctest below is narrower than the standard case since quantiles are exactly represented with only two decimals). This problem will be alleviated a bit if we stop printing vertical bars (saving up to 18 chars).
> Add standard deviation and 25% and 75% quantiles to `describe` :detailed

- NEWS.md
- docs/src/lib/functions.md
- docs/src/lib/internals.md
- src/DataFrames.jl
- src/abstractdataframe/selectionfast.jl
- src/other/utils.jl
- test/select.jl
This PR finishes the issue of wide aggregations I think.
The idea is to special case composition with `collect` so the benefit is that we do not introduce any new syntax to the minilanguage.
With this PR:
```
julia> using Statistics
julia> df = DataFrame(rand(100, 10_000), :auto);
julia> @time combine(df, AsTable(:) => std∘collect);
1.174799 seconds (2.79 M allocations: 200.640 MiB, 6.38% gc time, 97.97% compilation time)
julia> @time combine(df, AsTable(:) => std∘collect);
0.024292 seconds (49.67 k allocations: 35.170 MiB, 38.42% gc time)
julia> @time combine(df, AsTable(:) => ByRow(std∘collect));
0.394846 seconds (888.92 k allocations: 51.886 MiB, 2.47% gc time, 96.65% compilation time)
julia> @time combine(df, AsTable(:) => ByRow(std∘collect));
0.013849 seconds …
```
> Add general fast aggregation for wide tables with collect

- NEWS.md
- docs/src/man/working_with_dataframes.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/subset.jl
- src/groupeddataframe/groupeddataframe.jl
- test/subset.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2924
> Allow passing multiple columns to subset

- src/other/utils.jl
- test/select.jl
An interesting corner-case fix of:
```
julia> struct Identity
end
julia> function (::Identity)(x)
return x
end
julia> i = Identity()
Identity()
julia> df = DataFrame(x=1:3)
3×1 DataFrame
Row │ x
│ Int64
─────┼───────
1 │     1
2 │     2
3 │     3
julia> combine(df, :x => identity∘i)
ERROR: MethodError: no method matching nameof(::Identity)
Closest candidates are:
nameof(::Module) at reflection.jl:16
nameof(::DataType) at reflection.jl:214
nameof(::UnionAll) at reflection.jl:215
...
Stacktrace:
[1] funname(f::Identity)
```
> Correctly handle functors when auto-generating column names

- .github/workflows/ci.yml
Since Julia 1.6 will be a new LTS I propose to add it to our tests. With GitHub Actions this is painless. I would still keep Julia 1.0 in the tests as it does not hurt and it seems we will be able to support it for some time still.
> Update ci.yml in preparation of Julia 1.6 LTS

- NEWS.md
- src/other/broadcasting.jl
This is a transition PR clearly communicating to users what will happen in DataFrames.jl 1.4 release, see https://github.com/JuliaData/DataFrames.jl/issues/2804.
Since the change planned in DataFrames.jl 1.4 will be mildly breaking and will introduce an inconsistency between Julia versions an additional transition period is I think a good approach.
> plan for a change in broadcasting rules in Julia 1.7

- src/other/index.jl
- test/indexing.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2901
> Try to detect unicode normalization issues in column names

- test/join.jl
CI on 32-bit machine very often fails due to out of memory error.
This PR aims to reduce memory footprint of the most problematic testset.
> Change join tests to reduce memory consumption

- test/indexing.jl
Another place where CI tests fail on 32-bit machine because out of memory. The change reduces memory consumption as we cannot make the data smaller since we test threading.
> Reduce test memory usage

- NEWS.md
- src/abstractdataframe/sort.jl
- src/dataframe/sort.jl
I have added a few examples in `issorted` docstrings. And mentioned about lexicographic sorting at `issorted` and `sortperm`.
> Add examples for `issorted` docstrings.

- docs/src/lib/indexing.md
- src/abstractdataframe/abstractdataframe.jl
It was shown to me recently that column selectors can be used inside filter function definitions, which is incredibly useful. I want to add a brief statement and example to the `filter` and `filter!` documentation to show that usage.
> Add row indexing to filter docstring and examples.

- test/join.jl
We still get `OutOfMemoryError` on 32 bit machines. I change them to `@warning` and allow tests to pass in this PR
> Catch OutOfMemoryError

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Please look at this, I've added `view` (defaults to false) kwarg to `first` and `last`. Also added tests to check for checking types of the results that were returned by the above functions. https://github.com/JuliaData/DataFrames.jl/issues/2845
> Add `view` kwarg to `first` and `last`

- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/dataframe.jl
Improve the error message in case column conversion fails, e.g.:
```
julia> df = DataFrame(x=1:3, y=[1,2,missing])
3×2 DataFrame
Row │ x      y       
│ Int64  Int64?  
─────┼────────────────
1 │     1        1 
2 │     2        2 
3 │     3  missing 
julia> disallowmissing(df)
ERROR: ArgumentError: Missing value found in column number 2 
julia> disallowmissing!(df)
ERROR: ArgumentError: Missing value found in column number 2
```
> better disallowmissing error message

- src/join/core.jl
This is a minor cleanup of `ngroups` variable that is not used inside `compute_join_indices!` now.
> Clean up join code

- docs/src/index.md
There's no reason to give a link only to pandas.
Also stop saying that DataFrames.jl is particularly useful for people coming from R and Python as the package is useful for all users, and we already made the comparison with R and Python in the previous sentence.
> Add links to docs, rephrase a bit

- NEWS.md
- Project.toml
- src/abstractdataframe/sort.jl
- test/sort.jl
The problem in DataFrames.jl 1.3.1 is:
```
julia> df = DataFrame(a=1:5, b=11:15, c=21:25)
5×3 DataFrame
Row │ a      b      c     
│ Int64  Int64  Int64 
─────┼─────────────────────
1 │     1     11     21
2 │     2     12     22
3 │     3     13     23
4 │     4     14     24
5 │     5     15     25
julia> sdf = view(df, [1, 2, 3], :)
3×3 SubDataFrame
Row │ a      b      c     
│ Int64  Int64  Int64 
─────┼─────────────────────
1 │     1     11     21
2 │     2     12     22
3 │     3     13     23
julia> sort!(sdf)
ERROR: ArgumentError: data frame contains non identical columns that share the same memory
```
This is caused by incorrect aliasing detection rule.
This PR fixes this.
> fix aliasing detection in sort!

- src/abstractdataframe/subset.jl
- test/subset.jl
@nalimilan - could you please have a look. When we finalize the description I will add the same for `subset!`.
The reason for this note is that we are using recurrence to calculate row condition (so when there are many columns we get stack overflow due too deep recurrence and in general very slow compilation)
> Update subset to handle large number of selectors better

- src/abstractdataframe/reshape.jl
- test/reshape.jl
Fixes #2994 
It turns out that when I have re-written the `unstack` implementation to improve its performance we get handling of no row-key for free. So I have added it.
The question is if we want to add another option for `allowduplicates` like `allowduplicates=:vector`, in which case we would store a list of duplicate values (a la `dplyr` in #2994 example). This would be a new feature (and probably go to 1.4 release as what I make here is a patch)
> allow no rowkey in unstack

- .github/workflows/ci.yml
I was using the ci.yml file as an example and noticed that caching was missing for the `docs` job. I also took the opportunity to switch the other job to use the `julia-actions/cache` Action. The `julia-actions/cache` Action also caches `~/.julia/packages` next to `~/.julia/artifacts`, which may provide a little speedup
> Use `julia-actions/cache`; also for the `docs` job

- NEWS.md
- Project.toml
- docs/src/man/reshaping_and_pivoting.md
- src/abstractdataframe/reshape.jl
- test/reshape.jl
Follow up to https://github.com/JuliaData/DataFrames.jl/pull/2995
Replaces https://github.com/JuliaData/DataFrames.jl/pull/1181
What I would discuss if `allowduplicates` is a good name for this keyword argument now. Maybe we should introduce a new keyword argument (a single one) and deprecate `allowduplicates` (in a long term deprecation fashion i.e. we do need to remove it any time soon)
> allow function in allowduplicates in unstack

- src/abstractdataframe/selection.jl
- src/groupeddataframe/splitapplycombine.jl
- test/select.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2959
Example:
```
julia> df = DataFrame(id=1:2, a=[(a=1,b=2),(a=3,b=4)])
2×2 DataFrame
Row │ id     a
│ Int64  NamedTup…      
─────┼───────────────────────
1 │     1  (a = 1, b = 2)
2 │     2  (a = 3, b = 4)
julia> gdf = groupby(df, :id)
GroupedDataFrame with 2 groups based on key: id
First Group (1 row): id = 1
Row │ id     a
│ Int64  NamedTup…      
─────┼───────────────────────
1 │     1  (a = 1, b = 2)
⋮
Last Group (1 row): id = 2
Row │ id     a
│ Int64  NamedTup…      
─────┼───────────────────────
1 │     2  (a = 3, b = 4)
julia> select(df, :a => [:x])
ERROR: ArgumentError: Number of returned columns is 2 and it does not match the length of requested output which is 1
julia> select(gdf, :a => [:x])
ERROR: ArgumentError: Number …
```
> Improved error when column numbers do not match in transformations

- test/broadcasting.jl
- test/dataframe.jl
- test/join.jl
- test/reshape.jl
Avoids issues in tests caused by `CategoricalVector` promotion rules.
> avoid categorical promotion

- NEWS.md
- docs/src/lib/indexing.md
- src/other/broadcasting.jl
- test/broadcasting.jl
- test/dataframe.jl
- test/deprecated.jl
- test/subdataframe_mutation.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2804
> make broadcasting assignment consistent with !

- NEWS.md
- src/abstractdataframe/subset.jl
- test/subset.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3024
I have additionally corrected the docstring.
> handle empty args in subset

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
EDIT: nothing in this comment is still true. See the discussion below.
This is an improvement when there are 3+ columns, and should be an improvement for fewer columns once [upstream](https://github.com/scheinerman/Permutations.jl/pull/24) [changes](https://github.com/scheinerman/Permutations.jl/pull/25) merge.
```julia
using DataFrames, Random, BenchmarkTools
df = DataFrame([rand(500_000) for _ in 1:50], :auto);
@benchmark permute!(df, p) setup=(p=shuffle!(collect(1:500_000)))
```
Gives an 8x speedup on my computer: `2.207 s` to `276.050 ms`
(blocked until https://github.com/scheinerman/Permutations.jl/pull/24 merges due to pathological `O(rows^2)` runtime on identity permutation)
> Use cycle notation to speed up `permute!`

- NEWS.md
- src/abstractdataframe/iteration.jl
- test/iteration.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3023
Difference in performance:
```
julia> df = DataFrame(x=1:10^7);
julia> er = eachrow(df);
julia> @benchmark er[1:2:end]
BenchmarkTools.Trial: 10000 samples with 930 evaluations.
Range (min … max):  101.398 ns …   4.602 μs  ┊ GC (min … max): 0.00% … 97.35%
Time  (median):     114.194 ns               ┊ GC (median):    0.00%
Time  (mean ± σ):   125.150 ns ± 188.553 ns  ┊ GC (mean ± σ):  6.88% ±  4.44%
▂▇██▄▂
▄▄▄▃▄▅▆██████▆▄▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
101 ns           Histogram: frequency by time          179 ns <
Memory estimate: 160 bytes, allocs estimate: 5.
julia> @benchmark er[1:2:end, 1]
BenchmarkTools.Trial: 24 samples with 1 evaluation.
Range (min … max):  106.814 ms … 376.798 ms  ┊ GC (min … max): …
```
> Make indexing of eachrow return the object of the same type on a view of the parent

- NEWS.md
- src/abstractdataframe/subset.jl
- test/subset.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2740
> allow scalars in subset and subset! as conditions

- docs/src/index.md
Added `AlgebraOfGraphics` and replaced `LightGraphs` due to it being renamed a few months ago.
> Update "Julia Data Ecosystem" list

- NEWS.md
- Project.toml
- docs/src/lib/functions.md
- src/DataFrames.jl
- src/dataframe/dataframe.jl
- test/dataframe.jl
Partially implement changes requested in https://github.com/JuliaData/DataFrames.jl/issues/2936.
@nalimilan - if you agree with the proposed changes (especially `deleteat!` - I think, given that the operation is expensive anyway, we can afford sorting and de-duplicating incorrect input instead of having an undefined behavior in this case) I will add tests.
> add resize!, keepat!, pop!, popfist!, popat!

- docs/src/lib/functions.md
- src/dataframe/dataframe.jl
- src/other/tables.jl
- test/dataframe.jl
Another step towards https://github.com/JuliaData/DataFrames.jl/issues/2936
> add prepend!

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/selection.jl
- src/dataframe/dataframe.jl
- src/groupeddataframe/splitapplycombine.jl
- src/subdataframe/subdataframe.jl
- test/select.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3069.
What this PR addresses.
1. The initially reported performance issue. After the PR:
```
julia> using DataFrames, BenchmarkTools
julia> df = DataFrame(rand(100000, 100), :auto);
julia> subdf = view(df, df.x1 .>= 0.5, :);
julia> @btime transform!($subdf, :x1 => maximum => :x1);
289.800 μs (128 allocations: 1.15 MiB)
julia> gdf = groupby(subdf, :x2);
julia> @btime transform!($gdf, :x1 => maximum => :x1);
1.090 ms (300 allocations: 4.21 MiB)
```
and before the PR:
```
julia> using DataFrames, BenchmarkTools
julia> df = DataFrame(rand(100000, 100), :auto);
julia> subdf = view(df, df.x1 .>= 0.5, :);
julia> @btime transform!($subdf, :x1 => maximum => :x1);
37.446 ms (1642 allocations: 114.68 MiB)
julia> gdf = groupby(subdf, :x2); …
```
> Performance of transform! on SubDataFrame

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3074
> Fix vcat in case no data frames are passed

- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
@nalimilan :
1. Your recent comment prompted me to add `isempty` documentation as in DataFrames.jl when we say that data frame is empty it means that it has 0 rows (but can have some columns). I have also simplified `isempty` implementation as currently data frame that has positive number of rows must have some columns.
2. I have also split duplicate definitions in documentation that we discussed we should do.
> Improve documentation and speedup isempty

- Project.toml
- src/DataFrames.jl
Added to Julia in https://github.com/JuliaLang/julia/pull/43334, added to Compat in https://github.com/JuliaLang/Compat.jl/pull/777 (v4.2). This PR requires the latter to be merged and tagged first.
Closes https://github.com/JuliaData/DataFrames.jl/issues/3119.
> Extend `stack` from Base/Compat

- NEWS.md
- Project.toml
- docs/src/lib/types.md
- src/DataFrames.jl
- src/abstractdataframe/selection.jl
- src/other/tables.jl
- test/grouping.jl
- test/tables.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3127
> Synchronize ByRow and Tables.subset with Tables.jl 1.8

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3154
> Fix type assertion in _filter_helper

- src/join/composer.jl
`semijoin` and `antijoin` ignore `makeunique` kwarg. To be non-breaking I would keep it but note that it is ignored.
> Fix docstring of semijoin and antijoin

- NEWS.md
Small cleanup to make sure that NEWS.md between 1.3 and 1.4 branches are consistent
> synch NEWS.md between 1.4 and 1.3 branches

- src/other/index.jl
Following discussion on Slack.
After the change:
```
julia> df = DataFrame()
0×0 DataFrame
julia> df.a
ERROR: ArgumentError: column name "a" not found in the data frame since it has no columns
julia> df = DataFrame(a=1, b=2, c=3)
1×3 DataFrame
Row │ a      b      c     
│ Int64  Int64  Int64 
─────┼─────────────────────
1 │     1      2      3
julia> df.d
ERROR: ArgumentError: column name "d" not found in the data frame; existing most similar names are: "a", "b" and "c"
```
I use string quoting not `:` and backticks as suggested on Slack as we allow string as column name.
> improve error message when column is not found

- test/indexing.jl
Work with a matrix filled with `nothing` instead of random `Int8`s, goes from 98 KB to 48 B. This is an attempt to perhaps elevate the failiure here: https://github.com/JuliaData/DataFrames.jl/actions/runs/3091782763/jobs/5002284179#step:6:1105
> Reduce memory use in threading correctness tests

- src/abstractdataframe/reshape.jl
- test/reshape.jl
Going along with the other PR #3114, I was thinking maybe it would be better to just make permutedims easier to use instead of try to change the DataFrame constructors. 
The current methods for permutedims are honestly pretty confusing to me and I was surprised there wasn't a simple method that just permutes and doesn't add new columns or anything annoying like that.
I would love if someone could make it non-allocating or whatever, but I think regardless it makes sense to have this method defined. 
Would appreciate some comments :)
> 1-arg permutedims(df)

- src/abstractdataframe/reshape.jl
- test/metadata.jl
Fixes the missing part of `permutedims` implementation from #3115.
> fix metadata handling in permutedims

- src/dataframe/insertion.jl
Typically an error in `push!` etc. is because `promote=false` is set. This PR improves error message to give a proper hint to the user.
CC @nickrobinson251
> Add better error message on error when pushing rows to a data frame

- src/abstractdataframe/abstractdataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3171
@mortenpi - could you have a quick look if this is correct 😄.
The relevant page in the manual is https://dataframes.juliadata.org/dev/lib/indexing/#General-rules
Thank you!
> improve names docstring

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/abstractdataframe/sort.jl
- src/groupeddataframe/fastaggregates.jl
- src/groupeddataframe/groupeddataframe.jl
- src/other/broadcasting.jl
- src/subdataframe/subdataframe.jl
- test/broadcasting.jl
- test/dataframe.jl
- test/grouping.jl
- test/runtests.jl
- test/sort.jl
- test/subdataframe.jl
@nalimilan - this is a first step towards DataFrames.jl 1.4. release. To make sure things are precompiled correctly one of the recommendations is to avoid dispatch ambiguities. This recommendation makes sense in general.
This PR:
* fixes these cases
* fixes incorrect behavior that was detected when analyzing these ambiguities
* makes sure that in the future we test for dispatch ambiguities and for unbound type parameters
I comment on the reasons for changes in the code.
> Avoid method dispatch ambiguities in DataFrames.jl

- test/join.jl
@nalimilan - the multithreading tests for 32-bit machine constantly fail. I think it is better to just disable them in that case.
> enable multithreading tests of joins only on 64 bit machines

- docs/src/man/split_apply_combine.md
- src/groupeddataframe/show.jl
- test/show.jl
This is a small enhancement to make `GroupedDataFrame`s display so that they fit in one screen, like regular `DataFrame`s with many rows.
Before, the first and last groups of a `GroupedDataFrame` would be displayed at full size; now, the two groups are made smaller (using the `:displaysize` parameter in `IOContext`) so that together they fill the required line height.
If the first group is smaller than half the available REPL height, and the last group is larger, or vice versa, then the smaller group is shown in full and the larger one is squashed (displayed with missing rows). This means that the group with the most rows takes up the most room visually, even after some of its rows are skipped.
See the `"GroupedDataFrame displaysize test"` test set for example output.
> Improved REPL printing for GroupedDataFrames

- src/groupeddataframe/show.jl
- test/show.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3186
Covers all corner cases of various relative sizes of groups and single group.
> improve printing of GroupedDataFrame in corner cases

- NEWS.md
- docs/src/man/reshaping_and_pivoting.md
- src/abstractdataframe/reshape.jl
- test/deprecated.jl
- test/metadata.jl
- test/multithreading.jl
- test/reshape.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3184
We can still discuss the name if needed. Current proposal is `valuesfunction`.
> rename valuestransform to combine in unstack

- Project.toml
- src/other/metadata.jl
- test/metadata.jl
This PR should be passed through CI after https://github.com/JuliaData/DataAPI.jl/pull/53 is merged and DataAPI.jl 1.12.0 is released. Other than that it should be complete (not tested, but the changes are minor - mostly simplification of the code because of dropped default implementations + adding support for `default`).
> Sync metadata implementation with DataAPI.jl 1.12.0

- NEWS.md
- Project.toml
- src/abstractdataframe/iteration.jl
- test/iteration.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3191
> make sure getindex on DataFrameRows does not alias passed selector

- docs/Project.toml
- docs/src/index.md
- docs/src/man/querying_frameworks.md
- docs/src/man/working_with_dataframes.md
With the two modes of multi-column manipulation, I think this package is again sufficiently different from DataFramesMeta.jl to warrant being mentioned in the DataFrames docs. Otherwise, I think most people will not be able to find it.
I have written "similar to DataFramesMeta" in a couple places, as you know that package came first and there was some cross-pollination back and forth. It seems to me writing "similar" is a shortcut to not repeat the same information again, but if you want to adjust the language, I don't mind. I don't want the text to sound like "similar but better" because it's not a competition and I don't mean it like that.
> Mention DataFrameMacros.jl in the docs

- docs/src/man/basics.md
- docs/src/man/getting_started.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3200
> improve manual entry of assignment to a data frame

- NEWS.md
- Project.toml
- src/abstractdataframe/io.jl
- src/dataframerow/show.jl
- src/groupeddataframe/show.jl
- test/runtests.jl
- test/show.jl
What this PR changes:
1. better code organization (so that later changes to `DataFrameRow` and `GroupedDataFrame` printing are needed to be made in one file).
2. key of the PR: use `MIME("text/plain)` when calling `repr` to show group label key. This is needed to avoid printing type name in some cases (which is not useful).
This resolves the issue that before this change docs building was not passing due to the changes in InlineStrings.jl printing rules.
> Make sure we use MIME when calling repr in GroupedDataFrame printing

- docs/src/man/basics.md
- docs/src/man/getting_started.md
- src/dataframe/dataframe.jl
- test/io.jl
PrettyTables.jl 2.2 changes invalidated one test.
> fix HTML printing tests after PrettyTables.jl 2.2 release

- NEWS.md
- Project.toml
- src/other/metadata.jl
- test/metadata.jl
Following https://github.com/JuliaData/DataAPI.jl/pull/56. Should be merged after DataAPI.jl 1.13 release.
> add default style to metadata! and colmetadata!

- NEWS.md
- docs/src/man/split_apply_combine.md
- src/abstractdataframe/selection.jl
- src/groupeddataframe/complextransforms.jl
- src/groupeddataframe/splitapplycombine.jl
- test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3217
> make aggregation of empty GroupedDataFrame correct with AsTable

- NEWS.md
- Project.toml
- src/abstractdataframe/selection.jl
- src/other/index.jl
- test/index.jl
- test/select.jl
Fixes the following bug:
```
julia> df = DataFrame(a=1:3)
3×1 DataFrame
Row │ a
│ Int64
─────┼───────
1 │     1
2 │     2
3 │     3
julia> dfv = view(df, :, :)
3×1 SubDataFrame
Row │ a
│ Int64
─────┼───────
1 │     1
2 │     2
3 │     3
julia> select(dfv, x -> true, copycols=false) # bug - this should error
3×1 SubDataFrame
Row │ a
│ Int64
─────┼───────
1 │     1
2 │     2
3 │     3
julia> select(dfv, x -> true) # correct behavior in case of copying, but impossible to achieve without copying when working on a view
3×1 DataFrame
Row │ x1
│ Bool
─────┼──────
1 │ true
2 │ true
3 │ true
```
> fix select bug with copycols=false on SubDataFrame

- docs/src/man/split_apply_combine.md
- src/abstractdataframe/selection.jl
This PR adds additional explanation of context dependent expressions in operation specification syntax to make sure users know exactly how they work.
CC @yjunechoe @pdeffebach
> Explain column-independent operations

- NEWS.md
- Project.toml
- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
Having this function would be convenient in cases like https://discourse.julialang.org/t/arrow-stream-usage-clarification/89508.
With this PR adding new functionalities for 1.5 release starts. I will manage patches to 1.4.x releases in a separate branch if they are needed.
> add Iterators.partition

- NEWS.md
- docs/src/lib/functions.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/subdataframe/subdataframe.jl
- test/dataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3205
Requires adding:
* NEWS.md entry (after other 1.5 release PRs are merged)
* rebasing after https://github.com/JuliaData/DataFrames.jl/pull/3231 PR is merged
> Add allunique and improve nonunique and describe

- src/abstractdataframe/subset.jl
- src/dataframe/dataframe.jl
- test/dataframe.jl
Explanation in https://discourse.julialang.org/t/learning-to-benchmark-and-find-the-best-function-to-select-a-subset-of-a-dataframe/91704/12.
```
julia> using Random
julia> Random.seed!(1234)
TaskLocalRNG()
julia> df = DataFrame(rand(10^6, 100), :auto);
julia> df.id = rand(1:100, 10^6);
julia> inds = rand(Bool, 10^6);
julia> x = copy(df); @time deleteat!(x, inds);
0.084989 seconds (29.05 k allocations: 1.471 MiB, 11.83% compilation time)
julia> x = copy(df); @time deleteat!(x, inds);
0.074356 seconds (305 allocations: 4.766 KiB)
julia> x = copy(df); @time subset!(x, :x1 => Returns(inds));
0.091337 seconds (485 allocations: 262.422 KiB)
julia> x = copy(df); @time subset!(x, :x1 => Returns(inds));
0.148983 seconds (485 allocations: 262.422 KiB)
julia> x = groupby(copy(df), :id); @time …
```
> fix deleteat! and subset! performance

- NEWS.md
- docs/src/man/joins.md
- src/join/composer.jl
- test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2753
The performance probably can be improved in some cases, but I wanted to start with something simple that works (and already has performance that is not horrible).
I proposed the `sort` kwarg to specify sorting order, but maybe some other name would be better (earlier we discussed `order`).
> Add an option in joins to specify row order

- docs/src/index.md
Users asked to give a hint that macro-packages can be easier to use for newcomers in the opening page of DataFrames.jl manual near its top (so that it is easily discoverable).
@nalimilan, @pdeffebach, @jkrumbiegel - I have proposed something, but I am not sure if the wording is best. Can you please comment? (I think that good wording here is important) Thank you!
Also I mention only DataFramesMeta.jl as I did not want to introduce additional user confusion (i.e. that they need to make choices between DataFramesMeta.jl and DataFrameMacros.jl). But maybe it is better to mention both. I am open for suggestions.
(they are both mentioned below in data wrangling section)
> Add hints to use macro packages for new users

- docs/src/man/basics.md
- docs/src/man/working_with_dataframes.md
Small improvements based on user feedback
> Improve examples in the manual in basics.md

- src/groupeddataframe/splitapplycombine.jl
@nalimilan - also I think the issue is that our current stack trace is super long (essentially the same information is printed several times):
```
julia> df = DataFrame(a=[1, 1, 2, 2], b=11:14, c=21:24)
4×3 DataFrame
Row │ a      b      c     
│ Int64  Int64  Int64 
─────┼─────────────────────
1 │     1     11     21
2 │     1     12     22
3 │     2     13     23
4 │     2     14     24
julia> combine(groupby(df, :a), AsTable([:b, :c]) => DataFrame => :bc)
ERROR: ArgumentError: a single value or vector result is required (got DataFrame). Maybe it 
was forgotten to wrap the return value of the operation with `Ref`.
Stacktrace:
[1] _combine(gd::GroupedDataFrame{DataFrame}, cs_norm::Vector{Any}, optional_transform::Vec
tor{Bool}, copycols::Bool, keeprows::Bool, renamecols::Bool, …
```
> improve error message in operation specification syntax

- NEWS.md
- src/abstractdataframe/subset.jl
- test/subset.jl
This PR fixes a situation when we can only detect that no conditions are passed after processing them. Example of wrong behavior (fixed by this PR):
```
julia>     df = DataFrame(a=1:2)
2×1 DataFrame
Row │ a
│ Int64
─────┼───────
1 │     1
2 │     2
julia> subset(df, Not(:a) .=> ByRow(Returns(true)))
ERROR: AssertionError: !(isempty(conditions))
```
> Fix bug in subset[!] when handling no conditions case

- docs/src/index.md
- docs/src/lib/metadata.md
TableMetadataTools.jl is now a registered package after a first round of user feedback.
I think it is good to add a reference to it as these convenience functions are important for performing common operations on metadata.
> add information about TableMetadaTools.jl to docs

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- test/data.jl
Make sure we are explicit which values vary fastest when constructing a data frame.
> Improve allcombinations docstring + minor cleanups after #3256

- NEWS.md
- src/other/index.jl
- test/index.jl
Fixes issue raised on Slack.
I do not remember why we have not added support for it from the start, but I do not see the reason to disallow selectors like:
```
df[:, Cols(startswith("a"), endswith("2"))]
```
> Allow to pass multiple predicates in `Cols` and mix them with other selectors

- NEWS.md
- src/abstractdataframe/iteration.jl
- test/iteration.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3281
> add haskey and get support for DataFrameColumns

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- test/reshape.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2767
> Add `scalar` keyword argument to `flatten`

- docs/src/man/basics.md
I noticed this duplication only after the manual was deployed.
> Fix typo in the manual

- docs/src/lib/metadata.md
- docs/src/man/reshaping_and_pivoting.md
- docs/src/man/split_apply_combine.md
- src/abstractdataframe/reshape.jl
- src/abstractdataframe/selection.jl
- src/abstractdataframe/sort.jl
- src/groupeddataframe/fastaggregates.jl
- test/reshape.jl
Fixes some typos that I've found in the repository.
> Fix some typos

- docs/src/man/basics.md
- docs/src/man/importing_and_exporting.md
- docs/src/man/reshaping_and_pivoting.md
- docs/src/man/sorting.md
- docs/src/man/split_apply_combine.md
This makes the examples easier to read since:
```julia
julia> joinpath(dirname(pathof(DataFrames)), "..", "docs") |> normpath
"/home/rik/.julia/packages/DataFrames/LteEl/docs"
julia> joinpath(pkgdir(DataFrames), "docs")
"/home/rik/.julia/packages/DataFrames/LteEl/docs"
```
Regarding availability, `pkgdir` is available since Julia 1.4 (https://github.com/JuliaLang/julia/blob/v1.4.0/NEWS.md) and this repo is lower bounded to Julia 1.6: 
https://github.com/JuliaData/DataFrames.jl/blob/0b3d620ef6acd287d5db74258972f470532029e3/Project.toml#L47
The trailing spaces behind the tables were removed automatically by my editor. Let me know if I should undo that.
> Use `pkgdir` instead of `pathof`

- NEWS.md
- src/abstractdataframe/iteration.jl
- src/other/tables.jl
- test/iteration.jl
- test/tables.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3054
> add nrow, ncol, and Tables.subset for eachcol and eachrow

- NEWS.md
- src/join/composer.jl
- test/join.jl
Following user's request on Discourse.
> Add support for `renamecols` keyword argument in `crossjoin`

- docs/src/man/categorical.md
- docs/src/man/joins.md
- src/join/composer.jl
- src/join/inplace.jl
This documents that the join functions use `isequal` for key comparisons. It also adds a note that joining on floating point values is not recommended.
I also added the "`on` is a required argument" sentence to all the relevant docstrings (previously it was only included in the `innerjoin` and `outerjoin` docstrings).
The `isequal` sentence in the `matchmissing` bullet point seemed redundant so I removed it, but please check, maybe I misunderstood its meaning.
> Document use of isequal for comparisons

- docs/src/man/getting_started.md
I feel those constructors are used frequently and hard to find if not in getting started doc. Would it be better to copy them here? 
And I feel the `Note` section on top a bit long and useless in a getting started doc. I think the display is ommited is already obvious from the output. Might be better to move that out to another advanced topic page.
> copy more constructors from type doc to getting started

- src/abstractdataframe/selection.jl
Sorry, it seems that the typo comes from `[@ref]`, which should be `(@ref)`.
> `[@ref]` => `(@ref)`

- .github/workflows/ci.yml
Recently I have noticed that much more often than it happened in the past I get DataFrames.jl tests fail on Julia nightly, but then the issue goes away, but some new almost immediately pops out.
I propose to disable tests passing on Julia nightly in total test result evaluation (but still run them to see if they pass or fail).
CC @DilumAluthge
> Allow CI failure on Julia nightly

- src/abstractdataframe/abstractdataframe.jl
`permute!!` and `invpermute!!` are internal functions of Base, not covered by SymVer. We shouldn't be using them as sentinels here when the public `permute!` and `invpermute!` would work identically.
> Stop using internal [inv]permute!! as sentinel

- src/abstractdataframe/abstractdataframe.jl
use the same mechanism in `reverse!` as is already in use in `_permutation_helper!`. Because these are and should likely remain the same, I also factored out the common code into an internal helper function.
I did not make the helper function generic enough to also cover `_dealias_dataframe!`, but I still think this PR is an improvement in maintainability as well as performance.
> optimize reverse! for small data frames and factor out _foreach_unique_column

- test/grouping.jl
- test/select.jl
This is a minor test fix.
@LilithHafner - there are currently a lot of failing tests on Julia nightly due to sorting changes following #3340.
I understand that soon they would be gone, right? (when your PR to Julia is merged).
I will wait to merge this PR until then.
> fix dispatch errors in tests on Julia 1.10

- src/abstractdataframe/show.jl
- test/show.jl
> Do not crop columns with type Base.UUID

- docs/src/man/joins.md
- src/join/composer.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3345
> improve error messages in joins

- NEWS.md
- docs/src/man/split_apply_combine.md
- src/DataFrames.jl
- src/abstractdataframe/selection.jl
- src/groupeddataframe/callprocessing.jl
- src/groupeddataframe/complextransforms.jl
- src/groupeddataframe/splitapplycombine.jl
- src/other/names.jl
- test/grouping.jl
- test/select.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3335
After this PR `Tables.AbstractRow` is treated in the same way as `DataFrames.DataFrameRow` in all `combine`/`select`/`transform` operations.
> Correctly handle Tables.AbstractRow in operation specficiation

- test/show.jl
It is a standard `Int32` vs `Int64` issue.
> fix tests on 32-bit

- src/dataframe/insertion.jl
- test/insertion.jl
Improve error in cases like:
```
append!(DataFrame(x=PooledArray(1:255, UInt8)), DataFrame(x=PooledArray(256:500, UInt8)); promote=true)
```
as reported by @jariji
> Improve error message when pushing/appending with promote=true

- src/abstractdataframe/abstractdataframe.jl
This method was documented in `rename!` but not in `rename`, so I copied the example over. I also changed two Symbols to Strings in the second example so they also match.
This is a comparison of the two docstrings before my changes:
> Add vector of names method to `rename` docstring

- CITATION.bib
- README.md
- docs/src/index.md
This also follows the request from JSS
> Add JSS citation information

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/other/index.jl
- test/dataframe.jl
- test/index.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3361
> add cols kwarg to rename/rename!

- .github/workflows/ci.yml
- NEWS.md
- docs/src/lib/functions.md
- src/other/utils.jl
When Julia ≥ 1.9 is started with `-tX,Y`, by default tasks use the pool of interactive threads instead of the default pool. Fix this by updating `spawn_or_run_task` to match the code used by `@spawn` in Julia master.
Fixes #3383.
> Fix `@spawn_or_run_task` with interactive threads

- NEWS.md
- src/abstractdataframe/iteration.jl
- test/iteration.jl
add `cols` kwarg to `mapcols` and `mapcols!` similarly like we recently did for column renaming.
This is a useful addition for cases when e.g. one wants to transform only columns meeting some condition and keep the column order unchanged.
> add cols to mapcols and mapcols!

- NEWS.md
- src/abstractdataframe/unique.jl
- src/groupeddataframe/utils.jl
- test/duplicates.jl
- test/grouping.jl
fixes https://github.com/JuliaData/DataFrames.jl/issues/3392
reproducer:
```
julia> nonunique(DataFrame(a=PooledArray(Int[])))
ERROR: InexactError: trunc(Int64, NaN)
```
> fix nonunique bug

- test/join.jl
I must have left these `@time` calls by mistake. They are not needed. Tests.jl reports time of running `@testset` anyway.
> remove unnecessary @time in tests

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- test/dataframe.jl
> fix first and last for negative row count

- docs/src/man/basics.md
Related to https://github.com/JuliaData/DataFrames.jl/issues/3382
> add example of using Tables.dictcolumntable

- NEWS.md
- src/abstractdataframe/iteration.jl
- test/iteration.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3412
@nalimilan - I add it to 1.7 release as probably there is still some time till Julia 1.11 release.
Having said that - I propose we go back to the discussion on which open PRs from https://github.com/JuliaData/DataFrames.jl/pulls we want to merge and make 1.7 release of DataFrames.jl.
The bug is uncovered due to https://github.com/JuliaLang/julia/pull/52736, which starts using `CartesianIndexing` in broadcasting `BitArray`.
> Fix eachrow and eachcol indexing with CartesianIndex

- docs/src/index.md
* Add JuliaCon2023 link
* Sort by descending order (recent info should come first)
> Update docs on Juliacon

- NEWS.md
- src/abstractdataframe/abstractdataframe.jl
- src/dataframe/dataframe.jl
- src/groupeddataframe/utils.jl
- src/join/core.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3418
> Change big to BigInt calls

- NEWS.md
- src/abstractdataframe/unique.jl
- test/dataframe.jl
This resolves dispatch ambiguity introduced in Julia 1.11.
> disambiguate allunique signature

- NEWS.md
- src/abstractdataframe/selection.jl
- test/select.jl
@nalimilan - following your comment on Slack this is a DataFrames.jl fix. In it I propose even more extreme approach - do not generate any columns if the returned vector is empty. This will make consistent behavior of `DataFrame`, and `GroupedDataFrame`, as it is now a corner case when they differ.
The behavior before this PR is:
```
julia> df = DataFrame(a=[1,2,3])
3×1 DataFrame
Row │ a
│ Int64
─────┼───────
1 │     1
2 │     2
3 │     3
julia> gdf = groupby(df, :a)
GroupedDataFrame with 3 groups based on key: a
First Group (1 row): a = 1
Row │ a
│ Int64
─────┼───────
1 │     1
⋮
Last Group (1 row): a = 3
Row │ a
│ Int64
─────┼───────
1 │     3
julia> combine(df, :a => (a -> [(b=1,c=2)][1:0]) => AsTable) # we try to identify columns
0×2 DataFrame
Row │ b      c
│ Int64  Int64 …
```
> do not pass empty vector to Tables.columntable

- docs/Project.toml
- docs/src/man/querying_frameworks.md
This PR adds TidierData to the frameworks manipulations docs page. 
I tried to keep it brief and similar to the other framework examples. 
I am happy to make any changes. 
@kdpsingh @bkamins 
Thank you
> Add TidierData to frameworks docs page

- src/groupeddataframe/complextransforms.jl
- test/io.jl
- test/select.jl
It in particular fixes an error that enabled multithreading in cases where it should be disabled
> fix tests on nightly and 32-bit

- src/abstractdataframe/show.jl
noticed after https://github.com/apache/arrow-julia/pull/512 was displaying `Union{Missing, Base.CodeUnits}`  as just `CodeUnits` without the `?`
> add `?` suffix to show on all return paths

- src/abstractdataframe/abstractdataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3443
> Improve names docs

- docs/src/man/comparisons.md
using dcast is simpler so you may consider mentioning that, for example below
```r
> data.table(iris)[, unlist(lapply(.SD, function(x) c(max=max(x), min=min(x)))), .SDcols = c("Petal.Length", "Petal.Width") ]
Petal.Length.max Petal.Length.min  Petal.Width.max  Petal.Width.min 
6.9              1.0              2.5              0.1 
> dcast(data.table(iris), . ~ ., list(max,min), value.var = c("Petal.Length", "Petal.Width"))
Key: <.>
. Petal.Length_max Petal.Width_max Petal.Length_min Petal.Width_min
<char>            <num>           <num>            <num>           <num>
1:      .              6.9             2.5                1             0.1
```
> dcast instead of SDcols

- docs/src/man/basics.md
1. Fixed link to regular expressions documentation
2. Deleted an empty line
3. Fixed bullet rendering in admonition
4. Switched order of last example
5. Wrapped some long lines
6. Changed operation list from definition syntax to bullet syntax
> Small formatting tweaks to #3360 after reviewing online
