JuliaData/DataFrames.jl

src/RDA.jl, src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/join.jl, src/abstractdataframe/reshape.jl, src/abstractdataframe/show.jl, src/dataframe/dataframe.jl, src/dataframe/io.jl, src/other/index.jl, src/statsmodels/formula.jl, src/subdataframe/subdataframe.jl, test/RDA.jl, test/data.jl, test/dataframe.jl, test/io.jl
which fixes some bugs on 0.4. Also fix a bug and reduce allocation in formula code.
=> Track recent Julia 0.4 changes

NEWS.md, docs/formulas.md, docs/getting_started.md, docs/index.md, docs/io.md, docs/joins.md, docs/pooling.md, docs/reshaping_and_pivoting.md, docs/sorting.md, docs/split_apply_combine.md, docs/subsets.md, mkdocs.yml
@tshort, this overwhelmingly consisted of changing the headers and the code markdown. I've done some other minor changes, e.g removed the "indexing" from "joins and indexing" because it wasn't talked about.
In later PRs, I'll add content, and I will also go through the existing content to make sure it's all still relevant.
=> Cleaned up MkDocs after conversion from Sphinx

src/abstractdataframe/io.jl, test/io.jl
This option specifies the string to be written when a NA value is encountered, defaults to "NA".
=> Add nastring option to printtable and writetable

src/statsmodels/statsmodel.jl, test/formula.jl, test/runtests.jl, test/statsmodel.jl
This should improve the coverage of both formula.jl and statsmodel.jl (#786)
=> add tests for statsmodel functions

src/dataframe/dataframe.jl, test/indexing.jl
Needed since JuliaLang/julia#10331
=> Add getindex/setindex! methods for Colon

doc/source/getting_started.rst
Fixed minor typo conver -> convert
=> Update getting_started.rst for minor type

src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/sort.jl, src/statsmodels/formula.jl, test/statsmodel.jl
`StatsBase.describe` should eventually be better synchronized between StatsBase and the extensions here, but this gets the package loading again.
=> Remove deprecation warnings and load error on 0.4

doc/source/reshaping_and_pivoting.rst
Just a minor rewording of a few words.
=> Fix minor grammatical error

src/abstractdataframe/abstractdataframe.jl
Workaround for #852 suggested by @MichaelHatherly
=> Fix docs parsing in Julia 0.4dev

docs/reshaping_and_pivoting.md
Ref @tshort answer on issue #854
=> Fix docs error with melt-unstack

doc/source/introduction.rst, doc/source/io.rst, docs/build.jl, src/abstractdataframe/abstractdataframe.jl, test/statsmodel.jl
~~Note: I may need a compat when using Void, let's see.~~
=> Fix remaining deprecations in tests and documentation.

src/abstractdataframe/reshape.jl, test/dataframe.jl
=> Fix unstack and add a test for it

REQUIRE, src/abstractdataframe/sort.jl, src/dataframe/sort.jl, src/groupeddataframe/grouping.jl, src/other/utils.jl, test/utils.jl
Looks like this also fixed tests for 0.3, no idea why...
=> Fix tests with Julia 0.5

src/abstractdataframe/show.jl
Changed the design of the show function using box-drawing characters
https://github.com/JuliaStats/DataFrames.jl/issues/881
=> Changed show function

NEWS.md
We need to tag a new version, so the Lapidary docs get generated for a tagged version. @nalimilan, did I miss anything that was added? Do you want to do the honors and tag and update METADATA?
=> Prep for tagging

.travis.yml, NEWS.md, docs/make.jl, docs/mkdocs.yml
https://github.com/MichaelHatherly/Documenter.jl/issues/1
=> Rename Lapidary to Documenter.

src/dataframe/dataframe.jl, test/REQUIRE, test/conversions.jl
=> Loosen Dict->DataFrame conversion to Associative->DataFrame

src/abstractdataframe/show.jl, src/dataframe/io.jl
Also improve a few docstrings and simplify code using @sprintf.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/983.
=> Fix deprecation warnings due to bytestring()

appveyor.yml
download from s3 instead of status.julialang.org
=> modernize appveyor

src/RDA.jl
The failure only affected Julia 0.5 since on 0.4.6 the corruption
happened everywhere: the bit pattern was consistent and comparisons
worked. See JuliaLang/julia#17195.
-------
This should completely fix the tests on 0.5. Therefore, I'd like to tag a new release after merging this, even if there still are deprecation warnings.
=> Fix failure of RDA test by working around a bug with NaN bit patterns

src/statsmodels/formula.jl, src/statsmodels/statsmodel.jl
Cf. https://github.com/JuliaStats/DataFrames.jl/issues/1012.
=> Clean up and document ModelMatrix logic

src/abstractdataframe/reshape.jl, test/dataframe.jl
=> Unstack: take type info from eltype of key column

src/statsmodels/formula.jl, test/formula.jl
Continuation of https://github.com/JuliaStats/DataFrames.jl/pull/1045.
=> fix issue from #1017

src/abstractdataframe/io.jl, src/abstractdataframe/show.jl, src/statsmodels/formula.jl, test/formula.jl, test/io.jl, test/show.jl
=> Better display of Nullables

src/dataframe/dataframe.jl
=> Fix docstring example

.travis.yml
@MichaelHatherly You put in the ``clone`` originally, just double checking that you are ok with this change here.
=> Use the tagged version of Documenter

docs/src/man/getting_started.md, docs/src/man/pooling.md, docs/src/man/split_apply_combine.md
I apparently missed these occurrences when removing these functions.
=> Small docs fixes

docs/src/index.md, docs/src/lib/maintypes.md, docs/src/lib/manipulation.md, docs/src/lib/utilities.md, docs/src/man/io.md
Makes minimal changes to fix https://github.com/JuliaStats/DataFrames.jl/issues/1116.
=> Fix Documenter online docs by moving to new syntax

src/abstractdataframe/io.jl
Added thead and tbody tags to table output for stricter HTML compliance and to support other formatting options e.g. datatables.net
=> Add thead and tbody tags

REQUIRE, src/abstractdataframe/show.jl, test/REQUIRE, test/show.jl
=> Juno Display (master branch)

docs/src/index.md
I can't test this one locally because Documenter never produces a table of content on my system...
=> Add querying chapter to table of content

README.md
Builds have stalled for several weeks on the current account on which
current maintainers have no control.
=> Move AppVeyor to another account

appveyor.yml, test/runtests.jl, test/stdin.sh
Backport/sideport of https://github.com/JuliaData/DataTables.jl/pull/2.
=> Test fixes

src/statsmodels/formula.jl, src/statsmodels/statsmodel.jl, test/formula.jl
My bad, these were omitted when I added the modeling stuff back to #1164.
=> Fix more 0.6 depwarns

REQUIRE, src/abstractdataframe/abstractdataframe.jl, test/utils.jl
Follows https://github.com/JuliaStats/StatsBase.jl/pull/247 and https://github.com/JuliaStats/DataArrays.jl/pull/248, addresses https://github.com/JuliaStats/DataFrames.jl/issues/1184
=> Remove describe code moved to DataArrays and StatsBase

src/abstractdataframe/abstractdataframe.jl
Fixes a failure on nightlies.
Closes https://github.com/JuliaStats/DataFrames.jl/issues/1196.
=> Import Base.unique! on Julia 0.7

src/other/index.jl, test/index.jl
=> Allow renaming column without change (Fixes #1195)

src/abstractdataframe/abstractdataframe.jl, test/dataframe.jl
=> Added return type annotation to `completecases(df)`.

src/dataframe/dataframe.jl
This should have been updated when NominalArray was replaced by CategoricalArray.
=> Rename 'nominal' argument to 'categorical'

src/DataFrames.jl, src/deprecated.jl, src/groupeddataframe/grouping.jl, test/data.jl, test/grouping.jl
=> deprecate pipelining with |>

src/dataframe/dataframe.jl, test/constructors.jl
a proposal of a small fix checking that `categorical` argument in `DataFrames` constructor has the right length.
=> check categorical argument length

REQUIRE, src/DataFrames.jl, src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/join.jl, src/dataframe/dataframe.jl, src/dataframerow/utils.jl, test/dataframe.jl, test/utils.jl
Based on running FemtoCleaner locally.
=> Fix some Julia 0.7 deprecations

src/dataframe/dataframe.jl, src/deprecated.jl
PR following discussion in #1361.
=> remove deprecation of vector of vectors DataFrame constructor

src/dataframe/dataframe.jl, test/dataframe.jl
Test some more corner cases of `insert!`.
@nalimilan Second part of #1372 fixes.
=> improve insert! test coverage

src/abstractdataframe/abstractdataframe.jl, test/dataframe.jl
=> make end work under Julia 0.7

src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/io.jl, src/abstractdataframe/show.jl, src/dataframerow/show.jl
=> Replaced occurrences of deprecated STDOUT with stdout

src/abstractdataframe/sort.jl, test/deprecated.jl
=> Fix error in depwarn call for old sort syntax

src/abstractdataframe/io.jl, test/io.jl
Companion PR to #1399 but for LaTeX.
=> fix showing of #undef in LaTeX

src/abstractdataframe/show.jl
For 0.7.  This was starting to annoy me.
=> Fixed showcompact deprecation

src/abstractdataframe/join.jl, test/join.jl
Together with #1421 closes #1412 .
=> add merge indicator function

src/abstractdataframe/join.jl, test/join.jl
Previous version of indicator function would modify input datasets. This corrects that behavior and adds tests.
=> patch bug in indicator that modified input datasets

src/abstractdataframe/join.jl, test/join.jl
Half of #1412 
Can anyone advise on how to handle the `on` argument for stranger cases (like dictionaries)? Looks like there's a system in place (`OnType`), but can't quite figure out.
=> first pass at key uniqueness checking

src/abstractdataframe/io.jl, src/abstractdataframe/show.jl, test/show.jl
Also changes the name of `nastring` to `missingstring`
=> make REPL printing of `nothing` an `empty string`

.travis.yml, src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/iteration.jl, src/abstractdataframe/join.jl, src/abstractdataframe/show.jl, src/abstractdataframe/sort.jl, src/dataframe/dataframe.jl, src/dataframerow/dataframerow.jl, src/deprecated.jl, src/groupeddataframe/show.jl, src/other/utils.jl, test/conversions.jl, test/data.jl, test/dataframe.jl, test/grouping.jl, test/io.jl, test/runtests.jl, test/show.jl, test/sort.jl
cc: @nalimilan @ararslan @bkamins
=> Updates to run on 1.0

src/abstractdataframe/abstractdataframe.jl
=> Fix typo in iterator protocol

src/abstractdataframe/abstractdataframe.jl, test/conversions.jl
Addresses #1474.
There are a few failing tests and a bunch of deprecation warnings, but a quick glance suggests that they're the same as on Master.
Please let me know if there's anything else I can do.
cc @nalimilan @bkamins
=> Matrix conversion method

src/abstractdataframe/join.jl, src/abstractdataframe/show.jl
Small improvements for things spotted at https://github.com/JuliaData/DataFrames.jl/pull/1471/files/098ccaad3f7abdeb4329b3868b0e42d26bedeba9#r208640755.
=> Small cleanup

src/abstractdataframe/reshape.jl, test/dataframe.jl
This is a transitory PR before #1482 is merged.
=> Deprecate unstack(df) current functionality

.travis.yml, appveyor.yml
The configuration now should be in sync with Julia 1.0
=> Updated travis and appveyor configuration to Julia 1.0

test/dataframe.jl
Part of #1467 and #1468 . This adds a new test to check that our description is working. I keep the `NaN` for `mean` with an empty array of numbers for now.
=> Tests for dataframe of length 0

src/groupeddataframe/grouping.jl, src/other/utils.jl, test/data.jl, test/utils.jl
=> Omit prefix in function names with aggregate

src/deprecated.jl
=> Fix readtable

src/abstractdataframe/show.jl, test/show.jl
@nalimilan Fixes of by one error per discussion in #1551.
=> fix a corner case of showing types

docs/src/man/getting_started.md, docs/src/man/querying_frameworks.md
This PR improves documentation in two areas:
* explaining how type information when showing a `DataFrame` works;
* improved DataFramesMeta.jl introduction.
=> Improve documentation

test/io.jl
@nalimilan this makes no functional changes but re-enables test that were temporarily disabled after Julia 1.0 (spotted during #1552 testing). I additionally cleaned up some code in the file.
=> Re-enable tests of LaTeXStrings and minor code layout fixes

src/abstractdataframe/abstractdataframe.jl, test/data.jl
Also update docstrings to new formatting conventions and improve them.
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1544.
=> Allow specifying columns to completecases, dropmissing and dropmissing!

src/abstractdataframe/abstractdataframe.jl, src/dataframerow/dataframerow.jl, src/dataframerow/utils.jl, src/subdataframe/subdataframe.jl
These no longer make any difference to generated code.
=> Remove obsolete special paths for Missing

src/groupeddataframe/grouping.jl, test/grouping.jl
@nalimilan A parallel effort to `getindex` cleanup for `AbstractDataFrame` but in this case I guess it is more clear cut what is the desired behavior.
=> Improve GroupedDataFrame API

src/abstractdataframe/abstractdataframe.jl, src/dataframe/dataframe.jl, src/other/index.jl, src/other/utils.jl, test/dataframe.jl, test/deprecated.jl, test/join.jl, test/tables.jl
Finish deprecation period for `makeunique` keyword argument. It has been for ~1 year now in this state.
=> Enforce makeunique

test/utils.jl
A test I have forgotten to turn on when cleaning `makeunique`.
=> fix makeunique test

test/grouping.jl
Also test it for functions returning a vector and a matrix. Refactor code to avoid duplication.
=> Improve tests for map(::Function, ::GroupedDataFrame)

src/deprecated.jl, test/subdataframe.jl
Additional `dump` ambiguity fix and improved `SubDataFrame` tests.
@nalimilan Afer this I think we can do the release.
=> Small dump fix

src/dataframe/dataframe.jl
Spotted that when double checking how the code runs after doing merge.
=> A better error message for deletecols!

src/other/tables.jl
=> Fix DataFrame(::AbstractVector{Any}) constructor

docs/make.jl, docs/src/man/getting_started.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1653.
=> Fix link to data manipulation frameworks in docs

src/other/tables.jl, test/REQUIRE, test/tabletraits.jl
Fixes #1597.
@davidanthoff Could you suggest a test to ensure this doesn't regress?
=> Make any AbstractDataFrame an iterable table

REQUIRE, src/other/tables.jl, test/tabletraits.jl
Requires https://github.com/JuliaData/Tables.jl/pull/45
=> Adjust for Tables taking care of TableTraits logic

src/groupeddataframe/grouping.jl, test/grouping.jl
=> Add `parent` to grouped dataframes

src/abstractdataframe/abstractdataframe.jl, test/dataframe.jl
Adding tests and minor cleanups for #1291.
=> add tests for similar with 0 rows

test/dataframe.jl
It seems there are residuals of the same code to test the equality of DataFrame.
=> Remove duplicate tests for DataFrame equality

.travis.yml
Bounds checking is already enabled by default.
=> Use standard Travis script

REQUIRE, src/other/tables.jl, test/tables.jl
=> Fix constructor for Vector{<:NamedTuple}

src/abstractdataframe/io.jl, test/grouping.jl
=> show GroupedDataFrame with CSV and TSV mime

docs/src/man/joins.md
Following the discussion on Slack.
=> Improve explanation how join works with duplicates

src/dataframerow/dataframerow.jl, src/groupeddataframe/grouping.jl
Tried to have some more links and make types code highlighted!
=> xrefs and backticks for the docs

docs/src/lib/functions.md, src/dataframe/dataframe.jl, src/dataframerow/dataframerow.jl, test/dataframe.jl, test/dataframerow.jl
Following https://discourse.julialang.org/t/best-way-to-iteratively-add-to-a-dataframe/21084/9 by @nalimilan .
At first I was reluctant to add it, but in the end I think it does not hurt to have it (I do not see a scenario when this is risky).
I have also added documentation for `push!`. I have split two cases of `push!` into two comments as this is really a different functionality and describing it together might be confusing.
=> improve push! and document it

src/abstractdataframe/io.jl, src/abstractdataframe/show.jl, test/show.jl
Fixes #1762 and additionally wrapped tests of show in `@testset`
=> Add :compact handling in show and organize show tests

.travis.yml, REQUIRE, appveyor.yml, test/constructors.jl, test/data.jl, test/dataframerow.jl, test/grouping.jl, test/tables.jl, test/tabletraits.jl
Following the discussion in #1772.
=> remove Julia 0.7 dependencies

README.md, docs/src/index.md
Changes:
* remove a broken link from README.md
* add a description of what is considered a part of public API of DataFrames.jl
* minor layout changes
=> Minor updates to the documentation

test/grouping.jl
See https://github.com/JuliaData/DataFrames.jl/pull/1826#issuecomment-496014806.
=> More tests for empty groups in map on GroupedDataFrame

Project.toml
@quinnj, @davidanthoff - if dependency versions in `[compat]` should be changed please comment (I think they do not, but I might have missed something).
=> Increase package version for a release

src/groupeddataframe/grouping.jl
closes #1817 and some additional small documentation fixes to make it more consistent
=> small documentation fixes of split-apply-combine

docs/src/lib/indexing.md, docs/src/man/getting_started.md, src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/reshape.jl, src/dataframe/dataframe.jl, src/dataframerow/dataframerow.jl, src/other/index.jl, src/subdataframe/subdataframe.jl, test/data.jl, test/dataframe.jl, test/dataframerow.jl, test/index.jl, test/indexing.jl, test/subdataframe.jl
@nalimilan - this follows our discussion on Slack. If you find the changes OK I will update the documentation accordingly and write tests.
=> Regex handling in columns

src/other/index.jl
Try to throw a similar message with other BoundsErrors but not sure the given message is the best one for this case. Please feel free to revise the message. #1868
=> Throw an exception with msg rather than error() with it.

src/dataframe/dataframe.jl
As requested, add an error message to BoundsError(). Not sure if the given message is the best one in this case. Please feel free to change the message. #1867
=> Add an error message to give more details

src/abstractdataframe/abstractdataframe.jl
Small things I noticed when I review all code for `!` indexing change.
=> Minor cleanup of abstractdataframe.jl

src/deprecated.jl
Make it more specific for 0-column data frames.
=> Fix setindex! deprecation message

src/dataframe/dataframe.jl, src/other/index.jl, test/dataframe.jl
=> Raise a more specific ArgumentError rather than a general Error

Project.toml, docs/src/lib/types.md, docs/src/man/getting_started.md, docs/src/man/reshaping_and_pivoting.md, test/dataframe.jl
Fixes #1910
(I hope I have not missed anything)
=> Update documentation to reflect ! indexing

src/abstractdataframe/join.jl, test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1915
=> Deprecate Tuple as a value of on keyword argument in join

src/abstractdataframe/io.jl, src/abstractdataframe/iteration.jl, test/dataframerow.jl, test/io.jl, test/iteration.jl, test/show.jl
This replaces #1901. I have opened a new branch as GitHub showed a large diff after rebasing
=> Add custom show to DataFrameRows and DataFrameColumns

src/abstractdataframe/abstractdataframe.jl
=> fix AbstractDataFrame docstring

src/abstractdataframe/abstractdataframe.jl, src/dataframe/dataframe.jl, test/dataframe.jl
=> add type argument to categorical and categorical!

src/abstractdataframe/iteration.jl, test/iteration.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1895.
CC @oschulz
=> add getproperty and propertynames for data frame iterators

src/abstractdataframe/iteration.jl, test/iteration.jl
=> make sure mapcols does not reuse source vectors

src/dataframerow/dataframerow.jl, test/dataframerow.jl
@nalimilan spotted after your `eltypes` removal PR.
=> fix Vector for DataFrameRow eltype detection

src/abstractdataframe/abstractdataframe.jl
Hello. 
Is this a typo?
I'm new in Julia's DataFrame. I'm sorry if I'm wrong. 
Thank you.
=> Fix documentation

docs/src/lib/functions.md, src/DataFrames.jl, src/dataframe/dataframe.jl, src/deprecated.jl, src/subdataframe/subdataframe.jl, test/dataframe.jl
=> allow passing multiple columns arguments to select and select!

docs/src/man/getting_started.md
These are two things that commonly pop up on Discourse/Slack, so I thought adding it to getting started might be a good idea.
=> Add InvertedIndex and `in()` examples

src/groupeddataframe/grouping.jl
This dramatically improves performance for very small data sets.
Fixes #1988.
=> Avoid recompiling combine for each new NamedTuple or Tuple type

src/abstractdataframe/join.jl, test/join.jl
=> allow mixing Symbol and Pair{Symbol,Symbol} in on for joining

docs/src/man/getting_started.md, src/dataframe/dataframe.jl
=> update documentation of select

src/abstractdataframe/abstractdataframe.jl, src/dataframerow/dataframerow.jl, src/deprecated.jl, test/conversions.jl, test/dataframerow.jl
Following the discussion on Slack
=> add Array convert for data frame and data frame row

src/abstractdataframe/abstractdataframe.jl, src/deprecated.jl
=> deprecate io support in describe

.github/workflows/CompatHelper.yml
@nalimilan This PR sets CompatHelper to run once a day on the DataFrames.jl repo.
=> Run CompatHelper once a day

test/tables.jl
This PR cherry-picks a test from #2003.
=> Test append!(df, row_access_table)

test/grouping.jl
I don't really understand why we get `"DataFrames.GroupedDataFrame"` when doing `include("test/grouping.jl")`... Any idea?
=> Make grouping.jl test pass when using include

src/groupeddataframe/splitapplycombine.jl
=> add missing `

src/abstractdataframe/abstractdataframe.jl
we only allow vectors not arbitrary arrays
=> correct rename and rename! signature in documentation

test/deprecated.jl
Remove leftover import in tests.
=> Remove wrong import

src/other/tables.jl, test/tables.jl
Added missing Tables.jl integrations.
@quinnj - could you please have a look if all is correct?
=> add Tables.jl integration for eachrow and eachcol

src/other/tables.jl, test/tables.jl
=> improve speed of Tables.namedtupleiterator

src/dataframe/dataframe.jl, src/other/index.jl, src/other/utils.jl, test/dataframe.jl, test/index.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/1879
=> [BREAKING] Change ArgumentError to DimensionMismatch

docs/src/man/getting_started.md
This is my first pull request, I'm not sure if I am properly following the style guide.
Thanks
=> Add replacement examples to getting_started.md

src/abstractdataframe/io.jl, src/abstractdataframe/iteration.jl, src/abstractdataframe/show.jl, src/dataframerow/show.jl, test/dataframerow.jl, test/io.jl
This is a follow-up to #2142 completing the changes.
(as this is a clean-up PR I have also added some minor changes to unrelated code - specifically I have changed comments giving an expected return types of functions to assertions)
=> finalize adding eltypes to show

.travis.yml, test/indexing.jl, test/indexing_begin_tests.jl, test/select.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2089
+ change Julia version against which we run tests
=> update to Juia 1.4

src/dataframe/dataframe.jl
correct use of `eachcol` in `append!`
=> fix deprecation in append

docs/src/man/sorting.md, src/abstractdataframe/sort.jl, src/dataframe/sort.jl, test/deprecated.jl, test/sort.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2178
TODO: I will fix `aggregate` deprecation code here or in #2174 depending what gets merged first.
=> [BREAKING] Deprecate passing tuple of columns to sort

src/abstractdataframe/reshape.jl
@nalimilan It would be good to merge this before #2188 and before the PR allowing string indexing.
The old design was overly complex and was hard to reason about for me (both mentioned PRs will be simpler after this change).
The functionality is untouched.
=> clean-up reshaping code

src/dataframe/dataframe.jl, test/dataframe.jl
This is not urgent, but simple and will improve consistency.
=> add Not to delete!

docs/src/man/categorical.md
Shame on me! This time I've checked that the result is correct.
=> Fix exponent in docs

Project.toml, src/groupeddataframe/splitapplycombine.jl, test/grouping.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2241.
I have bumped version in the PR. When we merge it I will cherry pick it (+ maybe some other non-breaking PRs we have merged) and make a 0.21.1 release.
=> fix bug in reduceinit

src/abstractdataframe/show.jl
it is described in details but signature missed it
=> add eltypes to show docstring

src/abstractdataframe/join.jl, test/join.jl
Fix #1732
To see the result take out the test code and run it in REPL (just remove `@test_throws` and make sure that the loops go on working and do not stop after first error)
=> improve error message when validating

src/abstractdataframe/io.jl, src/abstractdataframe/show.jl, src/dataframerow/dataframerow.jl, src/groupeddataframe/show.jl
Needed because of https://github.com/JuliaLang/julia/pull/36303.
(@nalimilan - the same problem is in CategoricalArrays.jl I if I recall correctly)
=> fixes to follow breaking changes in printing in 1.6

src/groupeddataframe/groupeddataframe.jl
As suggested by @nalimilan this should improve performance a bit and still be thread safe.
=> move lock inside if clause

src/dataframerow/dataframerow.jl
The old examples were actually bad (users should not do things what they show).
=> update DataFrameRow documentation

Project.toml, src/abstractdataframe/show.jl, test/show.jl
=> fix show of UnionAll

docs/Project.toml
Change documenter version to latest 0.25. This is mainly needed to allow for dark theme.
=> Up Documenter.jl

src/other/broadcasting.jl
I noticed this due to https://github.com/JuliaLang/julia/pull/36810, but even if that is merged we should fix the comprehension in DataFrames.jl.
=> make colnames type stable in broadcasting

src/dataframerow/dataframerow.jl, src/subdataframe/subdataframe.jl
We disallowed duplicates some time ago. I just forgotten do remove these two sections of the documentation.
=> Update outdated documentation

.travis.yml, Project.toml
Update after the release of Julia 1.5.
=> Change Travis from Julia 1.4 to 1.5

CONTRIBUTING.md, NEWS.md, README.md
Following the discussions on Slack I have made an update to contribution guidelines.
=> update contribution guidelines and add NEWS.md

docs/src/index.md
I have almost not changed anything to make merging this PR easy. The only major point I change is noted in the comment of the PR.
=> fix formatting of index.md in the manual

src/groupeddataframe/splitapplycombine.jl
The functionality was changed in https://github.com/JuliaData/DataFrames.jl/pull/2324
=> fix wrong docstring that was a leftover of changing the aggregation rules

docs/src/man/sorting.md
It seems like potential duplicated line in sorting page.
=> Remove the duplicated line.

docs/src/index.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2407
=> Add a reference to Impute.jl

docs/src/man/comparisons.md
=> Update dplyr example in comparisons.md

src/dataframe/dataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2361
=> Improve docstring of DataFrame

docs/src/man/getting_started.md
=> improve references to indexing rules in the manual

README.md
@quinnj - is this all we need to change in DataFrames.jl?
=> Change Travis link

src/abstractdataframe/iteration.jl, test/iteration.jl
=> mapcols!(): exit early if no columns

src/abstractdataframe/sort.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2500
=> make sure by isa Function or a vector of functions

.codecov.yml, .travis.yml, README.md
Coveralls has been broken for weeks.
=> Switch from Coveralls to Codecov

Project.toml, README.md
=> fix coverage badge

test/join.jl
Remove another CategoricalArrays.jl dependency I missed earlier.
=> update deprecated tests

src/abstractdataframe/show.jl, test/show.jl
=> Fix size of float columns without eltypes

docs/src/lib/types.md, docs/src/man/split_apply_combine.md, src/abstractdataframe/selection.jl
Fixes issue #2550.
I looked through the contributor's guide, but didn't see anything about local testing before submitting a PR.  Please let me know if there is documentation that I missed and should follow.  Thanks.
=> issue #2550 fix two small typos in docs

docs/src/index.md
add a list of curated DataFrames.jl tutorials.
@tk3369 - please comment if you like it this way
=> add links to curated DataFrames.jl materials

.github/workflows/ci.yml
Hopefully this will fix the gh-pages problem we have now.
CC @nalimilan @quinnj
=> Update ci.yml from master to main

docs/src/man/split_apply_combine.md, src/abstractdataframe/selection.jl
With a handful of groups, specialization does not really matter.
=> Mention number of groups in performance note

test/broadcasting.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2643
=> fix broadcasting tests for Julia 1.7

test/grouping.jl
=> fix split-apply-combine tests

NEWS.md, Project.toml, src/abstractdataframe/abstractdataframe.jl, src/dataframe/dataframe.jl, src/dataframerow/dataframerow.jl, src/deprecated.jl, src/groupeddataframe/groupeddataframe.jl, test/conversions.jl, test/deprecated.jl, test/grouping.jl
=> Deprecate unnecessary convert methods

test/indexing.jl
@nalimilan - let us see if this helps.
=> Reduce test memory consumption

NEWS.md, Project.toml
PR tracking 0.22.7 release I am making right now.
=> 0.22.7 release notes

docs/src/man/comparisons.md
=> reviewed and fixed

docs/make.jl
=> make "Edit on Github" points to main branch

docs/src/index.md, docs/src/man/importing_and_exporting.md
=> add information how DelimitedFiles can be used

docs/Project.toml
It includes handling of old package versions.
=> Use latest Documenter.jl

NEWS.md, src/abstractdataframe/subset.jl, src/groupeddataframe/groupeddataframe.jl, test/grouping.jl, test/io.jl
=> improve subset! for GroupedDataFrame

docs/src/man/basics.md
=> review of the DataFrames.jl tutorial

docs/src/man/split_apply_combine.md, src/abstractdataframe/selection.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2830
=> explain that fun => target does not work in general

docs/src/man/basics.md
=> Fix typo math => match

docs/src/lib/functions.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2795
=> Add muli-threading support description to the manual

test/io.jl, test/show.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2846
I have tested these changes both with and without color.
=> Disable color testing when color is not supported

src/other/utils.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/2850
=> Improve docstring of AsTable

Project.toml, src/DataFrames.jl
=> use nrow and ncol from DataAPI.j

src/abstractdataframe/reshape.jl, src/abstractdataframe/sort.jl, test/grouping.jl, test/reshape.jl
=> fix transpose error message and clean up code

docs/src/man/basics.md
swapped : for ! for reference syntax
=> fix: do not copy syntax is with !

docs/src/man/getting_started.md, src/abstractdataframe/abstractdataframe.jl
Hi, @bkamins! Based on the comments in #2877, improving docstring rather than adding a new argument should be better. Examples that might be able to fix #2747 are added.
If there is something wrong or not suitable, please let me know, and I will manage to fix them.
=> Improve docstring for names()

src/abstractdataframe/abstractdataframe.jl, src/other/index.jl
In this PR I want to collect changes that are not breaking but just aimed at improving error messages.
I will make it not-draft after some more suggestions what should be fixed are collected.
CC @pdeffebach
=> code cleanup to improve error messages

test/dataframe.jl
Fix test problem following the change in https://github.com/JuliaLang/julia/pull/37343.
=> Fix tests of names

docs/src/man/importing_and_exporting.md
I've found it giving the fastest possible workflow for moving data from a running Julia process to Excel/PowerPoint, so I think it is worth mentioning :) 
cc @pdeffebach
=> mention ClipData.jl

src/abstractdataframe/sort.jl, src/dataframe/sort.jl
This is a sample PR, I enhanced the readability by adding a newline for each keyword argument.
=> Improve Docstrings for `sort` and `sort!`

NEWS.md, Project.toml, src/dataframe/dataframe.jl, src/subdataframe/subdataframe.jl, test/indexing.jl
=> fix getindex with vector of Pairs

NEWS.md, Project.toml, src/abstractdataframe/selection.jl, test/select.jl
fixes https://github.com/JuliaData/DataFrames.jl/issues/2957
TODO: add NEWS.md entry after #2981 is merged
=> make sure ByRow invokes generic map

NEWS.md, src/groupeddataframe/groupeddataframe.jl, test/grouping.jl
fixes https://github.com/JuliaData/DataFrames.jl/issues/2954
=> add ungroup keyword argument to filter

src/dataframe/dataframe.jl
Also add missing backticks and mention `PooledVector`.
=> Fix keyword argument syntax in `DataFrame` docstring

src/join/composer.jl, test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3039
=> make sure we correctly pass matchmissing in joins

NEWS.md, src/abstractdataframe/abstractdataframe.jl, src/abstractdataframe/selection.jl, src/other/utils.jl, test/index.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3062
=> make AsTable more careful when accepting argument

docs/src/man/split_apply_combine.md, src/abstractdataframe/selection.jl
Missed by https://github.com/JuliaData/DataFrames.jl/pull/3030.
=> Update remaining docs to reflect `threads` argument

src/join/composer.jl, test/join.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3088
=> Improve join error message

docs/src/man/working_with_dataframes.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3086
=> Add more examples of operation specification language

src/join/composer.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3091
=> fix wrong docs of outerjoin

src/abstractdataframe/sort.jl, src/dataframe/dataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3134
=> Remove unused where clauses

CONTRIBUTING.md, NEWS.md, docs/src/index.md, docs/src/man/basics.md, docs/src/man/reshaping_and_pivoting.md
https://github.com/JuliaData/DataFrames.jl/issues/3141
this commit only fixes .md files
=> markdown typos

src/abstractdataframe/io.jl, src/abstractdataframe/selection.jl, src/groupeddataframe/splitapplycombine.jl, src/groupeddataframe/utils.jl, src/other/utils.jl, test/broadcasting.jl
https://github.com/JuliaData/DataFrames.jl/issues/3141
merging would close the issue
=> fix typos in docs and comments

docs/src/index.md, docs/src/man/getting_started.md
Broken links as reported by documenter checks .
=> Fix broken links in docs

test/join.jl
x-ref https://github.com/JuliaData/DataFrames.jl/pull/3096#issuecomment-1249150419
=> further improve OutOfMemory problem handling in tests

docs/src/lib/metadata.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3168
=> Improve metadata documentation

Project.toml, src/other/tables.jl, test/tables.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3180
=> switch from view to viewhint in Tables.subset

NEWS.md, Project.toml, src/abstractdataframe/abstractdataframe.jl, test/reshape.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3197
(I will wait with the release some time as we might have some more patches; this bug is minor)
=> make sure flatten works corretly on a data frame with zero rows

NEWS.md, src/abstractdataframe/abstractdataframe.jl, test/metadata.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3218
=> fix insertcols! bug (not shifting column metadata)

src/abstractdataframe/reshape.jl
I have forgotten to update the docstring in one place after `unstack` changes.
=> Fix unstack docstring

test/io.jl
Fixes a difference between Julia versions in tests because of https://github.com/JuliaLang/julia/pull/47708
=> fix markdown tests

src/other/index.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3241
=> improve error message when used selector is incorrect

docs/src/index.md
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3259
=> document breaking change policy

NEWS.md, src/abstractdataframe/selectionfast.jl, test/select.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3267
=> Fix error in fast aggregation of missing only columns for sum and mean

NEWS.md, src/subdataframe/subdataframe.jl, test/subdataframe.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3272
=> correctly index into a SubDataFrame with no columns

.github/workflows/CompatHelper.yml
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3278
=> update CompatHelper.jl setup

docs/src/man/basics.md
@timholy - could you please check that this is the way we should inform users how they can disable precompilation of DataFrames.jl if they with to do so? Thank you!
=> Update documentation of how to disable precompilation

docs/src/index.md
Some users prefer to learn from a book.
=> Add "Julia for Data Analysis" reference in manual

src/abstractdataframe/reshape.jl, test/reshape.jl
Fixes https://github.com/JuliaData/DataFrames.jl/issues/3339
=> improve unstack error messages

docs/src/man/querying_frameworks.md
Users often think that meta-packages make life more complex, which is not the case 😄.
=> Explain the role of querying frameworks for DataFrames.jl

src/abstractdataframe/abstractdataframe.jl
Per discussion in above issue. Let me know if you would prefer different phrasing.
=> Update filter docs, Fixes #3460

src/groupeddataframe/groupeddataframe.jl
=> typo, df was d

docs/src/man/comparisons.md
Closes #3476 
This PR adds documentation about translating between reshape operations.
=> compare stack/unstack to data.table melt/dcast

docs/src/man/categorical.md
Change in `levels` behavior.
cc @nalimilan
=> Update categorical.md after CategoricalArrays.jl release
